web/cgi-bin/horas/do_io.pl

code: remove support for reading non utf8 files

---

web/www/horas/Latin/Tempora/115-0.txt

115-0 Lectio4 source & accents

---

web/cgi-bin/horas/monastic.pl

MONASTIC code: fix 3rd nocturn canticles

---

web/cgi-bin/horas/monastic.pl

MONASTIC code: fix 2 nocturn reading in Epiphanytide ferias

---

web/cgi-bin/horas/horascommon.pl

code: remove empty 'Tempora:' from header

---

web/cgi-bin/horas/specials.pl

MONASTIC code: fix minor hours Ants on 01-10

---

web/cgi-bin/horas/monastic.pl

MONASTIC code: fix versicle in 1st Nocturn in Epihany octave after Sunday

---

web/www/horas/Help/technical.html

"**C12** : Little Office of the Blessed Virgin Mary" added to `Help/technical.html`

C12 added to technical.html

---

web/www/horas/English/Sancti/01-21.txt

correction of English for  ℟ for Matins of St. Agnes's feast

marriagechamber → marriage-chamber

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/specials.pl
web/cgi-bin/horas/specmatins.pl

code: rewrite handling hymns

---

web/www/horas/Latin/SanctiM/01-25.txt
web/www/horas/Latin/SanctiM/02-24.txt
web/www/horas/Latin/SanctiM/12-25.txt

MONASTIC corrections: 01-25 02-24 12-25

---

web/www/horas/Deutsch/Psalterium/Psalmi matutinum.txt
web/www/horas/English/Psalterium/Psalmi matutinum.txt
web/www/horas/Latin/Psalterium/Psalmi matutinum.txt

The Versicle for the Monastic 3rd Nocturn on Sundays per annum is corrected in Latin, English and German (Latin again) not to give the Versicle of Sundays in Advent.

Correction in PsalmiMatutinum.txt

---

web/www/horas/Polski/Psalterium/Psalmi matutinum.txt
web/www/horas/Polski/Tempora/Epi2-2.txt
web/www/horas/Polski/Tempora/Epi5-2.txt
web/www/horas/Polski/Tempora/Quadp1-1.txt
web/www/horas/Polski/Tempora/Quadp2-0.txt

Polski: corrections and more translations

---

web/www/horas/English/Tempora/Quadp2-0.txt
web/www/horas/Espanol/Tempora/Quadp2-0.txt
web/www/horas/Francais/Tempora/Quadp2-0.txt
web/www/horas/Italiano/Tempora/Quadp2-0.txt
web/www/horas/Latin/Tempora/Quadp2-0.txt
web/www/horas/Latin/TemporaM/Quadp2-0.txt
web/www/horas/Polski/Tempora/Quadp2-0.txt

rework on fix #2755

---

web/www/horas/Help/credits.html
web/www/horas/Polski/SanctiM/03-12.txt
web/www/horas/Polski/SanctiM/03-21.txt

MONASTIC Polski 03-{12,21} translation courtesy adiutorium.pl

---

web/cgi-bin/horas/specials.pl
web/www/horas/English/SanctiM/03-12.txt
web/www/horas/English/TemporaM/Quadp1-0.txt
web/www/horas/Latin/SanctiM/03-12.txt
web/www/horas/Latin/Tempora/Quadp1-6.txt

Few updates

---

web/cgi-bin/horas/specials.pl

This reverts commit d67f3f70ca61359e17847044609e7c655e42faf7.
+AMDG+

Revert "code: add initial to hymn" as it breaks hymns with rubrics

---

web/www/horas/Portugues/Psalterium/Minor Special.txt

Update Minor Special.txt

---

web/www/horas/Francais/Psalterium/Major Special.txt
web/www/horas/Francais/Sancti/10-20.txt
web/www/horas/Francais/Tempora/083-2.txt
web/www/horas/Italiano/Psalterium/Doxologies.txt

fix Saturday Laudes Hymn in French & similar

---

web/www/horas/Latin/Sancti/03-07.txt

MONASTIC 03-07 rank fix

---

web/www/horas/English/CommuneM/C4.txt
web/www/horas/English/SanctiM/03-12.txt
web/www/horas/Latin/CommuneM/C4.txt
web/www/horas/Latin/SanctiM/03-12.txt

MONASTIC 03-12 & C4 update

---

web/cgi-bin/horas/dialogcommon.pl
web/cgi-bin/horas/monastic.pl
web/www/horas/Latin/CommuneM/C1.txt
web/www/horas/Latin/CommuneM/C11.txt
web/www/horas/Latin/CommuneM/C1p.txt
web/www/horas/Latin/CommuneM/C2.txt
web/www/horas/Latin/CommuneM/C2p.txt
web/www/horas/Latin/CommuneM/C3.txt
web/www/horas/Latin/CommuneM/C3p.txt
web/www/horas/Latin/CommuneM/C4.txt
web/www/horas/Latin/CommuneM/C5.txt
web/www/horas/Latin/CommuneM/C6.txt
web/www/horas/Latin/CommuneM/C7.txt
web/www/horas/Latin/CommuneM/C8.txt
web/www/horas/Latin/SanctiM/02-10.txt
web/www/horas/Latin/SanctiM/03-12.txt
web/www/horas/Latin/SanctiM/03-21.txt
web/www/horas/Latin/SanctiM/11-13.txt
web/www/horas/Latin/TemporaM/Nat2-0.txt

MONASTIC LectioE workaround

---

web/www/horas/Latin/CommuneM/C2.txt
web/www/horas/Latin/CommuneM/C2p.txt
web/www/horas/Latin/CommuneM/C3.txt
web/www/horas/Latin/CommuneM/C4a.txt
web/www/horas/Latin/CommuneM/C5.txt
web/www/horas/Latin/CommuneM/C5a.txt

adjust "LectioE in 2 loco" etc. to point to the right hash in missa in accordance to monastic.pl

CommuneM LectioE

---

web/www/horas/Polski/Psalterium/Psalmi major.txt

Add missing letter in "nienawiści" word in polish translation of antiphon for day 3 Vespera.

Add missing letter in "nienawiści" word in polish translation 

---

web/cgi-bin/horas/specials.pl
web/cgi-bin/horas/webdia.pl
web/www/horas/horas.dialog
web/www/horas/horas.setup

code: setup refactor & add option 'use antique hymns'

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/horas.dialog
web/www/horas/horas.setup

code: new option 'nonumbers' to hide verse numbers in psalms & readings

---

web/www/horas/Latin/SanctiM/04-29.txt

MONASTIC: 04-29 Hymnus Matutinum (links here hangs)

---

web/cgi-bin/horas/horas.ini

relative htmlurl

---

web/cgi-bin/horas/specmatins.pl

code: auto add initials to matutinum readings

---

web/cgi-bin/horas/specials.pl

code: fix rubrics display in hymn as in Vexilla Regis

---

web/cgi-bin/horas/specmatins.pl

code: fix auto initials in Matutinum readings

---

web/cgi-bin/horas/specmatins.pl

code: fix auto initials in Matutinum readings - correction

---

web/www/horas/English/SanctiM/03-25.txt
web/www/horas/English/TemporaM/Pasc0-0.txt
web/www/horas/English/TemporaM/Quad5-0.txt
web/www/horas/Latin/Psalterium/Matutinum Special.txt
web/www/horas/Latin/Psalterium/Psalmi matutinum.txt
web/www/horas/Latin/SanctiM/03-25.txt
web/www/horas/Latin/TemporaM/Pasc0-0.txt
web/www/horas/Latin/TemporaM/Quad5-0.txt

MONASTIC update: links, spelling

---

web/www/horas/Polski/Sancti/03-25.txt
web/www/horas/Polski/Tempora/Pasc1-0.txt
web/www/horas/Polski/Tempora/Quad5-1.txt
web/www/horas/Polski/Tempora/Quad6-2.txt
web/www/horas/Polski/Tempora/Quad6-3.txt
web/www/horas/Polski/Tempora/Quad6-5.txt
web/www/horas/Polski/TemporaM/Pasc0-0.txt
web/www/horas/Polski/psalms1/Psalm21.txt

Polski update

---

web/www/horas/Polski/Commune/C1.txt
web/www/horas/Polski/Commune/C1p.txt
web/www/horas/Polski/Sancti/04-25.txt

Polski: update for 04-25

---

web/cgi-bin/horas/horas.pl

code: omit initials in psalm 118, when using 'hide verse numbers'

---

web/cgi-bin/horas/horas.pl

code: restore initials in Canticles removed in 1a25c321f

---

web/cgi-bin/missa/missa.pl

- clean options page
- fix Missa Persoluta link
+AMDG+

code: missa

---

web/cgi-bin/horas/horascommon.pl
web/www/horas/Latin/Psalterium/Mariaant.txt
web/www/horas/Latin/Psalterium/Prayers.txt

Per eumdem spell variants

---

web/cgi-bin/DivinumOfficium/Main.pm

code: white colour for Vigilia Ascensionis

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/monastic.pl
web/www/horas/Deutsch/Ordinarium/MatutinumM.txt
web/www/horas/English/Ordinarium/MatutinumM.txt
web/www/horas/English/Ordinarium/PrimaM.txt
web/www/horas/English/Psalterium/Translate.txt
web/www/horas/Espanol/Ordinarium/MatutinumM.txt
web/www/horas/Espanol/Ordinarium/PrimaM.txt
web/www/horas/Italiano/Ordinarium/MatutinumM.txt
web/www/horas/Italiano/Ordinarium/PrimaM.txt
web/www/horas/Latin/Ordinarium/MatutinumM.txt
web/www/horas/Latin/Ordinarium/PrimaM.txt
web/www/horas/Latin/Psalterium/Translate.txt
web/www/horas/Magyar/Ordinarium/MatutinumM.txt
web/www/horas/Magyar/Ordinarium/PrimaM.txt
web/www/horas/Polski/Ordinarium/MatutinumM.txt
web/www/horas/Polski/Ordinarium/PrimaM.txt

MONASTIC: correction of Matutinum & Prima with neccessary code changes

---

web/cgi-bin/horas/horas.pl

code: fix Divinum_auxilium

---

web/cgi-bin/horas/kalendar.pl

code: fix Ordo when called from missa

---

web/cgi-bin/horas/Cofficium.pl
web/cgi-bin/horas/Pofficium.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/webdia.pl
web/cgi-bin/missa/missa.pl

code: bottom_links_menu

---

web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/specials.pl
web/www/horas/English/Sancti/05-19.txt
web/www/horas/English/Sancti/05-19o.txt
web/www/horas/Espanol/Sancti/05-19.txt
web/www/horas/Francais/Sancti/05-19.txt
web/www/horas/Italiano/Sancti/05-19.txt
web/www/horas/Latin/Sancti/05-19.txt
web/www/horas/Latin/Sancti/05-19o.txt
web/www/horas/Polski/Sancti/05-19.txt

- use links
- code: add postprocessing Ant and Vs in linked Commemoratio
- code: correct header information about commemoratio
+AMDG+

Another workaround about #2905

---

web/cgi-bin/DivinumOfficium/Main.pm
web/cgi-bin/horas/Cofficium.pl
web/cgi-bin/horas/Pofficium.pl
web/cgi-bin/horas/dialogcommon.pl
web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/setup.pl
web/cgi-bin/horas/webdia.pl
web/cgi-bin/missa/missa.pl
web/www/horas/Linguae.txt
web/www/horas/Versions.txt
web/www/horas/horas.dialog
web/www/horas/horas.setup
web/www/missa/missa.dialog

Reverts DivinumOfficium/divinum-officium#2908

Revert "code: use .dialog data for selectable elements, generate horas menu"

---

web/cgi-bin/horas/webdia.pl

code: restore horas menu positions in Pofficium

---

web/cgi-bin/horas/specials.pl
web/www/horas/Latin/Sancti/04-14-com-tp.txt
web/www/horas/Polski/Sancti/04-14.txt

fix #2917 + Polski/04-14 fix comm

---

web/www/horas/Latin/Martyrologium/Mobile.txt
web/www/horas/Latin/Psalterium/Psalmi matutinum.txt

add Octave of Asccension to Mobile
lowercase alleluja in Matutinum Verses
+AMDG+

Latin update

---

web/cgi-bin/horas/specmatins.pl
web/www/horas/English/TemporaM/Pasc6-0.txt
web/www/horas/Latin/SanctiM/05-25.txt
web/www/horas/Latin/SanctiM/05-27.txt
web/www/horas/Latin/TemporaM/Pasc6-0.txt

no commemoration on 05-2[57]
Pasc6-0 Lectio6 layout
code: fix Paschaltide Invit broken by adding new section to Prayers!
+AMDG+

MONASTIC: update

---

web/www/horas/Latin/Sancti/05-31o.txt

05-31 add 1570 matutinum readings

---

web/www/missa/Latin/Ordo/Ordo.txt
web/www/missa/Latin/Ordo/Ordo67.txt

Punctuation

---

web/www/horas/Latin/TemporaM/Pent01-5.txt

MONASTIC Pent01-5 Oratio

---

web/www/horas/Latin/Sancti/06-25o.txt

06-25 1570 Matutinum readings

---

web/cgi-bin/horas/specials.pl

MONASTIC code: fix Laudes canticle on 06-23 etc. when it is not Vigil

---

web/www/horas/English/Sancti/07-18o.txt
web/www/horas/Latin/Sancti/07-18o.txt
web/www/horas/Latin/Tempora/Pent03-0o.txt

- Pent03-0 Matutinum readings & responsories
- 07-18 Matutinum readings
+AMDG+

1570 update

---

web/www/horas/English/Sancti/07-02.txt
web/www/horas/Help/rubrics.html
web/www/horas/Latin/Sancti/07-02.txt

rubrics.html - use webarchive for nonexistent links, relative paths
+AMDG+

07-02 Responsories from Commune + 

---

web/www/horas/Polski/Commune/C11.txt
web/www/horas/Polski/Martyrologium/07-01.txt
web/www/horas/Polski/Martyrologium/07-02.txt
web/www/horas/Polski/Martyrologium/07-03.txt
web/www/horas/Polski/Martyrologium/07-04.txt
web/www/horas/Polski/Martyrologium/07-05.txt
web/www/horas/Polski/Martyrologium/07-06.txt
web/www/horas/Polski/Martyrologium/07-07.txt
web/www/horas/Polski/Martyrologium/07-08.txt
web/www/horas/Polski/Martyrologium/07-14.txt
web/www/horas/Polski/Martyrologium/07-15.txt
web/www/horas/Polski/Martyrologium/07-16.txt
web/www/horas/Polski/Martyrologium/07-20.txt
web/www/horas/Polski/Martyrologium/07-26.txt
web/www/horas/Polski/Martyrologium/07-27.txt
web/www/horas/Polski/Martyrologium/07-29.txt
web/www/horas/Polski/Martyrologium/08-01.txt
web/www/horas/Polski/Sancti/07-02.txt
web/www/horas/Polski/SanctiM/06-24.txt
web/www/horas/Polski/SanctiM/07-02.txt
web/www/horas/Polski/Tempora/Pent02-5.txt
web/www/horas/Polski/TemporaM/Pent01-4.txt
web/www/horas/Polski/TemporaM/Pent02-5.txt

Polski more translations, corrections

---

web/cgi-bin/horas/Pofficium.pl
web/cgi-bin/horas/officium.pl

Reverts DivinumOfficium/divinum-officium#2952

Revert "Revert "Revert "code: consolidate officium & Pofficium"""

---

web/www/missa/English/Tempora/Pent05-0.txt
web/www/missa/English/Tempora/Pent05-0o.txt

Changed Epistle and Secret to be consistent with the St Joseph missal.

Punctuation and Consistency

---

web/www/horas/Latin/Sancti/07-22.txt

07-22 old hymn for vespera

---

web/www/horas/Latin/SanctiM/07-26.txt

MONASTIC 07-26 laudes responsory fix

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/horasjs.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/officium_html.pl

- add 'Tu autem' after matutinum reading in Monastic BMV Sabbato
- disable expand button when display skeleton for 'omittitur' sections also for vernaculars + code clean
- proper return from setup
+AMDG+

code update

---

web/www/horas/English/Ordinarium/CompletoriumOP.txt
web/www/horas/English/Ordinarium/PrimaM.txt
web/www/horas/English/Sancti/11-02.txt
web/www/horas/Francais/Sancti/11-02.txt
web/www/missa/English/Commune/C10.txt
web/www/missa/English/Commune/C10b.txt
web/www/missa/English/Commune/C10c.txt
web/www/missa/English/Commune/C10t.txt
web/www/missa/English/Commune/C11.txt
web/www/missa/English/Commune/C11p.txt
web/www/missa/English/Ordo/Suffragium.txt
web/www/missa/English/Sancti/09-24.txt
web/www/missa/English/Tempora/C10c.txt
web/www/missa/English/Tempora/C10t.txt

"Virgin" is uppercase in all instances of "ever Virgin" in two different Missals

Uppercase "Virgin"

---

web/www/missa/French/Ordo/Post.txt

Translation found in this missal: https://www.1604.ca/missels/Missel1937GLJSD.pdf
The page has been tested locally

Add French Post.txt

---

web/www/horas/Help/credits.html
web/www/horas/Polski/CommuneM/C10.txt
web/www/horas/Polski/Martyrologium/07-03.txt
web/www/horas/Polski/Martyrologium/07-20.txt
web/www/horas/Polski/Sancti/03-24.txt
web/www/horas/Polski/Sancti/09-12.txt
web/www/horas/Polski/SanctiM/08-15.txt
web/www/horas/Polski/SanctiM/09-08.txt
web/www/horas/Polski/Tempora/Pasc3-1.txt
web/www/horas/Polski/Tempora/Pasc3-2.txt
web/www/horas/Polski/Tempora/Quad5-5.txt
web/www/horas/Polski/TemporaM/Pent13-0.txt
web/www/horas/Polski/TemporaM/Pent14-0.txt
web/www/horas/Polski/TemporaM/Pent16-0.txt

Polski: Translation of St. Bernards sermones + update

---

web/www/horas/Latin/Ordinarium/Completorium.txt
web/www/horas/Latin/Ordinarium/CompletoriumM.txt

Completorium - fix Kyrie

---

web/cgi-bin/horas/webdia.pl

code: fix closing <TR> tag when using single language

---

web/www/horas/English/Sancti/05-03.txt
web/www/horas/English/Sancti/05-03t.txt

Add punctuation

---

web/cgi-bin/horas/webdia.pl

code: correct html anchor

---

web/cgi-bin/horas/specmatins.pl

code: fix 'never' use Invitatorium4 etc in non Latin

---

web/www/horas/Polski/Psalterium/Invitatorium.txt
web/www/horas/Polski/Psalterium/Invitatorium2.txt
web/www/horas/Polski/Psalterium/Invitatorium3.txt
web/www/horas/Polski/Psalterium/Invitatorium4.txt

Polski: update Invitatorium

---

web/cgi-bin/horas/specials.pl

code: prevent Oremus in commemoratio being expandable

---

web/cgi-bin/horas/horas.pl
web/www/horas/Dansk/Psalterium/Prayers.txt
web/www/horas/Deutsch/Psalterium/Prayers.txt
web/www/horas/Deutsch/Psalterium/Translate.txt
web/www/horas/English/Ordinarium/PrimaM.txt
web/www/horas/English/Psalterium/Prayers.txt
web/www/horas/English/Psalterium/Translate.txt
web/www/horas/Espanol/Ordinarium/PrimaM.txt
web/www/horas/Espanol/Psalterium/Prayers.txt
web/www/horas/Espanol/Psalterium/Translate.txt
web/www/horas/Francais/Psalterium/Prayers.txt
web/www/horas/Francais/Psalterium/Translate.txt
web/www/horas/Italiano/Ordinarium/PrimaM.txt
web/www/horas/Italiano/Psalterium/Prayers.txt
web/www/horas/Italiano/Psalterium/Translate.txt
web/www/horas/Latin/Ordinarium/PrimaM.txt
web/www/horas/Latin/Psalterium/Prayers.txt
web/www/horas/Latin/Psalterium/Translate.txt
web/www/horas/Latin/SanctiM/10-05.txt
web/www/horas/Magyar/Ordinarium/PrimaM.txt
web/www/horas/Magyar/Psalterium/Prayers.txt
web/www/horas/Magyar/Psalterium/Translate.txt
web/www/horas/Polski/Ordinarium/PrimaM.txt
web/www/horas/Polski/Psalterium/Prayers.txt
web/www/horas/Polski/Psalterium/Translate.txt

MONASTIC: make Divinum auxilium & MLitany expandable properly

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/popup.pl
web/cgi-bin/horas/specials.pl
web/www/horas/Deutsch/Psalterium/Translate.txt
web/www/horas/English/Psalterium/Translate.txt
web/www/horas/Espanol/Psalterium/Translate.txt
web/www/horas/Francais/Psalterium/Translate.txt
web/www/horas/Italiano/Psalterium/Translate.txt
web/www/horas/Latin/Psalterium/Translate.txt
web/www/horas/Magyar/Psalterium/Translate.txt
web/www/horas/Polski/Psalterium/Translate.txt

(also reverts 09521470e as obsolete)
+AMDG+

code: prevent single lines be expandable 

---

web/cgi-bin/horas/horas.pl
web/www/horas/Deutsch/Psalterium/Translate.txt
web/www/horas/English/Psalterium/Translate.txt
web/www/horas/Espanol/Psalterium/Translate.txt
web/www/horas/Francais/Psalterium/Translate.txt
web/www/horas/Italiano/Psalterium/Translate.txt
web/www/horas/Latin/Psalterium/Translate.txt
web/www/horas/Magyar/Psalterium/Translate.txt
web/www/horas/Polski/Psalterium/Translate.txt

update expands presentation

---

web/cgi-bin/horas/horas.pl
web/www/horas/Deutsch/psalms1/Psalm231.txt
web/www/horas/English/psalms1/Psalm231.txt
web/www/horas/Espanol/psalms1/Psalm231.txt
web/www/horas/Francais/psalms1/Psalm231.txt
web/www/horas/Italiano/psalms1/Psalm231.txt
web/www/horas/Latin/PiusXII/Psalm231.txt
web/www/horas/Latin/psalms1/Psalm231.txt
web/www/horas/Magyar/psalms1/Psalm231.txt

code: work around canticles

---

web/www/horas/Polski/Martyrologium/10-16.txt
web/www/horas/Polski/Martyrologium/10-17.txt
web/www/horas/Polski/Martyrologium/11-01.txt
web/www/horas/Polski/Martyrologium/11-12.txt
web/www/horas/Polski/Martyrologium/11-19.txt
web/www/horas/Polski/Martyrologium/11-27.txt
web/www/horas/Polski/Psalterium/Invitatorium.txt
web/www/horas/Polski/Psalterium/Invitatorium1.txt
web/www/horas/Polski/Psalterium/Invitatorium3.txt
web/www/horas/Polski/Psalterium/Invitatorium4.txt
web/www/horas/Polski/Tempora/101-1.txt
web/www/horas/Polski/Tempora/103-0.txt
web/www/horas/Polski/Tempora/Pent20-0.txt
web/www/horas/Polski/TemporaM/Pent20-0.txt
web/www/horas/Polski/psalms1/Psalm94.txt

Polski: update

---

web/cgi-bin/horas/webdia.pl

code: allow arbitrary text width in Options - useful for wide screens

---

docker/generator/Dockerfile
standalone/tools/epubgen2/EofficiumXhtml.pl

Fix link errors in generated files.

Epubgen fix horas titles

---

web/cgi-bin/horas/horas.pl
web/www/horas/English/Ordinarium/CompletoriumM.txt
web/www/horas/English/Sancti/10-DU.txt
web/www/horas/English/SanctiM/10-DU.txt
web/www/horas/Espanol/Ordinarium/CompletoriumM.txt
web/www/horas/Italiano/Ordinarium/CompletoriumM.txt
web/www/horas/Latin/Ordinarium/CompletoriumM.txt
web/www/horas/Latin/SanctiM/10-DU.txt
web/www/horas/Magyar/Ordinarium/CompletoriumM.txt
web/www/horas/Polski/Ordinarium/CompletoriumM.txt
web/www/horas/Polski/Sancti/10-DU.txt
web/www/horas/Polski/SanctiM/10-DU.txt
web/www/horas/Portugues/Ordinarium/CompletoriumM.txt

10-DU + MONASTIC update

---

web/cgi-bin/horas/monastic.pl

code: prevent second fragment in regula on 06-24 & 10-24 + code refactor

---

web/cgi-bin/horas/horas.pl

code: remove dots in Alleluia_ant

---

web/www/horas/Polski/SanctiM/11-13.txt
web/www/horas/Polski/SanctiM/11-17.txt

Polski: MONASTIC 11-1[37] translation courtesy adiutorium.pl

---

web/www/horas/Polski/Commune/C9.txt

The new one is more faithful to the original

[Polish, defunct.] Fix Responsory91 translation

---

web/www/horas/English/Martyrologium/10-30.txt
web/www/missa/English/Commune/C10.txt
web/www/missa/English/Commune/C10c.txt
web/www/missa/English/Commune/C10t.txt
web/www/missa/English/Tempora/C10c.txt
web/www/missa/English/Tempora/C10t.txt

Found some lower-cased "virgin" at beginning of lines after tildes.
Removed a "-" causing misformatting.

Typos and formatting

---

web/cgi-bin/horas/specials.pl

MONASTIC code: fix psalm counter in Laudes when using 'roman' office

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/specials.pl

* auto initials
* italic for mute vovels
+AMDG+

code: changes in hymns

---

web/www/horas/Latin/Psalterium/Major Special.txt
web/www/horas/Latin/Psalterium/Matutinum Special.txt
web/www/horas/Latin/Sancti/11-11.txt

11-11, Matutinum Special, Major Special - accents

---

web/cgi-bin/horas/specials.pl

code: fix #2176 - IC octave commemoration

---

web/www/horas/Latin/Commune/C6.txt
web/www/horas/Latin/CommuneM/C6.txt
web/www/horas/Latin/CommuneM/C6a.txt
web/www/horas/Latin/CommuneM/C6b.txt

Lectiones in 2-5 loco
Correction in HymnusM Matutinum

Monastic: CommuneM C6

---

web/cgi-bin/horas/specials.pl

code: fix #3068

---

web/www/horas/Latin/Commune/C6.txt
web/www/horas/Latin/Sancti/11-09.txt
web/www/horas/Latin/Sancti/11-22.txt
web/www/horas/Latin/psalms1/Psalm105.txt

C6 & other accents & typos

---

web/www/horas/Latin/Psalterium/Psalmi matutinum.txt
web/www/horas/Latin/SanctiM/11-30.txt

Psalmi matutinum & SanctiM/11-30 - accents

---

web/cgi-bin/horas/horascommon.pl

code: replace geteaster (was wrong in 1954 & 2049)

---

web/www/horas/Deutsch/Psalterium/Prayers.txt
web/www/horas/Deutsch/psalms1/Psalm118.txt
web/www/horas/Deutsch/psalms1/Psalm139.txt

Addressing Issue #3079

---

web/www/horas/Help/brevi.css
web/www/horas/Help/credits.html
web/www/horas/Help/download.html
web/www/horas/Help/help.html
web/www/horas/Help/rubrics.html
web/www/horas/Help/technical.html
web/www/horas/Help/times.html
web/www/horas/Help/versions.html

update download.html + other help files small corrections

---

web/cgi-bin/horas/kalendar.pl

calendar: change Sun,Mon... to Latin

---

web/cgi-bin/horas/specials.pl

fix Prima Responsory on BMV Saturday in old Epiphany octave 1960 rule

---

web/www/horas/English/CommuneM/C2.txt
web/www/horas/English/TemporaM/Epi1-0.txt
web/www/horas/Latin/CommuneM/C2.txt
web/www/horas/Latin/Sancti/01-06.txt
web/www/horas/Latin/SanctiM/12-26.txt
web/www/horas/Latin/Tempora/Epi1-0a.txt
web/www/horas/Latin/TemporaM/Adv4-0.txt
web/www/horas/Latin/TemporaM/Epi1-0.txt
web/www/horas/Polski/Martyrologium/01-11.txt
web/www/horas/Polski/Martyrologium/01-13.txt
web/www/horas/Polski/Martyrologium/01-31.txt
web/www/horas/Polski/Sancti/12-25.txt
web/www/horas/Polski/Sancti/12-28.txt
web/www/horas/Polski/Tempora/Adv4-5.txt
web/www/horas/Polski/Tempora/Epi1-0a.txt
web/www/horas/Polski/Tempora/Epi1-1.txt

- Polski: Christmas old vespera hymn translation courtesy adiutorium.pl
- Polski: update
- accents
- Monastic: update

Batch of updates

---

web/www/horas/Latin/TemporaM/Quadp3-3.txt

MONASTIC: Ash Wednesday 1st class

---

web/www/horas/Latin/psalms1/Psalm234.txt

Scanned book to easily double-check against:
https://archive.org/details/breviariumromanu18984cath/page/n70/mode/1up

Quicumque: fix typo

---

web/www/horas/Help/credits.html
web/www/horas/Polski/Tempora/Quad2-0.txt
web/www/horas/Polski/Tempora/Quad5-0.txt
web/www/horas/Polski/TemporaM/Quad2-0.txt
web/www/horas/Polski/TemporaM/Quad5-0.txt

Polski: readings translations

---

web/cgi-bin/horas/horascommon.pl

code: fix unstability in transfered, provided by empty transfers

---

web/cgi-bin/horas/kalendar.pl

calendar.pl fix praypray

---

web/cgi-bin/horas/horascommon.pl

code: fix false vesperas of BMV Sabbato

---

web/cgi-bin/missa/Emissa.pl

so that epubgen2.sh creates proper *-Missa.html files.

added proper HTML header tags

---

web/cgi-bin/DivinumOfficium/Directorium.pm
web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/specials.pl
web/www/horas/Latin/Tabulae/Kalendaria/1570.txt

- code: include transfered in Directorium and other improvments
- code: work around St. Mathias fest & vigil in leap years
+AMDG+

code changes around transfer by easter

---

web/www/missa/English/Tempora/Pasc0-5.txt
web/www/missa/English/Tempora/Pasc0-5t.txt
web/www/missa/English/Tempora/Pasc0-6.txt
web/www/missa/English/Tempora/Pasc0-6t.txt

Missing Words

---

web/cgi-bin/horas/dialogcommon.pl
web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/popup.pl
web/cgi-bin/horas/setup.pl
web/cgi-bin/horas/specials.pl
web/cgi-bin/horas/specmatins.pl
web/cgi-bin/missa/Cmissa.pl
web/cgi-bin/missa/Emissa.pl
web/cgi-bin/missa/missa.pl
web/cgi-bin/missa/mpopup.pl
web/cgi-bin/missa/ordo.pl
web/cgi-bin/missa/propers.pl

Reverts DivinumOfficium/divinum-officium#3202

Revert "code: improvement"

---

web/www/horas/Deutsch/Ordinarium/Completorium1960.txt
web/www/horas/Deutsch/Ordinarium/CompletoriumM.txt
web/www/horas/Deutsch/Psalterium/Benedictions.txt
web/www/horas/Deutsch/Psalterium/Doxologies.txt
web/www/horas/Deutsch/Psalterium/Prayers.txt
web/www/horas/Deutsch/Psalterium/Translate.txt
web/www/horas/Deutsch/psalms1/Psalm15.txt
web/www/horas/Deutsch/psalms1/Psalm16.txt
web/www/horas/Deutsch/psalms1/Psalm17.txt
web/www/horas/Deutsch/psalms1/Psalm18.txt
web/www/horas/Deutsch/psalms1/Psalm19.txt
web/www/horas/English/psalms1/Psalm15.txt
web/www/horas/Espanol/psalms1/Psalm15.txt
web/www/horas/Latin/psalms1/Psalm15.txt
web/www/horas/Magyar/psalms1/Psalm15.txt
web/www/horas/Polski-Newer/psalms1/Psalm15.txt
web/www/horas/Polski/psalms1/Psalm15.txt

plus a numbering correction on Ps15

More German

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/specials.pl

code: fix missing preces in paschaltide - function preces invert logic & refactor

---

web/cgi-bin/horas/specials.pl

code: fix #3206

---

web/cgi-bin/horas/kalendar.pl

code: kalendar.pl - modify header, arbitrary year navigation

---

web/cgi-bin/DivinumOfficium/Date.pm
web/cgi-bin/horas/kalendar.pl

Enabling the display of the whole year as an additional option for kalendar.pl

Kalendar: Ordo Totum Annum

---

web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/missa/Cmissa.pl
web/cgi-bin/missa/Emissa.pl
web/cgi-bin/missa/missa.pl

code: exclude setting hashes with text for second column to new function setsecondcol - speedup kalendar generation    + other code improvements

---

web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/officium_html.pl

code: another fix dark mode

---

web/cgi-bin/horas/webdia.pl

fix dark mode style

---

web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/webdia.pl

- ordo in ical format (requested #1329)
- days in Christmastide in Tempora column
- code clean
+ remove http redirection from webdia
+AMDG+

code: kalendar update

---

web/cgi-bin/horas/specmatins.pl
web/www/horas/Latin/Tempora/Pasc0-1.txt
web/www/missa/Latin/Tempora/Pasc7-0.txt

- code: Matutinum readings comments in parrenthesis - allow numbers only
- minor fixes
+AMDG+

code + minor update

---

web/cgi-bin/horas/horascommon.pl
web/www/horas/Latin/Tempora/Pent01-5.txt
web/www/horas/Latin/Tempora/Pent01-6.txt
web/www/horas/Latin/Tempora/Pent01-6o.txt
web/www/horas/Latin/Tempora/Pent02-1.txt
web/www/horas/Latin/Tempora/Pent02-2.txt
web/www/horas/Latin/Tempora/Pent02-3.txt

set days in octave CC as semiduplex & fix #3269

---

web/cgi-bin/horas/monastic.pl

code: fix responsory in Monastic 1st Nocturn reading of III class

---

web/www/horas/Help/Rubrics/Monastic rubrics.html

Update monastic rubrics according to the 1962 code of rubrics.

Update Monastic rubrics.html

---

web/www/horas/English/SanctiM/07-11.txt
web/www/horas/Latin/Psalterium/Psalmi major.txt
web/www/horas/Latin/SanctiM/07-26.txt

Typos, fixes

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/officium_html.pl
web/www/horas/horas.dialog
web/www/horas/horas.setup

code: fix versions problems when switching compare/calendars

---

web/www/horas/Latin/Tabulae/Transfer/425.txt

update transfers in 425

---

web/www/horas/Help/technical.html

technical.html: a bit update of information about Tabulae directory

---

web/cgi-bin/horas/horascommon.pl
web/www/horas/Deutsch/Sancti/09-08.txt
web/www/horas/English/Sancti/09-08.txt
web/www/horas/Espanol/Sancti/09-08.txt
web/www/horas/Francais/Sancti/09-08.txt
web/www/horas/Italiano/Sancti/09-08.txt
web/www/horas/Latin/Sancti/08-25.txt
web/www/horas/Latin/Sancti/09-08.txt
web/www/horas/Polski/Sancti/09-08.txt

fix #3347 & #3348

---

web/www/horas/Latin/Commune/C12.txt
web/www/horas/Latin/CommuneM/C12.txt

C12 fix hymn in 1570 & monastic

---

web/cgi-bin/DivinumOfficium/Main.pm
web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/officium_html.pl
web/cgi-bin/horas/webdia.pl
web/cgi-bin/missa/Cmissa.pl
web/cgi-bin/missa/Emissa.pl
web/cgi-bin/missa/missa.pl
web/www/horas/Latin/Sancti/07-02.txt
web/www/horas/Latin/Sancti/07-16sab.txt
web/www/horas/Latin/Sancti/08-05.txt
web/www/horas/Latin/Sancti/09-sab-oct.txt
web/www/horas/Latin/SanctiM/07-02.txt
web/www/horas/Latin/SanctiM/08-15.txt

- code: add color to subheader - (commemtoratio etc.)
- code + data: update liturgical_color for feast of BMV + regexp
- code: update kalendar.pl
- code: update scriptura comments
+AMDG+

add color to subheader and other code updates

---

web/www/horas/Latin/Sancti/07-03t.txt
web/www/horas/Latin/Sancti/07-04.txt
web/www/horas/Latin/Sancti/07-05o.txt
web/www/horas/Latin/Sancti/07-06.txt
web/www/horas/Latin/Sancti/08-16o.txt
web/www/horas/Latin/Sancti/08-18.txt
web/www/horas/Latin/Sancti/08-19a.txt
web/www/horas/Latin/Sancti/08-19t.txt
web/www/horas/Latin/Sancti/08-21o.txt
web/www/horas/Latin/Sancti/08-22a.txt
web/www/horas/Latin/Sancti/08-22t.txt

adding "Apostolorum" and unabbreviated "BMV" such that the days are marked in red and blue, respectively.

Liturgical Colours in Octaves

---

web/www/horas/Latin/Commune/C1.txt
web/www/horas/Latin/Sancti/08-15t.txt
web/www/horas/Latin/Sancti/08-24.txt
web/www/horas/Latin/SanctiM/09-14.txt

remove superflous words & other small changes

---

web/cgi-bin/horas/specials.pl

1955: ferial psalms in minor hours for II class feasts

---

web/cgi-bin/horas/officium.pl

code: fix second column of Vespers in Omnes/Plures

---

web/cgi-bin/horas/horascommon.pl

code: fix false scriptura info monastic

---

web/www/horas/horas.dialog

fix ignoring 'text width percentage'

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/specials.pl
web/cgi-bin/horas/specmatins.pl

code: clean version conditions for 196?

---

web/www/horas/Latin/Tabulae/data.txt

data.txt clean junks

---

web/www/horas/English/TemporaM/111-0.txt
web/www/horas/English/TemporaM/113-0.txt
web/www/horas/Espanol/Commune/C9.txt
web/www/horas/Italiano/Commune/C9.txt
web/www/horas/Latin/Commune/C9.txt
web/www/horas/Latin/SanctiM/11-13.txt
web/www/horas/Latin/SanctiM/12-25.txt
web/www/horas/Latin/TemporaM/113-0.txt
web/www/horas/Polski/Commune/C9.txt

small fixes mostly in Monastic

---

web/cgi-bin/horas/kalendar.pl

kalendar.pl - allow download iCal for arbitrary year

---

web/www/missa/Espanol/Ordo/Prayers.txt

Added spanish version of [IteMissa] for spanish based on Misal Diario y Vesperal 1962 by Gaspar Lefebvre https://archive.org/details/misal-diario-y-vesperal-1962

Added spanish version of [IteMissa]

---

web/www/missa/Espanol/Ordo/Prayers.txt

Added spanish translation of [Laus tibi] according to https://archive.org/details/misal-diario-y-vesperal-1962

Added spanish translation of [Laus tibi]

---

web/www/missa/Espanol/Ordo/Prefationes.txt

Translation from 1962 spanish missal https://archive.org/details/misal-diario-y-vesperal-1962

add spanish translation to [C-common1962]

---

web/www/missa/Espanol/Ordo/Ordo.txt

finished a sentence in spanish that were incomplete.

fix prayer incomplete in Spanish

---

web/www/missa/Espanol/Sancti/11-22.txt

Added 11-22 for Spanish based on:
https://archive.org/details/misal-diario-y-vesperal-1962

Create 11-22.txt for Spanish

---

web/cgi-bin/horas/horascommon.pl

code: fix warning 'Use of uninitialized value' in transfered

---

web/cgi-bin/horas/horascommon.pl
web/www/horas/Latin/Sancti/12-24s.txt

fixing Saturday Dec 23 Vespers and Commemorations on 24 (before R. I. 1960)

Christmas Eve on Sunday 

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/specials.pl
web/www/horas/Latin/Tempora/Pasc7-6.txt
web/www/horas/Latin/Tempora/Pasc7-6t.txt
web/www/horas/Latin/Tempora/Pent01-0r.txt

Replacing names in Commemorations in the Vernacular #3453

Follow up to #3454

---

web/www/horas/Latin/Martyrologium/10-01.txt
web/www/horas/Latin/Martyrologium/10-02.txt
web/www/horas/Latin/Martyrologium/10-03.txt
web/www/horas/Latin/Martyrologium/10-09.txt
web/www/horas/Latin/Martyrologium/10-15.txt
web/www/horas/Latin/Psalterium/Major Special.txt

- Add some missing accents to Martyrology
- Fix typo (missing accent)
- Add 2 more pre-Urban hymn differences

Fix typos/omissions

---

web/cgi-bin/horas/horascommon.pl

close #3486 by re-introducing Dominical commemoreations on I. cl. feasts at Lauds and both Vespers

Close #3486

---

web/www/horas/Latin/CommuneM/C6.txt
web/www/horas/Latin/CommuneM/C7.txt

Monastic: fix matutinum readings in C6 & C7

---

web/www/horas/English/Ordinarium/CompletoriumOP.txt
web/www/horas/English/Sancti/03-24.txt
web/www/horas/English/Sancti/03-25.txt
web/www/missa/English/Tempora/Pasc0-0.txt

English: clean texts

---

web/www/horas/Latin/Tabulae/Transfer/e.txt
web/www/horas/Latin/Tabulae/Transfer/f.txt
web/www/missa/Cesky/Sancti/01-11.txt
web/www/missa/Cesky/Sancti/01-11cc.txt
web/www/missa/Cesky/Tempora/Epi1-0.txt
web/www/missa/English/Sancti/01-11.txt
web/www/missa/English/Sancti/01-11cc.txt
web/www/missa/English/Tempora/Epi1-0.txt
web/www/missa/Espanol/Sancti/01-06.txt
web/www/missa/Espanol/Tempora/Epi1-0.txt
web/www/missa/French/Sancti/01-11.txt
web/www/missa/French/Sancti/01-11cc.txt
web/www/missa/French/Tempora/Epi1-0.txt
web/www/missa/Italiano/Sancti/01-11.txt
web/www/missa/Italiano/Sancti/01-11cc.txt
web/www/missa/Italiano/Tempora/Epi1-0.txt
web/www/missa/Latin/Tempora/Epi1-0.txt
web/www/missa/Latin/Tempora/Epi1-0a.txt
web/www/missa/Polski/Tempora/Epi1-0.txt
web/www/missa/Portugues/Tempora/Epi1-0.txt

Sunday in the Epiphany Octave

---

web/cgi-bin/horas/monastic.pl
web/www/horas/Latin/SanctiM/12-24.txt

MONASTIC: fix Vigil of Nat. Matutinum

---

web/cgi-bin/horas/specials.pl

MONASTIC: fix Ant for Canticle in Laudes of Sat. Dec 17-23

---

web/cgi-bin/horas/dialogcommon.pl
web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/horasjs.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/webdia.pl
web/www/horas/English/Psalterium/Prayers.txt
web/www/horas/English/Psalterium/Translate.txt
web/www/horas/Latin/Appendix/Benedictio mensae.txt
web/www/horas/Latin/Appendix/Index.txt
web/www/horas/Latin/Appendix/Itinerarium.txt
web/www/horas/Latin/Appendix/Litaniae.txt
web/www/horas/Latin/Appendix/Ordo Commendationis Animae.txt
web/www/horas/Latin/Appendix/Psalmi graduales.txt
web/www/horas/Latin/Appendix/Septem psalmi paenitentiales.txt
web/www/horas/Latin/Psalterium/Prayers.txt
web/www/horas/Latin/Psalterium/Translate.txt
web/www/horas/Polski/Psalterium/Prayers.txt
web/www/horas/Polski/Psalterium/Translate.txt

Add Appendix (latin only)

---

web/www/horas/Latin/Psalterium/Matutinum Special.txt
web/www/horas/Latin/SanctiM/12-24s.txt
web/www/horas/Latin/SanctiM/12-29.txt
web/www/horas/Latin/SanctiM/12-31.txt
web/www/horas/Latin/TemporaM/Nat1-0.txt
web/www/horas/Latin/TemporaM/Nat30.txt

MONASTIC: fixes in Nativitytide

---

web/cgi-bin/horas/appendix.pl

add missing appendix.pl

---

web/www/horas/Latin/Tabulae/data.txt

fix probelms with missa in DA

---

web/cgi-bin/horas/specials.pl

DA rubrics: Commemorated Sunday of Epiphany

---

web/www/horas/Latin/Sancti/01-01.txt
web/www/horas/Latin/Sancti/01-02.txt
web/www/horas/Latin/Sancti/01-03.txt
web/www/horas/Latin/Sancti/01-04.txt
web/www/horas/Latin/Sancti/01-05.txt
web/www/horas/Latin/Sancti/01-07.txt
web/www/horas/Latin/Sancti/01-08.txt
web/www/horas/Latin/Sancti/01-09.txt
web/www/horas/Latin/Sancti/01-10.txt
web/www/horas/Latin/Sancti/01-11.txt
web/www/horas/Latin/Sancti/01-12.txt
web/www/horas/Latin/Sancti/01-13.txt
web/www/horas/Latin/SanctiM/01-02.txt
web/www/horas/Latin/SanctiM/01-04.txt
web/www/horas/Latin/SanctiM/01-07.txt
web/www/horas/Latin/SanctiM/01-08.txt
web/www/horas/Latin/SanctiM/01-09.txt
web/www/horas/Latin/SanctiM/01-10.txt
web/www/horas/Latin/SanctiM/01-11.txt
web/www/horas/Latin/SanctiM/01-12.txt
web/www/horas/Latin/SanctiM/01-13.txt

fix #3580 + clean Monastic files 01-02 - 01-13

---

web/cgi-bin/horas/horascommon.pl
web/www/horas/Latin/Sancti/01-12.txt

- fix second part of #3580 - vespera 01-12
- clean regexps which provided warning (bad argument)
+AMDG+

small fixes

---

web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/English/Psalterium/Translate.txt
web/www/horas/Latin/Psalterium/Translate.txt
web/www/horas/Polski/Psalterium/Translate.txt

code: refactor around psalms & anthiponas Matutinum 
- new function nocturn 
- also fix absolution in Monastic ferias and others
+AMDG+

code refactor

---

web/cgi-bin/horas/specials.pl

code: fix missing antiphonas in Monastic major horas

---

web/www/horas/English/SanctiM/01-25.txt
web/www/horas/Latin/SanctiM/01-25.txt

MONASTIC: 01-25 pre 1960 version

---

web/www/horas/Latin/Sancti/05-11r.txt

fix rank in 05-11r

---

web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/kalendar.pl
web/www/horas/horas.dialog

- ignore votive in kalendar
+AMDG+

votives from Commune

---

web/cgi-bin/horas/specmatins.pl

C12 no Te Deum in Septuagesimae == always respect 'no Te Deum' rule

---

web/cgi-bin/horas/specials.pl

Close issue #3645

---

.gitignore
web/cgi-bin/horas/horas.pl
web/www/horas/English/Martyrologium/02-29.txt
web/www/horas/Latin/Martyrologium/02-23.txt
web/www/horas/Latin/Martyrologium/02-24.txt
web/www/horas/Latin/Martyrologium/02-29.txt
web/www/horas/Latin/Martyrologium1570/02-23.txt
web/www/horas/Latin/Martyrologium1570/02-24.txt
web/www/horas/Latin/Martyrologium1570/02-29.txt
web/www/horas/Latin/Martyrologium1955R/02-23.txt
web/www/horas/Latin/Martyrologium1955R/02-24.txt
web/www/horas/Latin/Martyrologium1955R/02-29.txt
web/www/horas/Latin/Martyrologium1960/02-23.txt
web/www/horas/Latin/Martyrologium1960/02-24.txt
web/www/horas/Latin/Martyrologium1960/02-29.txt

Showing Martyrology "/:rubrics:/" as "rubrics".
Correcting Luna and English names of the days at the end of February.
(Re-) Closing [#3641](https://github.com/DivinumOfficium/divinum-officium/issues/3641)

Martyrology in Leap Years

---

web/www/horas/English/Tempora/Quad3-0.txt
web/www/horas/Espanol/Tempora/Quad3-0.txt
web/www/horas/Latin/Tempora/Quad3-0.txt
web/www/horas/Polski/Tempora/Quad3-0.txt

Quad3-0 fix 3rd Laudes antiphon in Monastic + clean Trident version

---

web/cgi-bin/horas/specmatins.pl

potentially close #3659 
@APMarcello3 @fiapps  Since I am not familar with the 1960 rubrics and the rules for matins/benedictions in particular, please scrutinise if the change causes any other issues

Benedictions for 1960 Feasts during Lent

---

web/www/horas/Latin/Commune/C5a.txt
web/www/horas/Latin/Ordinarium/Prima.txt
web/www/horas/Latin/Ordinarium/Prima1960.txt
web/www/horas/Latin/Sancti/03-07.txt

Using translatable variable for Silent Pater
Fixing Responsories in Commune C5a rather than for Thomas Aquinas only

Addition to #3667 and #3666

---

web/www/horas/Latin/Ordinarium/Prima.txt

fix Adjutorium nostrum in Prima

---

web/cgi-bin/horas/specmatins.pl

fix Monday Invitatorium in Quadragesima

---

web/cgi-bin/horas/specmatins.pl

follow up to 7a51411d16c0043138743550ebd13ef49648c7bf and its revert in 0008d01628f71dc2538b4132eb935e8cd7441d07

Trid & Monastic: Fix Monday Invit in Quad

---

web/www/horas/Latin/SanctiM/03-12.txt

MONASTIC: update 03-12

---

web/www/missa/Espanol/Ordo/Prayers.txt

The asperges me, and vita aquam were in english instead of spanish. This texts were changed for their proper translation in spanish.

Fixed Asperges me and Vidi aquam that were in english.

---

web/www/missa/Espanol/Ordo/Ordo.txt

Rubrics of incesatio added and little change in translation of the incipit.

New rubrics and translation improvment

---

web/www/missa/Espanol/Ordo/Ordo.txt

This part of the mass was in english for the spanish translation. The proper translation was added with its rubrics.

Incensation translation fixed.

---

web/www/missa/Espanol/Ordo/Ordo.txt

Some comments an rubrics were added plus a part of the canon was in english and was changed to spanish.

Translation to spanish fixed

---

web/www/missa/Espanol/Ordo/Communio.txt

There was not a Spanish Communio file, so it used to show it in English instead.

Communio file added for spanish missae

---

web/www/horas/Italiano/Psalterium/Prayers.txt

I was also working on an update of the Italian Prayers.txt, which I present here:
- Make the translation of silent Pater and silent Credo read more naturally.
- Use the subjunctive in `[Dominus det]`
- Supply translations for Monastic sections (I didn't do the OP ones because the Latin still has errors).
- Eliminate trailing spaces.

Improve and complete translation of Italian Prayers.txt

---

web/cgi-bin/horas/specmatins.pl

fix antophonas in eastertide when it contains semicolon

---

web/cgi-bin/horas/specials.pl

code: remove space after last psalm in minor hours

---

web/cgi-bin/horas/specials.pl

code: fix "N." in votive officium

---

web/cgi-bin/horas/horascommon.pl

exclude commemoration at Vespers

Secunda Rogationibus (ad Laudes tantum)

---

web/cgi-bin/horas/horas.pl
web/www/horas/English/Ordinarium/CompletoriumOP.txt
web/www/horas/English/Psalterium/Mariaant.txt
web/www/horas/English/Psalterium/Prayers.txt
web/www/horas/Latin/Ordinarium/CompletoriumOP.txt
web/www/horas/Latin/Psalterium/Mariaant.txt
web/www/horas/Latin/Psalterium/Prayers.txt
web/www/horas/Polski/Psalterium/Prayers.txt
web/www/horas/Portugues/Ordinarium/CompletoriumOP.txt

use &antiphona_finalis in CompletoriumOP

---

web/www/horas/English/Sancti/01-19.txt
web/www/horas/English/Sancti/01-19o.txt
web/www/horas/English/Sancti/07-21.txt
web/www/horas/English/Sancti/10-07a.txt
web/www/missa/English/Ordo/Suffragium.txt
web/www/missa/English/Sancti/04-14.txt
web/www/missa/English/Sancti/04-24.txt
web/www/missa/English/Sancti/05-06.txt

Misspelled word

---

web/www/horas/Latin/Sancti/05-22n.txt

The oratio is from the Missæ pro alicuibus locis in the appendix of the 1962 editio typica of the Missale Romanum.

St. Rita office (Cum sanctissima): correct common and add oratio.

---

web/cgi-bin/missa/propers.pl
web/www/missa/Latin/Sancti/01-21.txt
web/www/missa/Latin/Sancti/03-10.txt
web/www/missa/Latin/Sancti/03-27.txt
web/www/missa/Latin/Sancti/04-14.txt
web/www/missa/Latin/Sancti/04-28.txt
web/www/missa/Latin/Sancti/05-12.txt
web/www/missa/Latin/Sancti/05-26.txt
web/www/missa/Latin/Sancti/06-02.txt
web/www/missa/Latin/Sancti/06-04.txt
web/www/missa/Latin/Sancti/06-05.txt
web/www/missa/Latin/Sancti/06-09.txt
web/www/missa/Latin/Sancti/06-14.txt
web/www/missa/Latin/Sancti/06-15.txt
web/www/missa/Latin/Sancti/06-30.txt
web/www/missa/Latin/Sancti/07-07.txt
web/www/missa/Latin/Sancti/07-14.txt
web/www/missa/Latin/Sancti/07-28.txt
web/www/missa/Latin/Sancti/08-04.txt
web/www/missa/Latin/Sancti/08-25.txt
web/www/missa/Latin/Sancti/10-20.txt
web/www/missa/Latin/Sancti/11-17.txt
web/www/missa/Latin/Tempora/Pasc5-5.txt
web/www/missa/Latin/Tempora/Pasc5-6.txt
web/www/missa/Latin/Tempora/Pasc5-6t.txt
web/www/missa/Latin/Tempora/Pasc6-0.txt
web/www/missa/Latin/Tempora/Pasc6-1.txt
web/www/missa/Latin/Tempora/Pasc6-2.txt
web/www/missa/Latin/Tempora/Pasc6-2t.txt
web/www/missa/Latin/Tempora/Pasc6-3.txt

'Evangelium non appropriatum' could be added to [Rule] when needed
+AMDG+

fix #3712 only for 2024

---

web/www/horas/Italiano/Psalterium/Minor Special.txt
web/www/horas/Latin/Commune/C7a.txt
web/www/horas/Latin/Ordinarium/PrimaM.txt

These are other errors I found in testing today.

"Deo gratias" errors and erroneous title

---

web/www/horas/Dansk/Psalterium/Prayers.txt
web/www/horas/Deutsch/Psalterium/Prayers.txt
web/www/horas/English/Psalterium/Prayers.txt
web/www/horas/Espanol/Psalterium/Prayers.txt
web/www/horas/Francais/Psalterium/Prayers.txt
web/www/horas/Italiano/Psalterium/Prayers.txt
web/www/horas/Latin/Psalterium/Prayers.txt
web/www/horas/Magyar/Psalterium/Prayers.txt
web/www/horas/Polski/Psalterium/Prayers.txt
web/www/horas/Portugues/Psalterium/Prayers.txt

te Deum unificate rubrics

---

web/cgi-bin/horas/webdia.pl

code: do not print empty font tags

---

web/cgi-bin/missa/propers.pl

fix translation of Gloria in Asperges/Vidi aquam

---

web/cgi-bin/horas/specials.pl

- Revert "Resp Prime if 05-31 is Pasc 5-5"
- Revert "Prime responsory Pasc5-5 1960 rubrics"
- fix & clean get_prima_responsory
+AMDG+

code: fix & clean get_prima_responsory

---

web/cgi-bin/horas/specials.pl

code: fix versum

---

web/cgi-bin/DivinumOfficium/LanguageTextTools.pm

fix default translation for Latin-Bea - was English not Latin

---

web/www/horas/Latin/Ordinarium/Completorium.txt
web/www/horas/Latin/Ordinarium/PrimaOP.txt
web/www/horas/Latin/Psalterium/Prayers.txt
web/www/horas/Latin/Psalterium/Translate.txt

revert 78eca80 + restore Confiteor & Ant. fianlis in OP Completorium

---

web/cgi-bin/DivinumOfficium/LanguageTextTools.pm

remove left debug error

---

web/cgi-bin/horas/specials.pl
web/www/horas/Deutsch/Commune/C10.txt
web/www/horas/English/Commune/C10.txt
web/www/horas/Espanol/Commune/C10.txt
web/www/horas/Francais/Commune/C10.txt
web/www/horas/Italiano/Commune/C10.txt
web/www/horas/Latin/Commune/C10.txt
web/www/horas/Magyar/Commune/C10.txt
web/www/horas/Polski/Commune/C10.txt

closes #3760

---

web/cgi-bin/horas/horascommon.pl
web/www/horas/Latin/Tempora/Pasc5-5.txt
web/www/horas/Latin/Tempora/Pasc5-6.txt
web/www/horas/Latin/Tempora/Pasc6-0.txt
web/www/horas/Latin/Tempora/Pasc6-1.txt
web/www/horas/Latin/Tempora/Pasc6-2.txt
web/www/horas/Latin/Tempora/Pasc6-3.txt
web/www/horas/Latin/Tempora/Pent01-5.txt
web/www/horas/Latin/Tempora/Pent01-6.txt
web/www/horas/Latin/Tempora/Pent02-0r.txt
web/www/horas/Latin/Tempora/Pent02-1.txt
web/www/horas/Latin/Tempora/Pent02-2.txt
web/www/horas/Latin/Tempora/Pent02-3.txt
web/www/horas/Latin/Tempora/Pent02-4.txt

Reverts DivinumOfficium/divinum-officium#3764

Revert "Reduced 1955: cosmetics for "neglected" rubrics"

---

web/cgi-bin/horas/horascommon.pl
web/www/horas/Latin/Tempora/Pasc5-5.txt
web/www/horas/Latin/Tempora/Pasc5-6.txt
web/www/horas/Latin/Tempora/Pasc6-0.txt
web/www/horas/Latin/Tempora/Pasc6-1.txt
web/www/horas/Latin/Tempora/Pasc6-2.txt
web/www/horas/Latin/Tempora/Pasc6-3.txt
web/www/horas/Latin/Tempora/Pent01-5.txt
web/www/horas/Latin/Tempora/Pent01-6.txt
web/www/horas/Latin/Tempora/Pent02-0r.txt
web/www/horas/Latin/Tempora/Pent02-1.txt
web/www/horas/Latin/Tempora/Pent02-2.txt
web/www/horas/Latin/Tempora/Pent02-3.txt
web/www/horas/Latin/Tempora/Pent02-4.txt

Reverts DivinumOfficium/divinum-officium#3765

Revert "Revert "Reduced 1955: cosmetics for "neglected" rubrics""

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/monastic.pl

1. Restore functionality of Building Script
2. Monastic: Conditions for Scripture of 3 Lectiones vs. Lectio brevis

Functionality & Monastic

---

web/cgi-bin/horas/monastic.pl

small correction to c14eb899ff87d0256b8aa81d8c08617cc861b182

MONASTIC 1963: Lectio brevis rogation Monday

---

web/www/horas/Dansk/Psalterium/Prayers.txt
web/www/horas/Dansk/Psalterium/Translate.txt
web/www/horas/Deutsch/Psalterium/Prayers.txt
web/www/horas/Deutsch/Psalterium/Translate.txt
web/www/horas/English/Psalterium/Prayers.txt
web/www/horas/English/Psalterium/Translate.txt
web/www/horas/Espanol/Psalterium/Prayers.txt
web/www/horas/Espanol/Psalterium/Translate.txt
web/www/horas/Francais/Psalterium/Prayers.txt
web/www/horas/Francais/Psalterium/Translate.txt
web/www/horas/Italiano/Psalterium/Prayers.txt
web/www/horas/Italiano/Psalterium/Translate.txt
web/www/horas/Latin/Psalterium/Prayers.txt
web/www/horas/Latin/Psalterium/Translate.txt
web/www/horas/Magyar/Psalterium/Translate.txt
web/www/horas/Polski/Psalterium/Prayers.txt
web/www/horas/Polski/Psalterium/Translate.txt
web/www/horas/Portugues/Psalterium/Translate.txt

- Translate: Adjutorium nostrum & Pater secreto
- Prayers: Pater secreto + remove MLitany2 from vernaculars
+AMDG+

Translate & Prayers update

---

web/www/horas/Deutsch/Commune/C1p.txt
web/www/horas/English/Commune/C1p.txt
web/www/horas/Italiano/Commune/C1p.txt
web/www/horas/Latin/Commune/C1p.txt

C1p - allow doxology change in HymnusM Vespera, remove duplicate HymnusM Laudes

---

web/www/horas/Dansk/Psalterium/Prayers.txt
web/www/horas/Deutsch/Psalterium/Prayers.txt
web/www/horas/English/Psalterium/Prayers.txt
web/www/horas/Espanol/Psalterium/Prayers.txt
web/www/horas/Francais/Psalterium/Prayers.txt
web/www/horas/Italiano/Psalterium/Prayers.txt
web/www/horas/Latin/Psalterium/Prayers.txt
web/www/horas/Magyar/Psalterium/Prayers.txt
web/www/horas/Polski/Psalterium/Prayers.txt
web/www/horas/Portugues/Psalterium/Prayers.txt

Keeping consistency and conciseness of output across all vernaculars

Consistency in Prayers.txt and solving #3781

---

web/cgi-bin/horas/horascommon.pl

Close #3786

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/specials.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/Dansk/Psalterium/Prayers.txt
web/www/horas/Deutsch/Psalterium/Prayers.txt
web/www/horas/English/Psalterium/Prayers.txt
web/www/horas/Espanol/Psalterium/Prayers.txt
web/www/horas/Francais/Psalterium/Prayers.txt
web/www/horas/Italiano/Psalterium/Prayers.txt
web/www/horas/Latin/Ordinarium/Laudes.txt
web/www/horas/Latin/Psalterium/Prayers.txt
web/www/horas/Polski/Psalterium/Prayers.txt

simplifies `Laudes.txt` and restores (accidentally destroyed) functionality of `Ave only`rule for Officium parvum BMV

Pater totum secreto & Ave only (Officium Parvum)

---

web/www/horas/English/psalms/Psalm118.txt
web/www/horas/English/psalms1/Psalm118.txt

Reverts DivinumOfficium/divinum-officium#3794

Revert "Typos"

---

web/cgi-bin/horas/horascommon.pl

fix comment for Laudes in Pentecost ember days

---

standalone/tools/epubgen2/EofficiumXhtml.pl
standalone/tools/epubgen2/Ewebdia.pl
web/cgi-bin/missa/Emissa.pl

closes #3796

---

web/www/horas/Dansk/Psalterium/Prayers.txt
web/www/horas/English/Psalterium/Prayers.txt
web/www/horas/Espanol/Psalterium/Prayers.txt
web/www/horas/Francais/Psalterium/Prayers.txt
web/www/horas/Italiano/Psalterium/Prayers.txt
web/www/horas/Latin/Psalterium/Prayers.txt
web/www/horas/Magyar/Psalterium/Prayers.txt
web/www/horas/Polski/Psalterium/Prayers.txt
web/www/horas/Portugues/Psalterium/Prayers.txt

Rubrics at the end of Compline

---

web/cgi-bin/horas/specials.pl

dirty fix reptitive comment to psalms in Completorium when using Plures/Omnes

---

web/cgi-bin/missa/propers.pl
web/www/missa/Latin/Ordo/Propers.txt

closes #3806

---

web/www/missa/missa.setup

fix missa.pl initial landing

---

web/cgi-bin/horas/horasjs.pl
web/cgi-bin/horas/webdia.pl
web/cgi-bin/missa/missa.pl

- missa.pl landing page to main
- avoid false cookie warning
+AMDG+

missa code update

---

web/www/missa/Espanol/Commune/C10.txt
web/www/missa/Espanol/Commune/C11.txt
web/www/missa/Espanol/Ordo/Ante.txt
web/www/missa/Espanol/Ordo/Prefationes.txt
web/www/missa/Espanol/Sancti/09-08.txt

Added spanish translation for the mass

adding spanish translation to the missa

---

web/www/horas/Latin/SanctiM/05-03.txt
web/www/horas/Latin/SanctiM/11-17.txt
web/www/horas/Latin/SanctiM/12-07.txt
web/www/horas/Latin/SanctiM/12-13.txt
web/www/horas/Latin/TemporaM/Pasc2-3.txt
web/www/horas/Ordinarium/Minor.txt

MONASTIC: updates

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/specmatins.pl
web/cgi-bin/horas/webdia.pl
web/www/horas/Latin/Psalterium/Prayers.txt

- script is meant for Monastic 1617/1930 versions
- code improvements are

Code improvements and &Mlitany2 script

---

web/cgi-bin/horas/horascommon.pl

whenever referenced by monastic versions

Ensure Monastic folder for Pseudo-Commune

---

web/www/missa/English/Commune/C5.txt
web/www/missa/French/Commune/C5.txt
web/www/missa/Portugues/Commune/C5.txt

found in the commemoration of S. Eusebius vs. C5 while cleaning up the Vigils
@APMarcello3

Diverging Vernaculars (Secreta/Postcommunio)

---

web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/Latin/Sancti/06-11.txt
web/www/horas/Latin/SanctiM/06-11.txt
web/www/horas/Latin/Tempora/Pasc5-3.txt
web/www/horas/Latin/TemporaM/Nat30.txt
web/www/horas/Latin/TemporaM/Nat31.txt
web/www/horas/Latin/TemporaM/Pasc5-3.txt

MONASTIC 1963: fixes in Matutinum + 06-11 major hours

---

web/www/horas/Latin/CommuneM/C2.txt
web/www/horas/Latin/CommuneM/C3.txt

Whitespace

---

web/cgi-bin/horas/horascommon.pl
web/www/Tabulae/Transfer/420.txt

re-fix #3858

---

web/www/missa/English/Commune/C10c.txt
web/www/missa/English/Commune/C10t.txt
web/www/missa/English/Commune/C11.txt
web/www/missa/English/Commune/C11p.txt
web/www/missa/English/Sancti/07-16.txt
web/www/missa/English/Sancti/08-14.txt
web/www/missa/Espanol/Commune/C10c.txt
web/www/missa/Espanol/Commune/C11.txt
web/www/missa/Espanol/Commune/C11p.txt
web/www/missa/Espanol/Sancti/07-16.txt
web/www/missa/Espanol/Sancti/08-14.txt
web/www/missa/Latin/Commune/C10c.txt
web/www/missa/Latin/Commune/C10t.txt
web/www/missa/Latin/Commune/C11.txt
web/www/missa/Latin/Commune/C11p.txt
web/www/missa/Latin/Sancti/07-16.txt
web/www/missa/Latin/Sancti/08-14.txt

using inheritance references for latin, english, spanish Evangelium section in files:
/missa/ 
* c10c
* c10t
* c11
* 07-16 
* 08-14

using inheritance references for latin, english, spanish Luc 11:27-28

---

web/www/missa/Espanol/Commune/Propaganda.txt
web/www/missa/Latin/Commune/Propaganda.txt
web/www/missa/Latin/Sancti/05-24pl.txt
web/www/missa/Latin/Tempora/104-0.txt

Added Propaganda txt in Spanish, and Latin refactor for 104-0 file to reference Commune/Propaganda in [Commemoratio Postcommunio]

Added spanish Propaganda and using reference for latin Propaganda

---

web/www/missa/English/Commune/C10c.txt
web/www/missa/English/Commune/C10t.txt
web/www/missa/English/Commune/C11p.txt
web/www/missa/English/Sancti/07-02.txt
web/www/missa/English/Sancti/07-02o.txt
web/www/missa/English/Sancti/09-08.txt
web/www/missa/Espanol/Sancti/05-31.txt
web/www/missa/Espanol/Sancti/09-08.txt
web/www/missa/Latin/Commune/C10.txt
web/www/missa/Latin/Commune/C10Pasc.txt
web/www/missa/Latin/Commune/C10c.txt
web/www/missa/Latin/Commune/C10t.txt
web/www/missa/Latin/Commune/C11.txt
web/www/missa/Latin/Commune/C11p.txt
web/www/missa/Latin/Sancti/05-24pl.txt
web/www/missa/Latin/Sancti/05-31.txt
web/www/missa/Latin/Sancti/07-02.txt
web/www/missa/Latin/Sancti/07-02o.txt
web/www/missa/Latin/Sancti/09-08.txt

Following files were modified:
Missa/
C10c
c10Pasc
C11
c10t
C11p
05-31
07-02
07-02o
09-08
Introitus using reference to file C10. Languages impacted: Latin, English, Spanish

using same reference to introitus in latin, english and spanish salve+psalm44:2

---

web/cgi-bin/horas/horas.pl

remove code redudancy

---

web/cgi-bin/horas/specials.pl

code: checksuffragium - use 'Latin' and state variable

---

web/cgi-bin/horas/specials.pl

code: partially revoke 35b2e9ee6f, state variable does not work with *compare office*

---

web/www/missa/English/Commune/C8.txt
web/www/missa/English/Sancti/11-18.txt
web/www/missa/English/Sancti/11-18o.txt
web/www/missa/English/Sancti/11-18r.txt
web/www/missa/Espanol/Commune/C8.txt
web/www/missa/Espanol/Ordo/Prefationes.txt
web/www/missa/Espanol/Sancti/11-18.txt
web/www/missa/Espanol/Sancti/11-18o.txt
web/www/missa/Espanol/Sancti/11-18r.txt
web/www/missa/Latin/Commune/C8.txt
web/www/missa/Latin/Ordo/Prefationes.txt
web/www/missa/Latin/Sancti/11-18.txt
web/www/missa/Latin/Sancti/11-18o.txt
web/www/missa/Latin/Sancti/11-18r.txt

Modified C8 files and 11-18 sancti files.

minor refactor and spanish translations for Dedicationis Ecclessiae

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/specials.pl

fixing syntax error at horas.pl and specials.pl

perl syntax fix

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/specials.pl

Reverts DivinumOfficium/divinum-officium#3889

Revert "perl syntax fix"

---

web/www/horas/English/Tempora/Pent02-5.txt
web/www/horas/Espanol/Tempora/Pent02-5.txt
web/www/horas/Francais/Tempora/Pent02-5.txt
web/www/horas/Italiano/Tempora/Pent02-5.txt
web/www/horas/Italiano/Tempora/Pent02-5o.txt
web/www/horas/Latin/Tempora/Pent02-5.txt
web/www/horas/Latin/Tempora/Pent02-5o.txt
web/www/horas/Magyar/Tempora/Pent02-5.txt
web/www/horas/Magyar/Tempora/Pent02-5o.txt
web/www/missa/English/Tempora/Pent02-5.txt
web/www/missa/English/Tempora/Pent02-5o.txt
web/www/missa/Espanol/Tempora/Pent02-5.txt
web/www/missa/French/Tempora/Pent02-5.txt
web/www/missa/Italiano/Tempora/Pent02-5.txt
web/www/missa/Latin/Tempora/Pent02-5.txt
web/www/missa/Latin/Tempora/Pent02-5o.txt
web/www/missa/Magyar/Tempora/Pent02-5.txt
web/www/missa/Nederlands/Tempora/Pent02-5.txt
web/www/missa/Polski/Tempora/Pent02-5.txt
web/www/missa/Portugues/Tempora/Pent02-5.txt

([credits](https://www.facebook.com/groups/breviarydiscussion/posts/8061050467287032/))

Sanctissimi -> Sacratissimi Cordis DNJC

---

web/www/horas/Magyar/Tempora/Pent01-0.txt
web/www/horas/Magyar/Tempora/Pent01-1.txt
web/www/horas/Magyar/Tempora/Pent01-2.txt
web/www/horas/Magyar/Tempora/Pent01-3.txt
web/www/horas/Magyar/Tempora/Pent01-4.txt
web/www/horas/Magyar/Tempora/Pent01-5.txt
web/www/horas/Magyar/Tempora/Pent02-0.txt
web/www/horas/Magyar/Tempora/Pent02-5.txt
web/www/horas/Magyar/Tempora/Pent04-0.txt
web/www/horas/Magyar/Tempora/Pent05-0.txt
web/www/horas/Magyar/Tempora/Pent06-0.txt
web/www/horas/Magyar/Tempora/Pent07-0.txt
web/www/horas/Magyar/Tempora/Pent08-0.txt
web/www/horas/Magyar/Tempora/Pent09-0.txt
web/www/horas/Magyar/Tempora/Pent10-0.txt
web/www/horas/Magyar/Tempora/Pent11-0.txt
web/www/horas/Magyar/Tempora/Pent12-0.txt
web/www/horas/Magyar/Tempora/Pent13-0.txt
web/www/horas/Magyar/Tempora/Pent14-0.txt
web/www/horas/Magyar/Tempora/Pent15-0.txt
web/www/horas/Magyar/Tempora/Pent16-0.txt
web/www/horas/Magyar/Tempora/Pent17-0.txt
web/www/horas/Magyar/Tempora/Pent18-0.txt
web/www/horas/Magyar/Tempora/Pent19-0.txt
web/www/horas/Magyar/Tempora/Pent20-0.txt
web/www/horas/Magyar/Tempora/Pent21-0.txt
web/www/horas/Magyar/Tempora/Pent22-0.txt
web/www/horas/Magyar/Tempora/Pent23-0.txt
web/www/horas/Magyar/Tempora/Pent24-0.txt

Szunyogh Xavér Ferenc OSB's translation: this is the most widespread translation in Hungary

Hungarian Oratios for the Ordinary Time

---

web/cgi-bin/horas/horascommon.pl

MONASTIC: add missing Matutinum responsories in vigils during summer

---

web/cgi-bin/horas/dialogcommon.pl

Preventing some cause of infinite loops for Matins Gospel in Monastic

Some part for #525

---

web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specials.pl
web/www/horas/Dansk/Psalterium/Prayers.txt
web/www/horas/Deutsch/Psalterium/Prayers.txt
web/www/horas/Deutsch/Psalterium/Translate.txt
web/www/horas/English/Psalterium/Prayers.txt
web/www/horas/English/Psalterium/Translate.txt
web/www/horas/Espanol/Psalterium/Prayers.txt
web/www/horas/Francais/Psalterium/Prayers.txt
web/www/horas/Italiano/Psalterium/Prayers.txt
web/www/horas/Italiano/Psalterium/Translate.txt
web/www/horas/Latin/Psalterium/Prayers.txt
web/www/horas/Latin/Psalterium/Prima Special.txt
web/www/horas/Latin/Psalterium/Translate.txt
web/www/horas/Magyar/Psalterium/Prayers.txt
web/www/horas/Ordinarium/Completorium.txt
web/www/horas/Ordinarium/Matutinum.txt
web/www/horas/Ordinarium/Prima.txt
web/www/horas/Polski/Psalterium/Prayers.txt
web/www/horas/Portugues/Psalterium/Prayers.txt

expand some prayers, rubrics when expand=psalms. mainly in Prima

---

web/cgi-bin/DivinumOfficium/RunTimeOptions.pm
web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/officium_html.pl
web/cgi-bin/horas/specials.pl

- fix unknown version handling
- fix Lectio brevis in Prima - Monastic
- add notification 'incomplete' to Ordo Praedicatorum version
- capitalize first letter in expand links - probably needed only for 'pater_noster'
+AMDG+

small code update

---

web/www/horas/Latin/Commune/C7ap.txt
web/www/horas/Latin/Sancti/05-04.txt
web/www/horas/Latin/Sancti/05-22n.txt
web/www/horas/Latin/Sancti/06-10.txt
web/www/horas/Latin/Sancti/10-08.txt

@fiapps  Please let me know if there are other instances of doubled *Deo gratias* (potentially arising from circular references in Commune _in paschal tide?_)

Commune C7ap: Double Deo gratias  #3921

---

web/cgi-bin/horas/specials.pl
web/www/Tabulae/Kalendaria/OP1962.txt
web/www/Tabulae/data.txt
web/www/horas/Ordinarium/Laudes.txt
web/www/horas/Ordinarium/Vespera.txt

- no Preces Feriales
- add Kyrie to Ferial Office
- kalendar update et rename to OP1962
+AMDG+

OP: update

---

web/cgi-bin/horas/horascommon.pl
web/www/horas/Dansk/Psalterium/Prayers.txt
web/www/horas/Deutsch/Psalterium/Prayers.txt
web/www/horas/Deutsch/Psalterium/Translate.txt
web/www/horas/English/Psalterium/Prayers.txt
web/www/horas/English/Psalterium/Translate.txt
web/www/horas/Espanol/Psalterium/Prayers.txt
web/www/horas/Espanol/Psalterium/Translate.txt
web/www/horas/Francais/Psalterium/Prayers.txt
web/www/horas/Francais/Psalterium/Translate.txt
web/www/horas/Italiano/Psalterium/Prayers.txt
web/www/horas/Italiano/Psalterium/Translate.txt
web/www/horas/Latin/Psalterium/Prayers.txt
web/www/horas/Latin/Psalterium/Prima Special.txt
web/www/horas/Latin/Psalterium/Translate.txt
web/www/horas/Magyar/Psalterium/Prayers.txt
web/www/horas/Magyar/Psalterium/Translate.txt
web/www/horas/Ordinarium/Completorium.txt
web/www/horas/Ordinarium/Laudes.txt
web/www/horas/Ordinarium/Matutinum.txt
web/www/horas/Ordinarium/Minor.txt
web/www/horas/Ordinarium/Prima.txt
web/www/horas/Ordinarium/Vespera.txt
web/www/horas/Polski/Psalterium/Prayers.txt
web/www/horas/Polski/Psalterium/Translate.txt
web/www/horas/Portugues/Psalterium/Prayers.txt
web/www/horas/Portugues/Psalterium/Translate.txt

- hide Pater... in Incipit when expand=psalms for 196 rules
- expand some prayers, rubrics in Completorium & Prima when expand=psalms
- R. Amen - no expandable
+AMDG+

update Translate, Prayers et Ordinarium

---

web/www/horas/Latin/Psalterium/Prayers.txt
web/www/horas/Ordinarium/Laudes.txt
web/www/horas/Ordinarium/Matutinum.txt
web/www/horas/Ordinarium/Minor.txt
web/www/horas/Ordinarium/Prima.txt
web/www/horas/Ordinarium/Vespera.txt

follow #72a689e81b: fix 1955 Incipit, clean Prayers

---

web/cgi-bin/DivinumOfficium/RunTimeOptions.pm
web/cgi-bin/horas/dialogcommon.pl
web/cgi-bin/missa/missa.pl
web/cgi-bin/missa/propers.pl
web/www/Tabulae/data.txt
web/www/missa/missa.dialog

Reverts DivinumOfficium/divinum-officium#3934

Revert "Brute Force solution to #525 + Missa version names"

---

web/cgi-bin/horas/dialogcommon.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/officium_html.pl
web/www/Tabulae/data.txt
web/www/horas/horas.dialog

straighten old monastic internal version names

---

web/cgi-bin/horas/hymni.pl
web/cgi-bin/horas/specials.pl

code: separate hymns functions to hymni.pl + doxology refactor

---

web/www/missa/English/Commune/C6a.txt
web/www/missa/English/Commune/C6ap.txt
web/www/missa/English/Sancti/01-23.txt
web/www/missa/English/Sancti/02-06.txt
web/www/missa/English/Sancti/02-06o.txt
web/www/missa/English/Sancti/07-20.txt
web/www/missa/English/Sancti/07-20o.txt
web/www/missa/English/Sancti/07-24r.txt
web/www/missa/English/Sancti/08-29.txt
web/www/missa/Espanol/Commune/C6a.txt
web/www/missa/Espanol/Sancti/07-20.txt
web/www/missa/Latin/Commune/C6ap.txt
web/www/missa/Latin/Sancti/01-23.txt
web/www/missa/Latin/Sancti/01-23o.txt
web/www/missa/Latin/Sancti/02-06.txt
web/www/missa/Latin/Sancti/02-06o.txt
web/www/missa/Latin/Sancti/07-20.txt
web/www/missa/Latin/Sancti/07-20o.txt
web/www/missa/Latin/Sancti/07-24r.txt
web/www/missa/Latin/Sancti/08-29.txt
web/www/missa/Latin/Sancti/11-13pl.txt
web/www/missa/Latin/Sancti/12-02.txt

References tested, no nesting references found. Load times ok.

translation spanish mass 07-20 with references

---

web/www/horas/English/TemporaM/Pasc7-1.txt
web/www/horas/English/TemporaM/Pasc7-2.txt
web/www/horas/Italiano/TemporaM/Pasc7-1.txt
web/www/horas/Italiano/TemporaM/Pasc7-2.txt
web/www/horas/Latin/TemporaM/Pasc7-1.txt
web/www/horas/Latin/TemporaM/Pasc7-2.txt
web/www/horas/Polski/TemporaM/Pasc7-1.txt
web/www/horas/Polski/TemporaM/Pasc7-2.txt

close https://github.com/FAJ-Munich/divinum-officium/issues/21

MONASTIC 1617/1930: 12 lectiones Die II et III Pentecostes

---

web/www/horas/Francais/Psalterium/Psalmi minor.txt

Francais: fix Prima layout

---

web/cgi-bin/horas/hymni.pl
web/www/horas/Latin/Psalterium/Minor Special.txt
web/www/horas/Latin/Tempora/Pasc5-4.txt

OP: temporal hymns for Completorium

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/horascommon.pl
web/www/horas/Dansk/Psalterium/Minor Special.txt
web/www/horas/Dansk/Psalterium/Psalmi minor.txt
web/www/horas/Deutsch/Psalterium/Minor Special.txt
web/www/horas/Deutsch/Psalterium/Psalmi minor.txt
web/www/horas/English/Psalterium/Minor Special.txt
web/www/horas/English/Psalterium/Psalmi minor.txt
web/www/horas/Espanol/Psalterium/Minor Special.txt
web/www/horas/Espanol/Psalterium/Psalmi minor.txt
web/www/horas/Francais/Psalterium/Minor Special.txt
web/www/horas/Francais/Psalterium/Psalmi minor.txt
web/www/horas/Italiano/Psalterium/Minor Special.txt
web/www/horas/Italiano/Psalterium/Psalmi minor.txt
web/www/horas/Latin/Commune/C11.txt
web/www/horas/Latin/Psalterium/Minor Special.txt
web/www/horas/Latin/Psalterium/Psalmi minor.txt
web/www/horas/Magyar/Psalterium/Minor Special.txt
web/www/horas/Magyar/Psalterium/Psalmi minor.txt
web/www/horas/Polski/Psalterium/Minor Special.txt
web/www/horas/Polski/Psalterium/Psalmi minor.txt
web/www/horas/Portugues/Psalterium/Minor Special.txt
web/www/horas/Portugues/Psalterium/Psalmi minor.txt

- Nunc_dimittis refactor
- move 'Ant nunc dimittis' to 'Minor Special'
+AMDG+

OP: temporal antiphonas for Nunc dimittis

---

web/cgi-bin/horas/dialogcommon.pl
web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/psalmi.pl
web/cgi-bin/horas/specials.pl

- allow directories {Sancti|Tempora|Commune}OP with fallback to regular
- psalmi ad Vespera can be sub una antiphona
+AMDG+

code update for OP

---

web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/Latin/Sancti/11-19.txt
web/www/horas/Latin/Tempora/Pasc5-1.txt

- rewrite handling Te Deum and Responsories (obsolete &teDeum in data files)
- replace addtedeum with tedeum_required
- rewrite responsory_gloria
- add responsory before Te Deum for OP
+AMDG+

code update in Matutinum:

---

web/cgi-bin/horas/specmatins.pl

to close #3991 but re-establish 9th lectio for cases like 08-11-2024 for Tridentine version

Close #3991

---

web/cgi-bin/horas/dialogcommon.pl

Fixing MONASTIC Matutinum Gospel references to missa

---

epub/Eofficium.pl
standalone/tools/epubgen2/EofficiumXhtml.pl

Fixing ePub

---

web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specials.pl
web/www/horas/Latin/Regula/OrdoPraedicatorum.txt
web/www/horas/Ordinarium/Prima.txt

- also separate Lectio brevis Prima, Lectio Evangeli to own functions
+AMDG+

OP: add regula Augustini or Evangelium reading to Prima

---

web/www/horas/Latin/Sancti/02-24.txt
web/www/horas/Latin/Sancti/07-25.txt
web/www/horas/Latin/Sancti/08-24.txt
web/www/horas/Latin/Sancti/09-21.txt
web/www/horas/Latin/Sancti/10-18.txt
web/www/horas/Latin/Sancti/11-30.txt
web/www/horas/Latin/Sancti/12-21.txt
web/www/horas/Latin/SanctiM/07-25.txt
web/www/horas/Latin/SanctiM/09-21.txt

MONASTIC: fix ranks of Apostolis feasts

---

web/cgi-bin/horas/specmatins.pl
web/www/horas/English/Sancti/07-24.txt
web/www/horas/English/Sancti/08-23.txt
web/www/horas/English/Sancti/08-23o.txt
web/www/horas/English/Sancti/09-20.txt
web/www/horas/Espanol/Sancti/09-20.txt
web/www/horas/Espanol/Sancti/09-20o.txt
web/www/horas/Francais/Sancti/09-20.txt
web/www/horas/Francais/Sancti/09-20o.txt
web/www/horas/Italiano/Sancti/09-20.txt
web/www/horas/Italiano/Sancti/09-20o.txt
web/www/horas/Latin/Sancti/07-24.txt
web/www/horas/Latin/Sancti/08-05.txt
web/www/horas/Latin/Sancti/08-23.txt
web/www/horas/Latin/Sancti/08-23o.txt
web/www/horas/Latin/Sancti/09-20.txt
web/www/horas/Latin/Sancti/09-20o.txt
web/www/horas/Latin/Sancti/11-21.txt
web/www/horas/Latin/SanctiM/11-21.txt
web/www/horas/Magyar/Sancti/09-20.txt
web/www/horas/Magyar/Sancti/09-20o.txt

- code: readings from "ex commune" take precedence over Scriptura
- data update
+AMDG+

Fix Matutinum readings for Vigils of Ap.

---

web/www/horas/Latin/Sancti/09-08.txt

fix rank of Nat. BMV in '60

---

web/cgi-bin/horas/horascommon.pl

and removing Commemorations from Votiva

Fix Officium parvum BMV

---

web/www/Tabulae/Kalendaria/1570.txt
web/www/Tabulae/Kalendaria/1888.txt
web/www/Tabulae/Kalendaria/1906.txt

adding comeoration to March 7 for Tridentine

Trid: Perpetua et Felicitates

---

web/www/horas/Latin/Sancti/02-22.txt
web/www/horas/Latin/Sancti/04-23.txt
web/www/horas/Latin/Sancti/04-25t.txt
web/www/horas/Latin/Sancti/05-31.txt
web/www/horas/Latin/Sancti/07-02.txt
web/www/horas/Latin/Sancti/07-26.txt
web/www/horas/Latin/Sancti/08-10.txt
web/www/horas/Latin/Sancti/08-16.txt
web/www/horas/Latin/Sancti/08-22.txt
web/www/horas/Latin/Sancti/09-15.txt
web/www/horas/Latin/Sancti/10-07.txt
web/www/horas/Latin/Sancti/10-28.txt
web/www/horas/Latin/SanctiM/04-23.txt

fix ranks for 196'

---

web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specials.pl

code: 'Tu autem' expandable in Prima

---

web/www/horas/Espanol/psalms1/Psalm77.txt

@d4h0y0sr  Maybe you have a better translation than google for this missing verse
close #4036

Spanish: add Psalm 77 Verse 18

---

web/www/horas/Latin/TemporaM/092-0.txt
web/www/horas/Latin/TemporaM/Pent08-0.txt

MONASTIC: capitalize initial letter in readings

---

web/cgi-bin/horas/horas.pl
web/www/horas/Latin/Psalterium/Major Special.txt

Major Special - mark mute vovels

---

web/www/horas/English/TemporaM/Pasc0-1.txt
web/www/horas/Italiano/TemporaM/Pasc0-1.txt
web/www/horas/Latin/Tempora/Pasc0-2t.txt
web/www/horas/Latin/TemporaM/Pasc0-1.txt
web/www/horas/Latin/TemporaM/Pasc0-2.txt
web/www/horas/Polski/TemporaM/Pasc0-1.txt

Close: https://github.com/FAJ-Munich/divinum-officium/issues/31

M1617/1930: Lectiones diei II et III infra 8vam Paschæ

---

web/cgi-bin/horas/horascommon.pl

e.g., 1-14-2024
Close https://github.com/FAJ-Munich/divinum-officium/issues/33

M1963: no commemoration of Memoria in Dominica

---

web/www/missa/English/Commune/C4b.txt
web/www/missa/English/Sancti/09-23.txt

Made "Alleluia" conditional to Paschal time and took out extraneous line-feeds.

Corrections and formatting.

---

web/www/horas/Portugues/Psalterium/Comment.txt
web/www/horas/Portugues/Psalterium/Minor Special.txt
web/www/horas/Portugues/Psalterium/Revtrans.txt
web/www/horas/Portugues/Psalterium/Translate.txt
web/www/horas/Portugues/psalms1/Psalm231.txt
web/www/horas/Portugues/psalms1/Psalm232.txt
web/www/horas/Portugues/psalms1/Psalm233.txt

I modified major hour canticle translations to fit the book I have, since I intend to continue committing.

fixes typos, adds new translations

---

web/www/horas/Portugues/Psalterium/Prayers.txt

Also translates conclusion ending

feat: add pater noster and kyrie translation for monastic diurnal

---

web/cgi-bin/missa/propers.pl

@APMarcello3  fixing the issue from your correspondent

Missa 1960: Restore Commemoratio Dominica in Missa solemnis

---

web/cgi-bin/horas/specials.pl
web/www/horas/Latin/Commune/C12.txt
web/www/horas/Latin/CommuneM/C12.txt

C12: update

---

web/www/horas/Help/technical.html

@APMarcello3 and @mbab 
The conditionals have been part of the repository since a merge by Gregor Dick in 2012. I have spent a lot of time these days to understand their full functioning and hope I have grasped it now: the discription of how I believe it works is added to technical.html. The example from the Ordo is from my developing branch for the Cistercian rite.

Description of Conditionals and Rules in technical.html

---

web/www/horas/Ordinarium/Matutinum.txt

restore cell separator before Invitatorium

---

web/cgi-bin/horas/specials.pl
web/cgi-bin/horas/specmatins.pl

move getantmatutinum to specmatins.pl

---

web/www/missa/English/Sancti/10-10.txt
web/www/missa/Latin/Sancti/10-10.txt

Close #4091

---

standalone/tools/epubgen2/Ewebdia.pl
web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/officium_html.pl
web/cgi-bin/horas/webdia.pl
web/www/horas/horas.setup

- improving Dark Mode close #3265
- iBook cannot render ePub of invalid XHTML: therefore ensuring quotes around attributes and closing tags throughout 
epubgen2 results do render now on my mac; but still ignoring all line break

MacOS functionalities

---

web/cgi-bin/horas/specials.pl
web/www/horas/Latin/Psalterium/Translate.txt
web/www/horas/Polski/Psalterium/Translate.txt

code: translate in specials

---

web/cgi-bin/horas/specials.pl
web/cgi-bin/horas/specials/hymni.pl

code: tryoldhymn, return if possible for oldversion keyname instead of hymn text

---

web/cgi-bin/horas/specials.pl
web/cgi-bin/horas/specials/specprima.pl

code: rewrite lectio_brevis_prima, remove obsolete now getfromcommune

---

web/www/horas/Latin/Sancti/03-21.txt
web/www/horas/Latin/Sancti/06-04.txt
web/www/horas/Latin/Sancti/08-26.txt

@FAJ-Munich wonder why we have Commune in two places
+AMDG+

set commune in [Rule] as in [Rank]

---

web/www/horas/Latin/Sancti/12-11.txt

Psalms at S. Damasi Vespers

---

web/www/horas/Deutsch/CommuneM/C1.txt
web/www/horas/Italiano/CommuneM/C1.txt

MONASTIC: {Deutsch/Italiano} C1 - fix Ant. Mat.

---

web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specmatins.pl

code: fix readings in C10 for older Monastic

---

web/cgi-bin/missa/propers.pl

code: ugly fix #3899

---

web/cgi-bin/horas/horascommon.pl

continuation of d06bccd6d1 #4151
+AMDG+

continuation of d06bccd6d1 #4151

---

web/www/horas/Francais/Tempora/Pasc3-6.txt
web/www/horas/Italiano/Commune/C12.txt

fix layout Italiano/C12 & Francais/Pasc3-6

---

web/cgi-bin/missa/propers.pl

Fix Missa defunctorum

---

web/www/horas/Deutsch/Commune/C6.txt
web/www/horas/English/Sancti/08-01.txt
web/www/horas/Francais/Sancti/08-01.txt
web/www/horas/Italiano/Sancti/06-30.txt
web/www/horas/Italiano/Sancti/08-01.txt
web/www/horas/Latin/Sancti/08-01.txt
web/www/horas/Latin/SanctiM/02-05.txt
web/www/horas/Latin/SanctiM/06-30.txt
web/www/horas/Latin/SanctiM/09-29.txt
web/www/horas/Latin/TemporaM/Pasc7-0.txt

fix layouts in Monastic Vesperes

---

web/www/horas/English/TemporaM/Pasc7-3.txt
web/www/horas/Italiano/TemporaM/Pasc7-3.txt
web/www/horas/Latin/TemporaM/Pasc7-3.txt
web/www/horas/Polski/TemporaM/Pasc7-3.txt

MONASTIC: fix layout in Matutinum in Octave of Pentecost

---

web/cgi-bin/DivinumOfficium/SetupString.pl
web/cgi-bin/horas/horascommon.pl
web/www/horas/Latin/Psalterium/Comment.txt
web/www/horas/Polski/Psalterium/Comment.txt

Comment.txt in vernaculars needs to be filled.
+AMDG+

allow translation of days ranks using data in Comment.txt

---

web/cgi-bin/horas/horascommon.pl

remove empty newlines introduced by 1ff7c61

---

web/www/horas/English/Psalterium/Psalmi/Psalmi major.txt

Changes the word "the" into "thee".

Fix typo in Vespers

---

web/cgi-bin/horas/horasscripts.pl

fix false initial in Psalm 118

---

web/cgi-bin/horas/specials/specprima.pl
web/cgi-bin/horas/specmatins.pl

- restore presentation of biblical readings in one paragraph when nonumbers is in use
- fix Lectio3 09-13-2025 DA
- Prima 1963: remove useless comment from Capitulum
+AMDG+

code updates

---

web/www/horas/Latin/Psalterium/Common/Translate.txt

Per Dominum … ejusdem Spiritus

---

web/cgi-bin/horas/specmatins.pl

@mbab just a dirty fix as per my email

1888-1954: Fix readings for Dec 14

---

web/cgi-bin/horas/specmatins.pl
web/www/horas/Latin/Sancti/12-14.txt
web/www/horas/Latin/Sancti/12-15.txt

no last Lectio de Feria as Gospels are the same
Dec14: Lectiones ex Commune

Dec 14/15 in occurence with QT

---

web/www/horas/English/Psalterium/Mariaant.txt
web/www/horas/Latin/Commune/C12.txt
web/www/horas/Latin/Commune/C12A.txt
web/www/horas/Latin/Commune/C12N.txt

It seems like it has been broken for at least 3 years until someone noticed.

Fix C12: Hymnus minor

---

web/www/horas/English/Commune/C12A.txt
web/www/horas/Espanol/Commune/C12A.txt
web/www/horas/Italiano/Commune/C12A.txt
web/www/horas/Latin/Commune/C12A.txt
web/www/horas/Magyar/Commune/C12A.txt
web/www/horas/Polski/Commune/C12A.txt

C12A: close #4209

---

web/cgi-bin/horas/horascommon.pl

1960: Fix Vespers title on 2024-12-21

---

web/www/horas/English/Sancti/04-28n.txt
web/www/horas/English/Sancti/09-09n.txt
web/www/horas/Latin/Sancti/04-28.txt
web/www/horas/Latin/Sancti/04-28n.txt
web/www/horas/Latin/Sancti/06-22.txt
web/www/horas/Latin/Sancti/09-09n.txt
web/www/horas/Latin/Sancti/09-23.txt

NC: Removing Vespers commemorations for reduced Saints

---

web/www/horas/Latin/Sancti/10-24.txt
web/www/horas/Latin/SanctiM/07-17M.txt

Quick fixes

---

web/cgi-bin/DivinumOfficium/RunTimeOptions.pm
web/cgi-bin/horas/horasjs.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/kalendar/ical.pl
web/cgi-bin/horas/kalendar/kal.pl
web/cgi-bin/horas/kalendar/ordo.pl
web/cgi-bin/horas/officium_html.pl
web/cgi-bin/horas/webdia.pl
web/www/horas/Latin/Psalterium/Comment.txt

code: add Kalendarium as in printed books

---

web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/kalendar/kal.pl
web/cgi-bin/horas/kalendar/ordo.pl
web/www/horas/Latin/Psalterium/Comment.txt

- add black 19 to epact cycle & note for Dec 31st (suggested @FAJ-Munich)
- add space to empty fields in Compare (suggested @FAJ-Munich)
- remove obsolete reading 'Commemoratio' & 'Commemoratio 2'
- small letters in notes
- code improvement
+AMDG+

Kalendarium:

---

web/cgi-bin/horas/popup.pl

quick fix XSS vulnerabity in popup.pl

---

web/cgi-bin/horas/specials/orationes.pl

Restore Commemoratio de die infra 8vam Nat

---

web/cgi-bin/horas/kalendar/kal.pl

Kalendarium: Ranks of Octaves etc.

---

web/www/missa/Latin/Sancti/01-07.txt
web/www/missa/Latin/Sancti/01-08.txt
web/www/missa/Latin/Sancti/01-09.txt
web/www/missa/Latin/Sancti/01-10.txt
web/www/missa/Latin/Sancti/01-11.txt
web/www/missa/Latin/Sancti/01-12.txt
web/www/missa/Latin/Sancti/01-13.txt

1960: Tempora Epiphaniae (in missa)

---

web/www/horas/Latin/Appendix/Ante et Post Divinum Officium.txt
web/www/horas/Latin/Appendix/Index.txt
web/www/horas/Latin/Psalterium/Common/Prayers.txt
web/www/horas/Latin/Psalterium/Common/Rubricae.txt

Adding Prayers before and after to appendix

---

web/www/missa/English/Commune/C10.txt
web/www/missa/English/Commune/C10b.txt
web/www/missa/English/Tempora/C10c.txt

Forces the next line to be completely red.

Remove extra line with exclamation

---

web/www/missa/Deutsch/Ordo/Ordo.txt
web/www/missa/Latin/Ordo/Ordo.txt
web/www/missa/Latin/Tempora/Quad6-6.txt
web/www/missa/Latin/Tempora/Quad6-6r.txt
web/www/missa/Latin/Tempora/Quad6-6t.txt

"ip + sum, et cum ip + so, et in ip + so" → "Ip + sum, et cum Ip + so, et in Ip + so" for same reasons given in #4236

ipso/um → Ipso/um

---

admin/divinum-get.pl
admin/divinum-replay.pl
epub/Eofficium.pl
epub/Ewebdia.pl
obsolete/horas/Ckalendar.pl
obsolete/horas/brevi.pl
obsolete/horas/edit.pl
obsolete/horas/kalendarcomp.pl
obsolete/horas/ordo.pl
obsolete/missa/Ckalendar.pl
obsolete/missa/kalendar.pl
obsolete/missa/medit.pl
obsolete/missa/source.pl
standalone/tools/epubgen2/EofficiumXhtml.pl
standalone/tools/epubgen2/Ewebdia.pl
web/cgi-bin/DivinumOfficium/setup.pl
web/cgi-bin/horas/horasjs.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/kalendar/ical.pl
web/cgi-bin/horas/kalendar/kal.pl
web/cgi-bin/horas/kalendar/ordo.pl
web/cgi-bin/horas/officium_html.pl
web/cgi-bin/horas/webdia.pl
web/cgi-bin/missa/Cmissa.pl
web/cgi-bin/missa/Emissa.pl
web/cgi-bin/missa/missa.pl

- **fix some portuguese rubrics**
- **add portuguese translations for communicantes, based on translation by dom gaspar lefebvre**
- **style #4249: conform to the new heredoc spacing controls**

Conform to new Perl heredoc spacing controls

---

web/www/missa/Latin/Ordo/Ordo.txt
web/www/missa/Portugues/Ordo/Ordo.txt
web/www/missa/Portugues/Ordo/Prayers.txt

- **Addresses the issue #4245, removes a few <br />s**
- **style: forgot running perltidy, sorry**
- **fix some portuguese and latin rubrics**

fix some portuguese and latin rubrics

---

web/cgi-bin/DivinumOfficium/SetupString.pl
web/www/horas/Latin/Sancti/12-31.txt
web/www/horas/Latin/Sancti/12-31r.txt

code: remove resolving Gregem too early

---

web/cgi-bin/missa/ordo.pl
web/www/missa/Portugues/Ordo/Prefationes.txt

- **Remove spurious rubrics and translate special hanc igitur to portuguese**
- **generalize and fix spurious newline in hanc igitur**
- **style: adjust )**

Generalize and fix solution to spurious newlines in hanc igitur

---

web/www/horas/Portugues/Psalterium/Common/Prayers.txt
web/www/horas/Portugues/Psalterium/Common/Translate.txt
web/www/horas/Portugues/Psalterium/Special/Prima Special.txt

- **Squash merge translate/prima into master**
- **fix a typo (a vimmer's pain)**

Some portuguese Prima translations

---

web/www/horas/Portugues/Commune/C4.txt
web/www/horas/Portugues/Commune/C5.txt
web/www/horas/Portugues/Commune/C6.txt
web/www/horas/Portugues/Psalterium/Psalmi/Psalmi major.txt
web/www/horas/Portugues/Psalterium/Psalmi/Psalmi minor.txt
web/www/horas/Portugues/Santi/01-29.txt
web/www/horas/Portugues/Santi/06-12.txt

I'm using the Matos Soares Bible (1956), for somes pray I found a book called "DIURNAL MONÁSTICO - latim — português", elabored by a group of monk from "Mosteiro de São Bento do Rio de Janeiro".

laudes, prima and tertia - 1-20-2025

---

web/www/missa/Portugues/Ordo/Ordo.txt
web/www/missa/Portugues/Ordo/Prefationes.txt

- **Translate a few prefaces and rubrics**
- **1963 and 1940 brazilian missalettes gives no propers for these prefaces**
- **Some occasional translations for portuguese preface rubrics.**

Translations for portuguese prefaces

---

web/cgi-bin/horas/monastic.pl

code: MONASTIC fix condition when to swap Fridays Matutinum psalms

---

web/cgi-bin/horas/popup.pl

close #4291  (add fallback language to popup @mbab )

Follow up to PR #4274

---

web/www/horas/Deutsch/Tempora/Quadp1-0.txt
web/www/horas/Deutsch/Tempora/Quadp3-0.txt
web/www/horas/Espanol/Tempora/Quadp1-0.txt
web/www/horas/Francais/Psalterium/Special/Major Special.txt
web/www/horas/Francais/Tempora/Quadp1-0.txt

and also for German and Spanish

cleaner fix d6655d35fcae82ceb2319e46f355d654bff61188

---

standalone/tools/epubgen2/Ehoras.setup
standalone/tools/epubgen2/EofficiumXhtml.pl

@mbab.
added fallback language to epubgen2
for some reason, the days per month count  up too far and then there are date errors.  not sure what's happening

some things for #4295

---

web/cgi-bin/horas/specials/orationes.pl

1930: fix Commemoratio de cruce in Vespera Tempore Paschali

---

web/cgi-bin/horas/specials/capitulis.pl
web/www/horas/Bohemice/Commune/C1.txt
web/www/horas/Latin/Commune/C1.txt
web/www/horas/Latin/CommuneM/C1.txt
web/www/horas/Latin/SanctiM/12-21.txt

Cistercian (both versions): introducing changes to the C1.txt file along with a Czech translation of day Hours.

Cist: Commune Apostolorum extra T.P. + Czech Translation

---

web/www/Tabulae/Kalendaria/CAV.txt
web/www/horas/Bohemice/Commune/C1.txt
web/www/horas/Bohemice/Commune/C1p.txt
web/www/horas/Bohemice/Commune/C2.txt
web/www/horas/Bohemice/CommuneM/C1p.txt
web/www/horas/Bohemice/CommuneM/C2.txt
web/www/horas/Bohemice/CommuneM/C2p.txt
web/www/horas/Bohemice/Psalterium/Psalmi/Psalmi major.txt
web/www/horas/Bohemice/Psalterium/Psalmi/Psalmi minor.txt
web/www/horas/Bohemice/Psalterium/Special/Minor Special.txt
web/www/horas/Latin/Commune/C1p.txt
web/www/horas/Latin/Commune/C2.txt
web/www/horas/Latin/CommuneM/C1p.txt
web/www/horas/Latin/CommuneM/C2.txt
web/www/horas/Latin/CommuneM/C2p.txt
web/www/horas/Latin/CommuneM/C3.txt
web/www/horas/Latin/Psalterium/Psalmi/Psalmi minor.txt
web/www/horas/Latin/Sancti/01-22.txt
web/www/horas/Latin/SanctiM/01-19C.txt
web/www/horas/Latin/SanctiM/05-01cist.txt
web/www/horas/Latin/SanctiM/05-02cist.txt
web/www/horas/Latin/SanctiM/09-28.txt

Cistercian version added for Commune C1p, C2 and C2p incl. Czech + small fixes in Czech translation in other places
Small additions into the Altovadensis calendar, in order to create feasts for testing. 
Still only diurnal Hours.

Cist: C1p, C2 and C2p incl. Czech + small fixes in Czech

---

web/www/Tabulae/Kalendaria/CAV.txt
web/www/horas/Bohemice/Commune/C3.txt
web/www/horas/Bohemice/Commune/C4.txt
web/www/horas/Bohemice/Commune/C4a.txt
web/www/horas/Bohemice/CommuneM/C3.txt
web/www/horas/Bohemice/CommuneM/C4.txt
web/www/horas/Bohemice/Psalterium/Special/Major Special.txt
web/www/horas/Latin/Commune/C12.txt
web/www/horas/Latin/Commune/C3.txt
web/www/horas/Latin/CommuneM/C3.txt
web/www/horas/Latin/CommuneM/C4.txt
web/www/horas/Latin/Psalterium/Special/Major Special.txt
web/www/horas/Latin/Sancti/01-22.txt
web/www/horas/Latin/SanctiM/05-09C.txt

Cist: updated C3, C3, C4 and C4a for the Cistercian version (both of them)
Added Czech translation 
Bugfixes in Suffrage of Our Lady (Cist.)

Cist: upd. C3, C3, C4 and C4a + Czech 

---

web/www/Tabulae/Kalendaria/CAV.txt
web/www/horas/Bohemice/Commune/C2.txt
web/www/horas/Bohemice/Commune/C5.txt
web/www/horas/Bohemice/Commune/C6.txt
web/www/horas/Bohemice/Commune/C6a.txt
web/www/horas/Bohemice/Commune/C6b.txt
web/www/horas/Bohemice/Commune/C7.txt
web/www/horas/Bohemice/Commune/C7a.txt
web/www/horas/Bohemice/Commune/C7b.txt
web/www/horas/Bohemice/CommuneM/C5.txt
web/www/horas/Bohemice/CommuneM/C6.txt
web/www/horas/Bohemice/CommuneM/C7.txt
web/www/horas/Latin/Commune/C6.txt
web/www/horas/Latin/CommuneM/C5.txt
web/www/horas/Latin/CommuneM/C6.txt
web/www/horas/Latin/CommuneM/C7.txt
web/www/horas/Latin/CommuneM/C7a.txt
web/www/horas/Latin/SanctiM/01-26C.txt
web/www/horas/Latin/SanctiM/02-12C.txt
web/www/horas/Latin/SanctiM/05-31.txt

Cistercian version added to C5, C6 and C7 (including the "a" and "b" variants) 
Czech translation added

Cist: Upd. C5-C7 incl a+b

---

web/www/horas/Deutsch/Sancti/02-22.txt
web/www/horas/English/Sancti/02-22.txt
web/www/horas/English/SanctiM/01-18.txt
web/www/horas/English/SanctiM/02-22.txt
web/www/horas/Espanol/Sancti/02-22.txt
web/www/horas/Francais/Sancti/02-22.txt
web/www/horas/Italiano/Sancti/02-22.txt
web/www/horas/Latin/Sancti/01-18.txt
web/www/horas/Latin/Sancti/02-22.txt
web/www/horas/Latin/SanctiM/01-18.txt
web/www/horas/Latin/SanctiM/02-22.txt
web/www/horas/Polski/Sancti/02-22.txt
web/www/horas/Polski/SanctiM/01-18.txt
web/www/horas/Polski/SanctiM/02-22.txt

01-18 & 02-22 Monastic update + 01-18 1570 fix readings + accents

---

web/www/horas/Bohemice/Commune/C9.txt
web/www/horas/Bohemice/CommuneM/C9.txt
web/www/horas/Bohemice/Psalterium/Common/Prayers.txt
web/www/horas/Latin/Commune/C9.txt
web/www/horas/Latin/CommuneM/C9.txt
web/www/horas/Latin/Psalterium/Common/Prayers.txt

Cistercian Rite: C9 finished + Czech translation added

Cist: C9 finished + Czech translation

---

web/www/horas/Francais/Psalterium/Special/Prima Special.txt

Update Prima Special.txt

---

standalone/tools/epubgen2/EofficiumXhtml.pl
standalone/tools/epubgen2/epubgen2.sh
web/cgi-bin/missa/Emissa.pl

epubgen2.sh: add right side language

---

web/www/horas/Francais/Psalterium/Psalmi/Psalmi matutinum.txt

Update Psalmi matutinum.txt

---

web/www/horas/Latin/Sancti/03-07.txt

M1963: fix Saint Thomas rank

---

web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/specials.pl
web/cgi-bin/horas/specials/specprima.pl
web/www/horas/Latin/Sancti/01-22.txt
web/www/horas/Latin/SanctiM/01-21.txt

Trid: No "Vesp. a Capitulo" for Simplex

---

standalone/tools/epubgen2/EofficiumXhtml.pl
standalone/tools/epubgen2/epubgen2.sh

epubgen2.sh: update rubrics #4334

---

web/www/missa/Latin/Tempora/Quadp3-3.txt

in Ash Wednesday postcommunion

præbeant → prǽbeant

---

web/cgi-bin/horas/specials/capitulis.pl
web/www/horas/Bohemice/Psalterium/Special/Major Special.txt
web/www/horas/Deutsch/Psalterium/Special/Major Special.txt
web/www/horas/English/Psalterium/Special/Major Special.txt
web/www/horas/Espanol/Psalterium/Special/Major Special.txt
web/www/horas/Francais/Psalterium/Special/Major Special.txt
web/www/horas/Italiano/Psalterium/Special/Major Special.txt
web/www/horas/Latin/Psalterium/Special/Major Special.txt
web/www/horas/Latin/Psalterium/Special/Minor Special.txt
web/www/horas/Magyar/Psalterium/Special/Major Special.txt
web/www/horas/Polski/Psalterium/Special/Major Special.txt
web/www/horas/Portugues/Psalterium/Special/Major Special.txt

OP: officium in Quad.

---

web/cgi-bin/missa/ordo.pl

missa propers: enable *omit* Gloria Credo

---

standalone/tools/epubgen2/epubgen2.sh

- expose flags for changing lang1
- add dc codes for languages
- validate language flags
- move kindlegen logs to file so the console output is not so long

epubgen2: validate languages

---

web/cgi-bin/horas/horascommon.pl

code: remove superflous condition

---

web/cgi-bin/horas/specmatins.pl
web/www/horas/Bohemice/Psalterium/Psalmi/Psalmi minor.txt
web/www/horas/Bohemice/Psalterium/Special/Minor Special.txt
web/www/horas/Deutsch/Psalterium/Psalmi/Psalmi minor.txt
web/www/horas/Deutsch/Psalterium/Special/Matutinum Special.txt
web/www/horas/Deutsch/Psalterium/Special/Minor Special.txt
web/www/horas/English/Psalterium/Psalmi/Psalmi minor.txt
web/www/horas/English/Psalterium/Special/Matutinum Special.txt
web/www/horas/English/Psalterium/Special/Minor Special.txt
web/www/horas/Espanol/Psalterium/Psalmi/Psalmi minor.txt
web/www/horas/Espanol/Psalterium/Special/Matutinum Special.txt
web/www/horas/Espanol/Psalterium/Special/Minor Special.txt
web/www/horas/Francais/Psalterium/Psalmi/Psalmi minor.txt
web/www/horas/Francais/Psalterium/Special/Matutinum Special.txt
web/www/horas/Francais/Psalterium/Special/Minor Special.txt
web/www/horas/Italiano/Psalterium/Psalmi/Psalmi minor.txt
web/www/horas/Italiano/Psalterium/Special/Matutinum Special.txt
web/www/horas/Italiano/Psalterium/Special/Minor Special.txt
web/www/horas/Latin/Psalterium/Psalmi/Psalmi minor.txt
web/www/horas/Latin/Psalterium/Special/Major Special.txt
web/www/horas/Latin/Psalterium/Special/Matutinum Special.txt
web/www/horas/Latin/Psalterium/Special/Minor Special.txt
web/www/horas/Magyar/Psalterium/Psalmi/Psalmi minor.txt
web/www/horas/Magyar/Psalterium/Special/Matutinum Special.txt
web/www/horas/Magyar/Psalterium/Special/Minor Special.txt
web/www/horas/Polski/Psalterium/Psalmi/Psalmi minor.txt
web/www/horas/Polski/Psalterium/Special/Matutinum Special.txt
web/www/horas/Polski/Psalterium/Special/Minor Special.txt
web/www/horas/Portugues/Psalterium/Psalmi/Psalmi minor.txt

also fix translation issue mentioned in discussion in #4248
+AMDG+

OP: officium in Quad + Quad5

---

web/www/horas/English/SanctiM/08-15t.txt
web/www/horas/Latin/Sancti/08-15.txt
web/www/horas/Latin/Sancti/08-15t.txt
web/www/horas/Latin/SanctiM/08-15.txt
web/www/horas/Latin/SanctiM/08-15t.txt
web/www/horas/Polski/SanctiM/08-15t.txt

MONASTIC: 08-15

---

web/www/horas/Latin/Psalterium/Special/Major Special.txt

Close issue #4358

---

web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specmatins.pl
web/cgi-bin/horas/webdia.pl
web/www/horas/Latin/Regula/OrdoPraedicatorum.txt
web/www/horas/Ordinarium/Prima.txt

OP: Prima update + tidy

---

web/www/horas/Ordinarium/Prima.txt

Proper solution for #4366"

---

web/cgi-bin/horas/specials.pl
web/www/horas/Bohemice/Commune/C2.txt
web/www/horas/Bohemice/Commune/C2a.txt
web/www/horas/Bohemice/Commune/C3.txt
web/www/horas/Bohemice/Commune/C4.txt
web/www/horas/Bohemice/Commune/C4a.txt
web/www/horas/Bohemice/Commune/C5-1.txt
web/www/horas/Bohemice/Commune/C5.txt
web/www/horas/Bohemice/Commune/C5b.txt
web/www/horas/Bohemice/Sancti/01-14.txt
web/www/horas/Bohemice/Sancti/01-16.txt
web/www/horas/Bohemice/Sancti/01-25.txt
web/www/horas/Bohemice/Sancti/01-27.txt
web/www/horas/Bohemice/Sancti/01-29.txt
web/www/horas/Bohemice/Sancti/02-27.txt
web/www/horas/Bohemice/Sancti/03-19.txt
web/www/horas/Bohemice/Sancti/03-24.txt
web/www/horas/Bohemice/Sancti/09-08.txt
web/www/horas/Bohemice/Sancti/12-28.txt
web/www/horas/Bohemice/Sancti/12-29.txt

After the last big PL, there were several things that needed to be corrected in Czech language files:
- unified Collects where the only difference was a different translation
- a Dutch Collect translated to Czech
- added `[Name] Ant=` where needed
`sub replaceNdot` in `specials.pl` was expanded to work for Czech

Czech: corrections of new texts in last PL

---

web/www/horas/Latin/Sancti/07-29.txt
web/www/horas/Latin/SanctiM/11-09.txt

07-29 M/11-09 minor fixes

---

web/www/horas/Latin/Commune/C3a-1.txt
web/www/horas/Latin/Commune/C5.txt
web/www/horas/Latin/Sancti/02-24.txt

Restore a a few accents that were lost in the merge of horas and missa Orations.

Restore lost accents.

---

web/www/missa/Latin/Tempora/Quad6-0.txt
web/www/missa/Nederlands/Tempora/Quad6-0.txt
web/www/missa/Portugues/Tempora/Quad6-0.txt

fix: #4404

---

web/cgi-bin/horas/specials/capitulis.pl
web/www/horas/Latin/Sancti/01-01.txt
web/www/horas/Latin/SanctiM/01-01.txt
web/www/horas/Latin/SanctiM/01-13.txt
web/www/horas/Latin/Tempora/Nat1-0.txt
web/www/horas/Latin/TemporaM/Nat2-0r.txt
web/www/horas/Latin/TemporaOP/Quad5-0.txt
web/www/horas/Latin/TemporaOP/Quad6-0.txt

code: simplification in monastic_major_responsory for 'Responsory Vespera 1'

---

web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/specials/orationes.pl
web/www/horas/Latin/Tempora/Quad6-0.txt
web/www/horas/Latin/Tempora/Quad6-1.txt
web/www/horas/Latin/Tempora/Quad6-2.txt
web/www/horas/Latin/Tempora/Quad6-3.txt

for [#4384](https://github.com/DivinumOfficium/divinum-officium/issues/4384) ( [@Augustinus-Altovadensis](https://github.com/Augustinus-Altovadensis) please have an eye on the Sunday commemorations; I think this should improve the issues arising but who knows...)
for #4394 Resolving the actual issue on Vespers commemorations in Holy Week and Pentecost Octave

For #4384 and #4394

---

web/cgi-bin/horas/specials/capitulis.pl
web/www/horas/Latin/TemporaM/Nat2-0r.txt

follow up discussion to 3af6204

---

web/cgi-bin/horas/specials/orationes.pl
web/www/horas/Latin/Tempora/Pasc6-1.txt
web/www/horas/Latin/TemporaM/Pasc6-1.txt

Solve #4401

---

web/www/horas/Latin/Psalterium/Special/Matutinum Special.txt

1955: Invit in Passiontide

---

web/www/horas/Latin/Psalterium/Special/Matutinum Special.txt

Reverts DivinumOfficium/divinum-officium#4417

Revert "1955: Invit in Passiontide"

---

web/cgi-bin/horas/horasscripts.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/Latin-Bea/Psalterium/Special/Matutinum Special.txt

- Latin-Bea: Invit in Passiontide
- code: option 'Pius XII psalter' changes Latin to Latin-Bea
+AMDG+

Follow comment at #4417

---

web/www/horas/Latin/Psalterium/Psalmorum/Psalm1.txt
web/www/horas/Latin/Psalterium/Psalmorum/Psalm118.txt
web/www/horas/Latin/Psalterium/Psalmorum/Psalm17.txt
web/www/horas/Latin/Psalterium/Psalmorum/Psalm216.txt
web/www/horas/Latin/Psalterium/Psalmorum/Psalm90.txt

Just removing some pesky double spaces.

Remove double spaces

---

web/cgi-bin/horas/horascommon.pl

Commemorations got wrongly suppressed

Fixing Vespera Commemorations (Trid/DA): April 26 2025

---

web/www/missa/Latin/Ordo/Prefationes.txt
web/www/missa/Nederlands/Ordo/Prefationes.txt

Reverts DivinumOfficium/divinum-officium#4433

Revert "Sabbato → Sábbato, etc."

---

web/cgi-bin/horas/horascommon.pl
web/www/Tabulae/Kalendaria/M1617.txt
web/www/horas/English/SanctiM/07-01t.txt
web/www/horas/English/SanctiM/07-06.txt
web/www/horas/English/TemporaM/Pasc2-3.txt
web/www/horas/Latin/Sancti/07-01.txt
web/www/horas/Latin/Sancti/07-06.txt
web/www/horas/Latin/SanctiM/06-25oct.txt
web/www/horas/Latin/SanctiM/06-26oct.txt
web/www/horas/Latin/SanctiM/06-27oct.txt
web/www/horas/Latin/SanctiM/06-28oct.txt
web/www/horas/Latin/SanctiM/07-01.txt
web/www/horas/Latin/SanctiM/07-01t.txt
web/www/horas/Latin/SanctiM/07-02.txt
web/www/horas/Latin/SanctiM/07-03oct.txt
web/www/horas/Latin/SanctiM/07-04oct.txt
web/www/horas/Latin/SanctiM/07-05oct.txt
web/www/horas/Latin/SanctiM/07-06.txt
web/www/horas/Latin/SanctiM/07-11M.txt
web/www/horas/Latin/SanctiM/07-13Moct.txt
web/www/horas/Latin/SanctiM/07-15Moct.txt
web/www/horas/Latin/SanctiM/07-16.txt
web/www/horas/Latin/SanctiM/07-17Moct.txt
web/www/horas/Latin/SanctiM/07-18M.txt

MONASTIC: update 8va days in June & July

---

web/cgi-bin/horas/specmatins.pl
web/www/horas/Latin/Sancti/09-20.txt

fix Matutinum on 09-20 & Nat1-0

---

web/cgi-bin/horas/specmatins.pl

code: refactor around Versum in Matutinum of 3 readings

---

web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specials/hymni.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/Bohemice/Tempora/Pasc5-4.txt
web/www/horas/Deutsch/Tempora/Pasc5-4.txt
web/www/horas/English/Tempora/Pasc5-4.txt
web/www/horas/Espanol/Tempora/Pasc5-4.txt
web/www/horas/Francais/Tempora/Pasc5-4.txt
web/www/horas/Italiano/Tempora/Pasc5-4.txt
web/www/horas/Latin/Tempora/Pasc5-4.txt
web/www/horas/Latin/TemporaOP/Pasc2-5.txt
web/www/horas/Latin/TemporaOP/Pasc2-6.txt
web/www/horas/Latin/TemporaOP/Pasc3-1.txt
web/www/horas/Latin/TemporaOP/Pasc3-2.txt
web/www/horas/Latin/TemporaOP/Pasc3-4.txt
web/www/horas/Latin/TemporaOP/Pasc3-5.txt
web/www/horas/Latin/TemporaOP/Pasc5-0.txt
web/www/horas/Latin/TemporaOP/Pasc5-1.txt
web/www/horas/Latin/TemporaOP/Pasc5-2.txt
web/www/horas/Latin/TemporaOP/Pasc5-3.txt
web/www/horas/Latin/TemporaOP/Pasc5-4.txt
web/www/horas/Latin/TemporaOP/Pasc5-5.txt
web/www/horas/Latin/TemporaOP/Pasc5-6.txt
web/www/horas/Latin/TemporaOP/Pasc6-0.txt
web/www/horas/Latin/TemporaOP/Pasc6-1.txt
web/www/horas/Latin/TemporaOP/Pasc6-2.txt
web/www/horas/Latin/TemporaOP/Pasc6-3.txt
web/www/horas/Latin/TemporaOP/Pasc6-4.txt
web/www/horas/Latin/TemporaOP/Pasc6-5.txt
web/www/horas/Polski/Tempora/Pasc5-4.txt

+ spell correction in OP Pasc2 & Pasc3
+ necessary code & data changes
+AMDG+

OP: Pasc5 & Pasc6

---

web/cgi-bin/horas/monastic.pl

code: LectioE omit line breaks

---

web/www/horas/Bohemice/Psalterium/Psalmorum/Psalm133.txt
web/www/horas/Dansk/Psalterium/Psalmorum/Psalm133.txt
web/www/horas/Dansk/Psalterium/Psalmorum/Psalm90.txt
web/www/horas/Deutsch/Psalterium/Psalmorum/Psalm118.txt
web/www/horas/Deutsch/Psalterium/Psalmorum/Psalm133.txt
web/www/horas/Deutsch/Psalterium/Psalmorum/Psalm90.txt
web/www/horas/English/Psalterium/Psalmorum/Psalm133.txt
web/www/horas/English/Psalterium/Psalmorum/Psalm90.txt
web/www/horas/Espanol/Psalterium/Psalmorum/Psalm133.txt
web/www/horas/Espanol/Psalterium/Psalmorum/Psalm90.txt
web/www/horas/Francais/Psalterium/Psalmorum/Psalm133.txt
web/www/horas/Francais/Psalterium/Psalmorum/Psalm90.txt
web/www/horas/Italiano/Psalterium/Psalmorum/Psalm133.txt
web/www/horas/Italiano/Psalterium/Psalmorum/Psalm90.txt
web/www/horas/Latin-Bea/Psalterium/Psalmorum/Psalm118.txt
web/www/horas/Latin-Bea/Psalterium/Psalmorum/Psalm133.txt
web/www/horas/Latin-Bea/Psalterium/Psalmorum/Psalm90.txt
web/www/horas/Latin/Psalterium/Psalmorum/Psalm133.txt
web/www/horas/Latin/Psalterium/Psalmorum/Psalm90.txt
web/www/horas/Magyar/Psalterium/Psalmorum/Psalm133.txt
web/www/horas/Magyar/Psalterium/Psalmorum/Psalm90.txt
web/www/horas/Nederlands/Psalterium/Psalmorum/Psalm133.txt
web/www/horas/Nederlands/Psalterium/Psalmorum/Psalm90.txt
web/www/horas/Polski-Newer/Psalterium/Psalmorum/Psalm133.txt
web/www/horas/Polski-Newer/Psalterium/Psalmorum/Psalm90.txt
web/www/horas/Polski/Psalterium/Psalmorum/Psalm133.txt
web/www/horas/Polski/Psalterium/Psalmorum/Psalm90.txt
web/www/horas/Portugues/Psalterium/Psalmorum/Psalm133.txt
web/www/horas/Portugues/Psalterium/Psalmorum/Psalm90.txt

continuing what started with PRs #3925 #4093 and #4168

Psalms: 90, 118, 133

---

web/cgi-bin/horas/specials/hymni.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/Bohemice/Tempora/Pasc7-1.txt
web/www/horas/Bohemice/Tempora/Pasc7-2.txt
web/www/horas/Bohemice/Tempora/Pasc7-3.txt
web/www/horas/Bohemice/Tempora/Pasc7-4.txt
web/www/horas/Latin/Psalterium/Doxologies.txt
web/www/horas/Latin/Psalterium/Special/Minor Special.txt
web/www/horas/Latin/Tempora/Pasc6-6.txt
web/www/horas/Latin/Tempora/Pasc7-1.txt
web/www/horas/Latin/Tempora/Pasc7-2.txt
web/www/horas/Latin/Tempora/Pasc7-3.txt
web/www/horas/Latin/Tempora/Pasc7-4.txt
web/www/horas/Latin/Tempora/Pasc7-5.txt
web/www/horas/Latin/TemporaOP/Pasc5-4.txt
web/www/horas/Latin/TemporaOP/Pasc5-5.txt
web/www/horas/Latin/TemporaOP/Pasc6-3.txt
web/www/horas/Latin/TemporaOP/Pasc7-0.txt
web/www/horas/Latin/TemporaOP/Pasc7-1.txt
web/www/horas/Latin/TemporaOP/Pasc7-2.txt
web/www/horas/Latin/TemporaOP/Pasc7-3.txt
web/www/horas/Latin/TemporaOP/Pasc7-4.txt
web/www/horas/Latin/TemporaOP/Pasc7-5.txt
web/www/horas/Latin/TemporaOP/Pasc7-6.txt

OP: Pasc6-6 & Pasc7

---

web/cgi-bin/horas/specmatins.pl

fixing Absolutio (error introduced by #4505)
close #4511

Fixing #4511

---

web/www/horas/Bohemice/Commune/C4.txt
web/www/horas/Bohemice/CommuneM/C4.txt
web/www/horas/Bohemice/CommuneM/C5.txt
web/www/horas/Latin/CommuneM/C4.txt
web/www/horas/Latin/CommuneM/C5.txt

Cistercian version. In Matutinum: 
- Commune Confessoris Pontificis extra T.P. was added 
- Czech version added

Cist. Matutinum: Commune Conf. Pont. extra T.P. + Czech

---

web/www/horas/English/SanctiM/06-11.txt
web/www/horas/Latin/SanctiM/06-11.txt

MONASTIC: 06-11 update

---

web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specials/capitulis.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/Latin/SanctiM/03-25.txt
web/www/horas/Latin/SanctiM/12-08o.txt

Following discussion #4526
- Ensuring single Antiphone for Monastic
- Ensuring correct antiphone for transferred Annunciation T.P. (e.g. 2024)
- Ensuring Alleuja at end of Versicles for Monastic and Roman

Fixing Eastertide Matutinum

---

web/www/horas/Bohemice/Commune/C11.txt
web/www/horas/Bohemice/Commune/C2p.txt
web/www/horas/Bohemice/Commune/C6.txt
web/www/horas/Bohemice/Commune/C6a.txt
web/www/horas/Bohemice/Commune/C7.txt
web/www/horas/Bohemice/CommuneM/C6.txt
web/www/horas/Bohemice/CommuneM/C7.txt
web/www/horas/Bohemice/Psalterium/Psalmorum/Psalm249.txt
web/www/horas/Bohemice/Psalterium/Psalmorum/Psalm250.txt
web/www/horas/Bohemice/Psalterium/Psalmorum/Psalm251.txt
web/www/horas/Bohemice/SanctiM/04-05C.txt
web/www/horas/Bohemice/SanctiM/10-21C.txt
web/www/horas/Latin/Commune/C6.txt
web/www/horas/Latin/Commune/C6a.txt
web/www/horas/Latin/Commune/C7.txt
web/www/horas/Latin/CommuneM/C6.txt
web/www/horas/Latin/CommuneM/C6a.txt
web/www/horas/Latin/CommuneM/C7.txt
web/www/horas/Latin/SanctiM/04-05C.txt

Added to Cistercian version in Matins:
- Commune Virginum
- Commune non Virginum
- Czech translation

Cist: Commune Sanctarum Feminarum + Czech

---

web/www/horas/Latin/TemporaM/Pent02-0r.txt

MONASTIC 1963: fix readings in Pent02-0 once again

---

web/www/horas/Latin/SanctiM/06-25.txt

MONASTIC 1617 - 12 readings: 06-25

---

web/www/horas/Latin/SanctiM/06-25.txt

MONASTIC: 06-25 fix cistercian

---

web/cgi-bin/horas/horascommon.pl
web/www/horas/Bohemice/SanctiM/06-26.txt
web/www/horas/Latin/Tempora/Pent02-4.txt
web/www/horas/Latin/TemporaM/Pent02-3.txt

Small corrections for this week

Cist: small corrections

---

web/cgi-bin/DivinumOfficium/dialogcommon.pl

code: allow parameters have 'false' values as '0' etc.

---

web/www/Tabulae/Kalendaria/M1617.txt
web/www/Tabulae/Kalendaria/M1930.txt
web/www/horas/Latin/Sancti/01-15cc.txt
web/www/horas/Latin/SanctiM/01-15cc.txt
web/www/horas/Latin/SanctiM/01-15t.txt

MONASTIC 1617 & 1930: Feast of St. Mauri

---

web/www/horas/Latin/Sancti/01-15cc.txt
web/www/horas/Latin/Sancti/10-04.txt
web/www/horas/Latin/Sancti/10-05.txt
web/www/horas/Latin/SanctiM/01-15cc.txt
web/www/horas/Latin/SanctiM/01-15t.txt

cf. Duæ Tabellæ Ex Superioribus Rubricis Excerptæ (M1617 pdf p. 47)

M1617: Rank of S. Mauri / Ss. Placidi et soc. / S. Francisi

---

web/cgi-bin/horas/specials/psalmi.pl

code: fix minor ants on feasts in 1963

---

web/cgi-bin/horas/monastic.pl

code: add 'Lectio unica' header in monastic

---

web/www/horas/Latin/SanctiM/11-01.txt

MONASTIC: fix All Saints Day

---

web/www/horas/Latin/CommuneM/C10.txt

MONASTIC: update sources of C10 readings

---

web/www/horas/Latin/Sancti/08-16bmv.txt
web/www/horas/Latin/Sancti/08-17t.txt
web/www/horas/Latin/Sancti/08-18bmv.txt
web/www/horas/Latin/Sancti/08-19bmv.txt
web/www/horas/Latin/Sancti/08-21bmv.txt
web/www/horas/Latin/Sancti/08-22t.txt
web/www/horas/Latin/SanctiM/08-15t.txt
web/www/horas/Latin/SanctiM/08-16bmv.txt
web/www/horas/Latin/SanctiM/08-17bmv.txt
web/www/horas/Latin/SanctiM/08-18bmv.txt
web/www/horas/Latin/SanctiM/08-19bmv.txt
web/www/horas/Latin/SanctiM/08-21bmv.txt
web/www/horas/Latin/SanctiM/08-22t.txt

- update 1570
- add M1617 M1930
+AMDG+

Octava Assumpionis BMV

---

web/www/horas/English/Sancti/08-18bmv.txt
web/www/horas/English/SanctiM/08-22t.txt
web/www/horas/Espanol/Sancti/08-18bmv.txt
web/www/horas/Francais/Sancti/08-18bmv.txt
web/www/horas/Italiano/Sancti/08-18bmv.txt
web/www/horas/Latin/SanctiM/08-22t.txt

fix Octava Assumpionis BMV + vernaculars

---

web/www/horas/Bohemice/Tempora/Pent04-0.txt
web/www/horas/Bohemice/Tempora/Pent06-0.txt
web/www/horas/English/Tempora/Pent04-0.txt
web/www/horas/English/Tempora/Pent06-0.txt
web/www/horas/Espanol/Tempora/Pent04-0.txt
web/www/horas/Espanol/Tempora/Pent06-0.txt
web/www/horas/Francais/Tempora/Pent04-0.txt
web/www/horas/Francais/Tempora/Pent06-0.txt
web/www/horas/Italiano/Tempora/Pent04-0.txt
web/www/horas/Italiano/Tempora/Pent06-0.txt
web/www/horas/Latin/Psalterium/Special/Minor Special.txt
web/www/horas/Latin/Tempora/Pent04-0.txt
web/www/horas/Latin/Tempora/Pent06-0.txt
web/www/horas/Latin/TemporaOP/Pent06-0.txt
web/www/horas/Latin/TemporaOP/Pent06-1.txt
web/www/horas/Latin/TemporaOP/Pent06-2.txt
web/www/horas/Latin/TemporaOP/Pent06-3.txt
web/www/horas/Latin/TemporaOP/Pent06-4.txt
web/www/horas/Latin/TemporaOP/Pent06-5.txt
web/www/horas/Latin/TemporaOP/Pent06-6.txt
web/www/horas/Latin/TemporaOP/Quad6-0.txt
web/www/horas/Polski/Tempora/Pent04-0.txt
web/www/horas/Polski/Tempora/Pent06-0.txt

OP: Pent06 + Quad update

---

web/www/horas/Latin/SanctiM/07-22.txt
web/www/horas/Latin/SanctiM/08-29.txt

MONASTIC 1617 & 1930: 12 readings for S. Maria Magdalena & Decollatio S. Joannis Baptiste

---

web/cgi-bin/horas/monastic.pl
web/www/horas/English/SanctiM/09-12.txt
web/www/horas/English/SanctiM/09-15t.txt
web/www/horas/Latin/CommuneM/C11.txt
web/www/horas/Latin/Psalterium/Special/Matutinum Special.txt
web/www/horas/Latin/Sancti/09-15t.txt
web/www/horas/Latin/SanctiM/09-09bmv.txt
web/www/horas/Latin/SanctiM/09-11bmv.txt
web/www/horas/Latin/SanctiM/09-12.txt
web/www/horas/Latin/SanctiM/09-12bmv.txt
web/www/horas/Latin/SanctiM/09-13bmv.txt
web/www/horas/Latin/SanctiM/09-15t.txt
web/www/horas/Polski/SanctiM/09-15t.txt

- capitalize after star in responsory after Lectio brevis
- update C11:Responsory7
- code: use 'Ant Matutinum 3N' also from Commune
- 1930: 12 readings for S. Nominis BMV
- 1617: Matutinum in octavam Nativitatis BMV
+ 1570: 09-15t fix readings 4-6
+AMDG+

MONASTIC: update + 1570/09-15t

---

web/cgi-bin/DivinumOfficium/SetupString.pl
web/www/horas/Latin/Commune/C10.txt
web/www/horas/Latin/CommuneM/C10.txt

code: new condition 'mense' + M1617: 3 readings in summers Saturdays of BMV

---

web/www/horas/Latin/Sancti/08-04.txt

1963: 08-04 psalmi feriales

---

web/www/horas/English/SanctiM/04-21.txt
web/www/horas/English/SanctiM/11-21.txt
web/www/horas/Latin/SanctiM/04-21.txt
web/www/horas/Latin/SanctiM/11-21.txt
web/www/horas/Latin/SanctiM/12-07.txt

- In Præsentatione B.M.V. (1617 & 1930)
- S. Ambrosii (1617)
- S. Anselmi (1930)
@FAJ-Munich this should complete '12 lectiones' in 1930, please check if we can remove disclaimer from top of page.
+AMDG+

OLD MONASTIC: 12 lectiones

---

web/www/horas/Bohemice/Tempora/Pent12-0.txt
web/www/horas/English/Tempora/Pent12-0.txt
web/www/horas/Espanol/Tempora/Pent12-0.txt
web/www/horas/Francais/Tempora/Pent12-0.txt
web/www/horas/Italiano/Tempora/Pent12-0.txt
web/www/horas/Latin/Tempora/Pent12-0.txt
web/www/horas/Latin/TemporaOP/085-0.txt
web/www/horas/Latin/TemporaOP/085-1.txt
web/www/horas/Latin/TemporaOP/085-2.txt
web/www/horas/Latin/TemporaOP/085-3.txt
web/www/horas/Latin/TemporaOP/085-4.txt
web/www/horas/Latin/TemporaOP/085-5.txt
web/www/horas/Latin/TemporaOP/085-6.txt
web/www/horas/Latin/TemporaOP/Pent12-0.txt
web/www/horas/Nederlands/Tempora/Pent12-0.txt
web/www/horas/Polski/Tempora/Pent12-0.txt

OP: Pent12 & 085

---

web/www/horas/Bohemice/Tempora/Pent13-0.txt
web/www/horas/Deutsch/Tempora/Pent13-0.txt
web/www/horas/English/Tempora/Pent13-0.txt
web/www/horas/Espanol/Tempora/Pent13-0.txt
web/www/horas/Francais/Tempora/Pent13-0.txt
web/www/horas/Italiano/Tempora/Pent13-0.txt
web/www/horas/Latin/Tempora/Pent13-0.txt
web/www/horas/Latin/TemporaOP/091-0.txt
web/www/horas/Latin/TemporaOP/091-1.txt
web/www/horas/Latin/TemporaOP/091-2.txt
web/www/horas/Latin/TemporaOP/091-3.txt
web/www/horas/Latin/TemporaOP/091-4.txt
web/www/horas/Latin/TemporaOP/091-5.txt
web/www/horas/Latin/TemporaOP/091-6.txt
web/www/horas/Nederlands/Tempora/Pent13-0.txt
web/www/horas/Polski/Tempora/Pent13-0.txt

OP: Pent13 & 091

---

web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/specials/orationes.pl

Trid: Fixing tonight's Vespers commemoration

---

web/www/horas/Bohemice/Tempora/093-3.txt
web/www/horas/Bohemice/Tempora/093-5.txt
web/www/horas/Deutsch/Psalterium/Special/Major Special.txt
web/www/horas/English/Tempora/093-3.txt
web/www/horas/English/Tempora/093-5.txt
web/www/horas/Espanol/Tempora/093-3.txt
web/www/horas/Espanol/Tempora/093-5.txt
web/www/horas/Francais/Tempora/093-3.txt
web/www/horas/Francais/Tempora/093-5.txt
web/www/horas/Italiano/Tempora/093-3.txt
web/www/horas/Italiano/Tempora/093-5.txt
web/www/horas/Latin/Tempora/093-3.txt
web/www/horas/Latin/Tempora/093-5.txt
web/www/horas/Nederlands/Psalterium/Special/Major Special.txt
web/www/horas/Ordinarium/Prima.txt
web/www/horas/Polski/Tempora/093-3.txt
web/www/horas/Polski/Tempora/093-5.txt

close #4727 stemming from quick fix to #793

Fix Embertide and Prima

---

web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/officium_html.pl
web/cgi-bin/horas/webdia.pl
web/cgi-bin/missa/missa.pl

code: allow output only content without html-head menus etc. with `content` param (fixed)

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/webdia.pl
web/cgi-bin/missa/missa.pl
web/cgi-bin/missa/ordo.pl

- ignore content param if no pray command given
- prevent empty cells in missa (eg. on top),
- add h2 header to missa when content only,
- omit Ante & Post when content only
- remove unnecesary variable in &horas
+AMDG+

code update:

---

web/cgi-bin/horas/specials/capitulis.pl
web/www/horas/Bohemice/Sancti/01-06.txt
web/www/horas/Bohemice/SanctiM/01-06.txt
web/www/horas/Bohemice/Tempora/Pasc7-0.txt
web/www/horas/Bohemice/TemporaM/Pasc7-0.txt
web/www/horas/Latin/Sancti/01-06.txt
web/www/horas/Latin/SanctiM/01-01.txt
web/www/horas/Latin/SanctiM/01-06.txt
web/www/horas/Latin/SanctiM/02-10.txt
web/www/horas/Latin/SanctiM/03-19.txt
web/www/horas/Latin/SanctiM/03-21.txt
web/www/horas/Latin/SanctiM/03-25.txt
web/www/horas/Latin/SanctiM/05-01b.txt
web/www/horas/Latin/SanctiM/06-24.txt
web/www/horas/Latin/SanctiM/06-29.txt
web/www/horas/Latin/SanctiM/07-11b.txt
web/www/horas/Latin/SanctiM/08-15.txt
web/www/horas/Latin/SanctiM/09-08.txt
web/www/horas/Latin/SanctiM/09-29.txt
web/www/horas/Latin/SanctiM/10-13b.txt
web/www/horas/Latin/SanctiM/10-DU.txt
web/www/horas/Latin/SanctiM/11-01.txt
web/www/horas/Latin/SanctiM/12-08.txt
web/www/horas/Latin/SanctiM/12-25.txt
web/www/horas/Latin/Tempora/Pasc7-0.txt
web/www/horas/Latin/TemporaM/Pasc5-4.txt
web/www/horas/Latin/TemporaM/Pasc7-0.txt
web/www/horas/Latin/TemporaM/Pent01-0.txt
web/www/horas/Latin/TemporaM/Pent01-4.txt

Barroux: responsories prolix
