DivinumOfficium/divinum-officium

web/www/horas/English/Ordinarium/Prima.txt, web/www/horas/English/Ordinarium/Prima1960.txt, web/www/horas/English/Ordinarium/Primap.txt, web/www/horas/English/Ordinarium/Primap1960.txt
It was pointed out to me that the English translation of prime is translating "opera tua" as "their works." I'm not sure if you have some reason for preferring that translation, but I've corrected it.
=> Correct translation of ordinary of prime

web/www/horas/English/Sancti/08-30.txt, web/www/horas/Latin/Sancti/03-19.txt, web/www/horas/Latin/Sancti/05-11r.txt, web/www/horas/Latin/Sancti/12-26.txt, web/www/horas/Latin/Tempora/Quad1-0.txt
Most of these are typos, and uncontroversial. One could differ about the following changes:
* Regarding Sancti/08-30.txt, one could phrase the title in different ways, but since there's only one companion martyr, the plural was definitely wrong. The companion's name is unknown, and so he is called in Latin "Adauctus," the one who was added.
* The change to Sancti/12-26.txt removes a [BOM](http://en.wikipedia.org/wiki/Byte_order_mark) from the beginning of the file. Without this, [Rank] was unrecognized. Since 4889a8a, this may no longer be necessary, but it was already part of my commit.
* I more recently did the opposite to Santi/05-11.txt, adding a BOM to the beginning: without the BOM this file is not recognized as UTF-8, and so the word "fœnum" in lectio 2 is garbled (see …
=> Typos and UTF-8 recognition problem

web/www/horas/English/Martyrologium/07-27.txt, web/www/horas/English/Tempora/Pent02-5.txt, web/www/horas/Italiano/Martyrologium/02-20.txt, web/www/horas/Italiano/Martyrologium/10-10.txt, web/www/horas/Italiano/Martyrologium/11-10.txt, web/www/horas/Italiano/Tempora/Quad3-6.txt, web/www/horas/Italiano/Tempora/Quad3-6t.txt, web/www/horas/Latin/Sancti/07-31.txt, web/www/horas/Latin/Sancti/08-02.txt, web/www/horas/Latin/Tempora/Pent03-1Feria.txt
These are almost all corrections to typos. One corrects a mistranslation of "De vite mystica." The only one that could be questioned is adding a BOM to Pent03-1Feria.txt: without this, the file is read as CP-1252, which mangles the word "Israel". Arguably, the code to identify UTF-8 files should be improved instead of patching a single file.
=> Recent corrections

web/www/horas/English/Tempora/Quad6-0.txt
Responsory 1 repeated as responsory 2. Replaced with correct responsory from English Breviary. This problem also found in the other versions of this file. 6-0r also has Jer. 2:18 as the last verse of lesson 1 and the first of lesson 2; the other two versions do not. Unsure if this is proper.
=> Missing Responsory Quad6-0

web/cgi-bin/missa/propers.pl, web/www/missa/Deutsch/Ordo/Ordo.txt, web/www/missa/English/Ordo/Ordo.txt, web/www/missa/Italiano/Ordo/Ordo.txt, web/www/missa/Latin/Ordo/Ordo.txt, web/www/missa/Magyar/Ordo/Ordo.txt, web/www/missa/Polski/Ordo/Ordo.txt
- propers.pl : removes "Dominus Vobiscum" (which is then added on Ordo.txt)
Why ? In order to have:
"""
Deinde sacerdos in cornu Evangelii, iunctis manibus dicit:
V. Dominus vobiscum.
R. Et cum spiritu tuo.
Et signans signo crucis primum Altare vel librum, deinde se in fronte, ore et pectore, dicit:
Initium ✠ sancti Evangélii secúndum Ioánnem.
R. Gloria tibi, Domine!
"""
and NOT the previous version:
"""
Deinde sacerdos in cornu Evangelii, iunctis manibus dicit:
Et signans signo crucis primum Altare vel librum, deinde se in fronte, ore et pectore, dicit:
V. Dominus vobiscum.
R. Et cum spiritu tuo.
Initium ✠ sancti Evangélii secúndum Ioánnem.
R. Gloria tibi, Domine!
"""
=> Improves the rubrics of the ordo (Ordo/Ordo.txt)

web/www/missa/Latin/Tempora/Quad6-2.txt, web/www/missa/Polski/Tempora/Quad1-5.txt, web/www/missa/Polski/Tempora/Quad6-1.txt, web/www/missa/Polski/Tempora/Quad6-2.txt, web/www/missa/Polski/Tempora/Quadp3-3.txt
I found a problem in Holy Tuesday's Passion. It's similar to one described in issue #394. After 1955 changes, Passion starts with verse Marc 14:32, while Divinum Officum shows it from 14:1.
I made a fix to Latin and Polish propers. If this solution is accepted I can fix other languages.
=> Polish - Mass - Adding Holy Monday, Holy Tuesday

web/cgi-bin/horas/dialogcommon.pl, web/www/missa/English/Tempora/Quad6-4.txt, web/www/missa/English/Tempora/Quad6-4r.txt, web/www/missa/English/Tempora/Quad6-4t.txt, web/www/missa/Latin/Tempora/Quad6-4.txt, web/www/missa/Latin/Tempora/Quad6-4r.txt, web/www/missa/Latin/Tempora/Quad6-4t.txt, web/www/missa/Polski/Ordo/Ordo.txt, web/www/missa/Polski/Sancti/01-03n.txt, web/www/missa/Polski/Sancti/02-02.txt, web/www/missa/Polski/Sancti/02-24.txt, web/www/missa/Polski/Sancti/12-21.txt, web/www/missa/Polski/Sancti/12-26.txt, web/www/missa/Polski/Sancti/12-28.txt, web/www/missa/Polski/Sancti/12-28o.txt, web/www/missa/Polski/Sancti/12-28r.txt, web/www/missa/Polski/Tempora/Adv1-0.txt, web/www/missa/Polski/Tempora/Adv3-3.txt, web/www/missa/Polski/Tempora/Epi1-0.txt, web/www/missa/Polski/Tempora/Nat1-0.txt, web/www/missa/Polski/Tempora/Nat2-0.txt, web/www/missa/Polski/Tempora/Quad3-0.txt, web/www/missa/Polski/Tempora/Quad5-0.txt, web/www/missa/Polski/Tempora/Quad5-0t.txt, web/www/missa/Polski/Tempora/Quad6-0.txt, web/www/missa/Polski/Tempora/Quad6-1.txt, web/www/missa/Polski/Tempora/Quad6-4r.txt, web/www/missa/Polski/Tempora/Quadp3-3.txt
When doing Polish translation of Maundy Thursday I found two issues existing in original texts:
1. `Tempora/Quad6-4*.txt` – references in antifons involved in the ceremony of washing feet were incorrect. The reference was always **Ps** while it should be **Joann** (in most cases) and **1 Cor** (in one case). The verses' numbers were correct, though.
2. `Tempora/Quad6-4r.txt` - Maundy Thursday has its own `Communicantes` which does not take into account the change added by John XXIII – mention of st. Joseph. I added this mention as conditional `(rubrica 1960 dicitur)`.
I fixed mentioned issues in Latin and English language versions. I'll leave other languages to the respective authors.
=> Polish - Mass - Adding Maundy Thursday

web/www/horas/Latin/Tabulae/Tr1960.txt, web/www/horas/Latin/Tempora/Quad6-4r.txt, web/www/horas/Latin/Tempora/Quad6-5r.txt, web/www/horas/Latin/Tempora/Quad6-6r.txt
Removing these files results in lack of Polish Mass translation for Maundy Thursday, Good Friday and Easter Vigil. Perhaps Polish files for the Mass can be adjusted to allow deletion of files in question but I'd defer it for time after Easter.
http://divinumofficium.com/cgi-bin/missa/missa.pl?lang2=Polski&Propers=1&date=3-24-2016
http://divinumofficium.com/cgi-bin/missa/missa.pl?lang2=Polski&Propers=1&date=3-25-2016
http://divinumofficium.com/cgi-bin/missa/missa.pl?lang2=Polski&Propers=1&date=3-26-2016
=> Reverting commit 5a9dc6b as it causes problems in Mass part

web/index.html
Since the index isn’t affected by the scripts, I’ve conservatively rewritten the html to be strict HTML 4.01. Visually, this should be largely identical with no noticeable differences. An ALT attribute was added to the picture, as required for this to be valid HTML.
=> Index.html from transitional to strict

web/www/horas/Latin/Psalterium/Psalmi matutinum.txt
Currently the Saturday Matins in our Trient modes are broken: Ps. 97 98 91 100 101 102 are shown, whereas it should be 97-108. Visible e.g. on 18 June and 9 July 2016.
I don't know if this fixes the whole problem (with only 6 psalms being shown, even though the code at the moment already provides for 12), but it will at least take out the wrong 91.
=> Fix Saturday pre-Pius

web/www/horas/Latin/Sancti/08-15.txt
The attempt of @mbab to replace it with Reponsory 6 of C11 left a spurious asterisk
before the first "Unguentum", thus:
> R. Ornatam monilibus filiam Ierusalem Dominus concupivit:
> \* Et videntes eam filiae Sion, beatissimam praedicaverunt, dicentes: * Unguentum effusum nomen tuum.
> V. Astitit regina a dextris tuis in vestitu deaurato, circumdata varietate.
> R. Et videntes eam filiae Sion, beatissimam praedicaverunt, dicentes: Unguentum effusum nomen tuum.
This commit reverts the change. It may be that a more clever substitution could eliminate the spurious asterisk. That would also be acceptable to me.
=> Restore Responsory4 of Latin/Sancti/08-15.txt

web/cgi-bin/horas/horascommon.pl, web/www/horas/Latin/Sancti/04-22.txt, web/www/horas/Latin/Sancti/04-26.txt
Commit 4b35e71 converted all occurrences of "ae" in the Latin Sancti files to the æ ligature. But:
1. "hæc versus ommittuntur" is not recognized as a valid conditional: this PR changes horascommon.pl to recognize it, also allowing "haec" to be used.
2. OPapæM is not recognized as a rule. This PR restores the spelling OPapaeM so that the rule will be recognized.
=> Fix rules affected by æ ligature substitution

standalone/tools/epubgen2/epubgen2.sh
By generating all hours of the same day simultaneously, it shoud be possible to benefit from multi-cores processors without loading too much older machines.
=> Parallel processing of hours of the same day

web/www/horas/English/Commune/C1p.txt, web/www/horas/English/Commune/C7.txt, web/www/horas/English/Commune/C7a.txt
The elimination of proper texts that are just duplicates of the common (and common texts that duplicate others) is causing the commons to be used more frequently. This in turn makes it more evident that they do not have a consistent style. These commits restore an alleluia that disappeared, and capitalize a word, but a more thorough review is needed.
@APMarcello3, I suggest you review the English commons for style. For example, should alleluia be capitalized or not? Should terms like "mother" and virgin" be capitalized?
In particular, take a look at `web/www/horas/English/Commune/C1p.txt`: ætérnitas tempórum is sometimes translated "the eternity of times" and other times "the eternity of *the* times."
=> English translation corrections

web/www/horas/Deutsch/psalms1/Psalm1.txt, web/www/horas/English/psalms1/Psalm1.txt, web/www/horas/Francais/psalms1/Psalm1.txt, web/www/horas/Italiano/psalms1/Psalm1.txt, web/www/horas/Latin/psalms1/Psalm1.txt, web/www/horas/Magyar/psalms1/Psalm1.txt, web/www/horas/Polski/psalms1/Psalm1.txt
This is the first patch updating numbering of verses in psalms. The proposal was presented in #838.
Psalm 1 is relatively simple, because there are no references to parts of it in `LANG/Psalterium/Psalmi minor.txt` or other files.
The changes are first manually applied to the Latin version, and then programmatically transferred to other languages with necessary validation. Encoding of files (including BOM) is preserved.
=> Renumbering of verses in Psalm 1

web/www/horas/English/Sancti/05-01r.txt, web/www/horas/Italiano/Sancti/05-01r.txt, web/www/horas/Latin/Sancti/02-09.txt, web/www/horas/Latin/Sancti/03-25.txt, web/www/horas/Latin/Sancti/04-28.txt, web/www/horas/Latin/Sancti/04-30.txt, web/www/horas/Latin/Sancti/05-01r.txt, web/www/horas/Latin/Tempora/Pasc0-5.txt, web/www/horas/Latin/Tempora/Quad6-5.txt, web/www/horas/Polski/Sancti/05-01r.txt
* Most of these commits correct typos.
* The Annunciation had lost the versicle at vespers. I've restored it with a reference.
* The new oratio for St. Joseph (1962 rubrics) had the wrong conclusion. I've corrected it for all languages.
As a rule, I check my corrections with the *editio typica.*
=> Corrections mostly to Latin

web/www/horas/Latin/PiusXII/Psalm109.txt, web/www/horas/Latin/PiusXII/Psalm110.txt, web/www/horas/Latin/PiusXII/Psalm111.txt, web/www/horas/Latin/PiusXII/Psalm112.txt, web/www/horas/Latin/PiusXII/Psalm113.txt
Related to #817
Psalterium Pianum not only changed "words", but also made significant shifts in structure of the psalms, in order to adjust verses as prayed in the Divine Office to the inner structure of the Hebrew text. Boundaries of divisions of the longer psalms prayed in parts were occasionally shifted, too. Strophes was marked in some psalms.
Currently the psalms are arranged in the traditional way, all the distinctive structural features mentioned above are thus lost. I propose switching to the "proper Psalterium Pianum arrangement", as printed in the liturgical books between 1945 and 1960'. This PR rearranges Psalms of Sunday Vespers. I am willing to proceed in a slow pace with the rest of the Psalter if the idea gets a "go" from project maintainers.
=> Psalterium Pianum: original verse divisions, strophes

web/cgi-bin/horas/horas.pl
escaped braces to fix Perl 5.32 error
>Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32)
=> escaped braces to fix Perl 5.32 error

web/www/horas/Latin/Commune/C1.txt, web/www/horas/Latin/Sancti/05-28.txt, web/www/horas/Latin/Sancti/10-18.txt, web/www/horas/Latin/Sancti/11-02.txt
* A typo in the `[Rank]` section of St. Augustine's office made it disappear from the calendar.
* The office of All Souls had a spurious *autem* and an *et* turned into *ut.*
=> Recent typos

web/cgi-bin/horas/dialogcommon.pl, web/cgi-bin/horas/horascommon.pl
I've implemented a fallback mechanism for #938 according to @fiapps suggestion ([link](https://github.com/DivinumOfficium/divinum-officium/issues/938#issuecomment-434046885)).
There is a bug, though. In some places the parameter `$lang` has `_` replaced with ` ` (a space), notably `mpopup.pl`. Owing to this fact, if I click the link to the `Communio` popup (while reading `Sancta Missa`), using the `Polski_New` language (without the proper translation of the communio among the files), I get English instead of Polish.
I see two ways of fixing this:
1. Change the separator to `-` (easy, but not elegant).
2. Remember to replace a space with and underscore where needed in `$lang` (at the moment I know only about `mpopup.pl`).
3. (best) Find a reason why `_` is encoded as space and fix it.
=> Multi fallback implementation (#938) - discussion needed

web/www/horas/English/Sancti/12-25.txt
The meter was off in the last stanza of the Vespers Hymn because it appears that the line break between the first and second lines was off by one word.
=> Fix line break in Vespers Hymn

Dockerfile
Fix #1126: 340 MB instead of 1.02 GB.
=> Use slim perl docker image

README.md
The old links were only accessible to the docker-hub repo admin.
These new ones are proper public links to the image.
=> Update Docker Badge links to public ones

web/www/horas/Portugues/psalms1/Psalm13.txt, web/www/horas/Portugues/psalms1/Psalm14.txt, web/www/horas/Portugues/psalms1/Psalm15.txt, web/www/horas/Portugues/psalms1/Psalm16.txt, web/www/horas/Portugues/psalms1/Psalm17.txt, web/www/horas/Portugues/psalms1/Psalm18.txt, web/www/horas/Portugues/psalms1/Psalm19.txt, web/www/horas/Portugues/psalms1/Psalm20.txt, web/www/horas/Portugues/psalms1/Psalm21.txt
The extra spaces prevented the verses from being recognized.
=> Fix verse numbers in Portuguese Psalms.

web/www/horas/Espanol/Ordinarium/Sexta.txt, web/www/horas/Espanol/Ordinarium/Sexta1960.txt, web/www/horas/Espanol/Ordinarium/SextaM.txt
The Spanish translation of Sext produced an error with the 1960 rubrics because `Sext.txt` existed in the `Ordinarium` directory, but `Sext1960.txt` did not. The missing file has been created by copying `Sext.txt` and deleting the prayers that are no longer said with the 1960 rubrics.
The other commit fixes the code for a large capital at the beginning of the hymn for Sext.
=> Corrections to Spanish translation of Sext

web/www/horas/Magyar/Sancti/05-08.txt
Typos in hymn in First Vespers for Feast of St. Michael the Archangel
=> Typos in First Vespers

web/cgi-bin/horas/horas.pl
Error would occur when trying to generate an epub with Divino Afflatu rubrics. The issue was that ante_post was an undefined subroutine at horas.pl. As Perl is not my go-to language, I am sure that there is a better fix than the one that I proposed.
=> Fix horas.pl for epub generation

web/www/missa/English/Tempora/Quad6-5r.txt
Change "too" to "to"
Remove b. from "Bend thy boughs
Remove incorrect "us"
=> Typos Good Friday

web/www/horas/Espanol/Ordinarium/Completorium.txt, web/www/horas/Espanol/Ordinarium/Completorium1960.txt
www/cgi-bin/horas/specials.pl line 233 searches for R.br., but does not consider that it might not exist:
```Perl
while ($t[$tind] !~ /^\s*R\.br\./) { push(@s, $t[$tind++]); }
```
The Spanish compline files had "R. brev." instead of "R.br", so `$tind` kept growing without limit, far past the end of the array. Eventually the server kills the Perl process, and the user gets an error (see #1620).
This PR fixes the compline files, but it would be good to fix the Perl as well. I don't do it myself because I don't have time to work out the logic. If the code is changed, what should it do if it does not find "R.br."?
=> Fix error in Español compline that caused infinite loop.

web/www/missa/French/Sancti/05-24pl.txt, web/www/missa/Latin/Sancti/05-24pl.txt, web/www/missa/Polski/Commune/C10Pasc.txt, web/www/missa/Polski/Commune/C10c.txt, web/www/missa/Polski/Commune/C10t.txt, web/www/missa/Polski/Sancti/03-25.txt, web/www/missa/Polski/Sancti/05-24pl.txt, web/www/missa/Polski/Sancti/08-05.txt, web/www/missa/Polski/Sancti/08-22r.txt, web/www/missa/Polski/Sancti/09-12.txt, web/www/missa/Polski/Sancti/09-15.txt, web/www/missa/Polski/Sancti/09-24.txt, web/www/missa/Polski/Sancti/11-21.txt, web/www/missa/Polski/Tempora/Adv3-3.txt
After the changes from ticket "C10 files are taken from Tempora dir #500" (a96954f83aec6833e49c519e2d50d5077618f9e9) some of the Saturday Masses were broken (for example Polish Mass from 2-15-2020), as the references were not updated everywhere. Updating required references in proper files.
=> Fixing Mass proper after #500

web/cgi-bin/horas/horascommon.pl
Internally this is represented by a rank of 2.  This was handled correctly; only the reporting was wrong.
----
Testing: Advent ferias are shown correctly now.  Green ferias are still shown as IV. cl.
=> 1960: Advent ferias are third-class.

web/cgi-bin/horas/horascommon.pl, web/www/horas/Latin/Sancti/02-11.txt, web/www/horas/Latin/Sancti/03-06.txt, web/www/horas/Latin/Sancti/03-07.txt, web/www/horas/Latin/Sancti/03-09.txt, web/www/horas/Latin/Sancti/03-12.txt, web/www/horas/Latin/Sancti/03-21.txt, web/www/horas/Latin/Sancti/03-24.txt, web/www/horas/Latin/Sancti/04-11.txt, web/www/horas/Latin/Sancti/04-14.txt
The logic to force the rank of Lenten/Passiontide ferias to 4.9 was redundant, predating the ability to set ranks conditionally according to rubrics in the datafiles.  Having removed this, the datafiles of the relevant feasts have been changed so that they maintain their pre-1960 rank that allows them to beat such ferias.
----
Testing: Manual checking of `kalendar.pl` for "Rubrics 1960" and "1960 Newcalendar" for March 2020.  The former is unchanged; the latter now prefers the feasts.
=> 1960 Newcalendar: Prefer feasts specified in 'Cum Sanctissima' to Lenten ferias.

web/cgi-bin/horas/specmatins.pl, web/www/horas/English/Commune/C10t.txt, web/www/horas/English/Psalterium/Psalmi matutinum.txt, web/www/horas/Latin/Commune/C10t.txt, web/www/horas/Latin/Psalterium/Psalmi matutinum.txt
- ferial saturday matins has 12 psalms (99 and 100 were missing)
- BVM saturday matins has psalm 91 instead of 99
- BVM saturday lauds has antiphons and psalms as on feasts of the BVM
- BVM saturday matins has special V (Diffúsa est etc.)
- BVM saturday matins has special responsories
- BVM saturday lauds 1570 has old hymn
=> Changes to the Tridentine office on saturdays

web/cgi-bin/horas/specials.pl, web/www/horas/Latin/Sancti/12-25.txt, web/www/horas/Latin/Sancti/12-26.txt, web/www/horas/Latin/Sancti/12-27.txt, web/www/horas/Latin/Sancti/12-28.txt, web/www/horas/Latin/Sancti/12-29.txt, web/www/horas/Latin/Tempora/Nat1-0.txt
Fixes some issues with commemorations in Christmastide from #2176: 
- Vespers on 12-29 and 12-30 now has the vespers commemorations of the octaves including the nativity, 
- Commemoratio Die VI infra Octavam Nativitatis is omitted on 12-30
TODO: the commemoration of St. Thomas Becket is still last on 12-29 (it should be first)
=> Corrections to commemorations in Christmastide

web/www/missa/Magyar/Tempora/093-3.txt, web/www/missa/Magyar/Tempora/093-5.txt, web/www/missa/Magyar/Tempora/093-6.txt, web/www/missa/Magyar/Votive/Coronatio.txt, web/www/missa/Magyar/Votive/Dedicatio.txt, web/www/missa/Magyar/Votive/Defunctorum.txt
Removed superfluous English and Latin.  Left Latin at end of hymn from Daniel in 093-6.txt. Please advise if needs to be removed.
=> Remove Superfluous English from Magyar Texts

web/www/missa/English/Sancti/01-25.txt, web/www/missa/English/Sancti/01-25r.txt, web/www/missa/French/Sancti/01-25.txt, web/www/missa/French/Sancti/01-25r.txt, web/www/missa/Italiano/Sancti/01-25.txt, web/www/missa/Italiano/Sancti/01-25r.txt, web/www/missa/Latin/Sancti/01-25.txt, web/www/missa/Latin/Sancti/01-25r.txt, web/www/missa/Magyar/Sancti/01-25.txt, web/www/missa/Magyar/Sancti/01-25r.txt, web/www/missa/Polski/Sancti/01-25r.txt, web/www/missa/Portugues/Sancti/01-25r.txt
Other missals omit the Credo for this feast.
=> Remove Credo from Sancta Missa for Conversione S. Pauli Apostoli

web/www/horas/Latin/Commune/C6.txt, web/www/horas/Latin/SanctiM/03-12.txt, web/www/horas/Latin/Tempora/Pasc5-4.txt, web/www/horas/Latin/Tempora/Pasc7-0.txt, web/www/horas/Latin/Tempora/Pent01-0.txt
Removes nasty unicode linebreaks `\2028` and replaces them with nice real linebreaks `\n`.
Feel free to reject if these are actually needed for something.
=> remove nasty unicode linebreaks

web/www/horas/Latin/Sancti/08-18o.txt
Reference is to non-existent file. I presume `-t` suffix files = tridentine, in which case `08-18` seems the best bet as it's clearly actually used for the 1570 and 1910 versions.
The web version seems to work anyhow. Probably something clever is going on in the Perl.  Give me latin over Perl any day.
=> references non existent file

web/www/horas/Latin/TemporaM/Nat2-0.txt
There appears to be a typo in this replace str, which doesn't have an accent an an æ ligature.  Probably the accent was added at a later date in the target.
As a consequence Lectio12 at mattins for the second sunday of the Nativity is incorrect in the Latin, as can be seen by comparing it at divinumofficium.com with the English.
In broader thinking, it would be good to add a test for failing regexs in the Perl.  But Perl is to me a closed book so I'll leave that to someone else.
Either that or the English is wrong!
=> correct search str for Lectio 12 Nat2M

.github/workflows/build.yml
After dockerhub locked down auto builds, I had to move the build-and-push script to one of my personal servers in the short term.
This is the first step of the long term solution, which will build container images in github actions, which will eliminate the dependency on my personal infrastructure, but also provide improved visibility in github to things like failed builds, and providing nice feedback in Pull Requests if a code change is going to fail the build.
Currently this CI file builds the container image on pushes to `master`, but does not push that container image anywhere. A future CI PR will iterate further on this.
=> Begin Moving to Github Actions for Container Builds

web/cgi-bin/horas/horascommon.pl
(#2653)
The previous version did use the variable $csaint{Rank} to test whether concurring day was a vigil. It did not work, because the variable was redefined somewhere in between. I used the already defined $BMVSabbato variable which seems have had no purpose before.
=> Fix BMV Sabbato on Friday before Vigils

web/www/missa/French/Ordo/Ordo.txt
The rubrics style was broken after "Si la" as a newline was inserted probably by mistake.
=> Fix Rubrics style of French Credo

web/www/missa/Latin/Commune/C10b.txt
Was _adducéntur_ initially, but in repetition of verse in introit, it changed to _adducántur_; it should be _adducéntur_.
=> Introit: adducántur → adducéntur

standalone/tools/epubgen2/Ewebdia.pl
Use Unicode symbols:
☨
✠
✝
℣.
℟.
Modern e-book readers should support this.
=> ebook unicode crosses ☨ ✠ ✝ and ℟, ℣

web/www/missa/English/Commune/C9.txt, web/www/missa/English/Tempora/Quad1-0.txt, web/www/missa/French/Tempora/Quad1-0.txt, web/www/missa/Italiano/Tempora/Quad1-0.txt, web/www/missa/Latin/Tempora/Quad1-0.txt, web/www/missa/Portugues/Tempora/Quad1-0.txt
This reverts commit b16129c88885b5a24f60ebeaed3d4e7ca0187b56, reversing
changes made to 89cebc9734f8cc56dd6bef4886fdd244fe3ef25b.
Note:  Unintended consequences.  This change completely removed Tractus.  The odd formatting that I corrected was apparently a patch to solve a problem somewhere.
=> Revert "Merge pull request #2830 from dokeefe9999/master"

README.md
Reverse slashes to make the "How to generate Divine Office files" link in readme actually work.
=> reverse slashes to make the link in readme work

web/cgi-bin/horas/dialogcommon.pl, web/www/horas/Latin/Sancti/08-03.txt
eg.:
- 8/18 vespera (trident & divino) - Sancti/08-15t:Versum 3 is missing!
- 9/15 major hymn (monastic) - wrong render instead of doxology
- 8/3 nona (trident) - sometimes double Deo gratias
+AMDG+
=> code: fix unstable include substitutions 

web/www/horas/English/Commune/C7a.txt, web/www/horas/English/Commune/C7ap.txt, web/www/horas/Espanol/Commune/C7a.txt, web/www/horas/Espanol/Commune/C7ap.txt, web/www/horas/Francais/Commune/C7a.txt, web/www/horas/Italiano/Commune/C7a.txt, web/www/horas/Italiano/Commune/C7ap.txt, web/www/horas/Latin/Commune/C6ap.txt, web/www/horas/Latin/Commune/C7a.txt, web/www/horas/Latin/Commune/C7ap.txt, web/www/horas/Magyar/Commune/C7a.txt, web/www/horas/Magyar/Commune/C7ap.txt, web/www/horas/Polski/Commune/C7a.txt, web/www/horas/Polski/Commune/C7ap.txt
S. Monica had no Ant 2. But not because of the cleanup of C7a but because of the double cross-references I had introduced in C7ap.
Double checked with S. Monica (May 4, 2022 for Rubrics1960 and 2021 for DivinoAfflatu) that it works now in T. P.; and with S. Birgitta (October 8) also outside of T.P.
Merry Christmas!
=> Addressing the deeper cause of issue #3095

web/www/missa/English/Commune/C4a.txt, web/www/missa/English/Commune/C4ap.txt, web/www/missa/English/Commune/C5ap.txt, web/www/missa/English/Sancti/04-21.txt
Introit was missing "Lord" so prayer was replaced with St Joseph missal version.
Comma in Post Communion was replaced with period as consistent in other sources.
=> Typos and punctuation

standalone/tools/epubgen2/EofficiumXhtml.pl, standalone/tools/epubgen2/Ewebdia.pl, standalone/tools/epubgen2/epubgen2.sh, standalone/tools/epubgen2/headline.pl, web/cgi-bin/horas/horas.pl, web/cgi-bin/missa/Emissa.pl
Allow generating of standalone missale texts.
(Adds XHTML header that was missing in the implementation; document -m and -M switches in epubgen2.sh.)
See the newly generated missale and combined files on:
https://breviarium.srubarovi.cz/
=> fix headings in generated missale files

web/www/horas/English/Sancti/02-03.txt, web/www/horas/Italiano/Sancti/02-03.txt
This makes the English reading spell Blaise consistently, and improves the translation:
- The _spina_ lodged in the boy's throat is usually understood to be a fish bone rather than a thorn.
- _Praeses_ here is the governor of the province.
- I think Argasus was an OCR error (recognizing æ as "as"), but I corrected it without checking the Marquis of Bute scans.
In Italian, it supplies the missing "et Martyris" in the feast title.
=> Further St. Blaise corrections (English and Italiano)

web/www/horas/English/Martyrologium/01-21.txt
St. Meinrad's monastery was Einsiedeln. This is correct in the Latin version.
=> Martyrologium, English: Correct location

web/cgi-bin/horas/specmatins.pl
Tested on May 18, 2020; the last time it occured and no matins hymn was displayed anymore with old code
=> hymncontract: fix regexpr

obsolete/horas/Ckalendar.pl, obsolete/missa/Ckalendar.pl, obsolete/missa/kalendar.pl, web/cgi-bin/horas/kalendar.pl, web/cgi-bin/horas/officium_html.pl, web/cgi-bin/missa/Cmissa.pl, web/cgi-bin/missa/missa.pl, web/index.html
The loadbalancer has been adjusted to do server-side redirects from http -> https, so these client-side redirects are now superfluous.
=> Remove client-side redirects in favor of server side redirects

web/cgi-bin/DivinumOfficium/RunTimeOptions.pm
=> fix runtime error for 'old' version names 'Reduced 1955' & '1960 Newcalendar'

web/cgi-bin/horas/horas.pl
The triduum routine checked for tvesp == 3  i.e. whether we are in 2nd Vespers to do say the Gloria on Sabbato Sancto Vespers and Complet pre-1955.
However, the correct check should be whether we are not in 1st Vespers. Because in Laudes and throughout the day, i.e. tvesp == 2, we are still in the Triduum.
=> Fix Triduum Gloria omittitur #3456

web/cgi-bin/horas/horascommon.pl
To close #3498 and close #3496  as the reported observation is not an error.
=> Close #3498

web/cgi-bin/DivinumOfficium/Directorium.pm
This allows for local calendars (e.g. a Country or Religious Order) which generally follows the universal calendar, but with local feasts on particular days. Simplifies the calendar by allowing only the exceptions to be noted in the kalendaria, transfer and stransfer files.
read optional `$base` when reading data.txt
- after stransfer
- get kalendar, transfer or stransfer for a particular day/key,
- if the version has no entry
- and there is a base version specified,
- check the base version
Sample: for Redemptorists, the feast of St Alphonsus would be 1st class:
`data.txt`:
```
...
Rubrics 1960,1960,1960,1960
Redemptorist,fssr,fssr,fssr,Rubrics 1960
...
```
`Kalendaria/fssr.txt`:
```
08-02=08-02r=S. Alphonsi Mariae de Ligorio Episc Conf et Eccles Doct=6=St Stephano Papae Martyris=1=
``` …
=> calendar inheritance

web/www/missa/English/Tempora/Quadp3-3.txt, web/www/missa/French/Tempora/Quadp3-3.txt, web/www/missa/Italiano/Tempora/Quadp3-3.txt, web/www/missa/Latin/Tempora/Quadp3-3.txt, web/www/missa/Polski/Tempora/Quadp3-3.txt, web/www/missa/Portugues/Tempora/Quadp3-3.txt
At Ash Wednesday during imposition of ashes we chant a responsory. In all the languages on divinum officium including Latin the text was the same way it is printed in Missal: the refrain is given once, and then only the first couple words are repeated. We do expand introits, so I expanded this one as well.
**Attention** As it was in all the versions like that, I'm a bit anxious that I may have misunderstood it.
**Note** In Spanish the "attende" is absent altogether from propers, it should be added
=> Expand responsory at Ash Wednesday Mass

web/cgi-bin/horas/specials.pl
First it didn't work with `Nat6` but `Nat06` only; now it's `Nat6` again!? Let's be safe and allow for both.
=> Followup #3572

web/www/missa/Latin/Tempora/Quad1-0.txt
Fix the typo. Took the correct Latin version from [this missal](https://archive.org/details/missale-romanum-1962/page/n144/mode/1up) :
=> Missa Dom Quadragesima typo

web/www/missa/Latin/Tempora/Quad5-0.txt, web/www/missa/Latin/Tempora/Quad5-0t.txt
In the missal reference for the offertory is Ps 118:17, 107, so in that regard the site gives the correct reference.
But the first part of the offertory, *Confitébor tibi, Dómine, in toto corde meo*, is clearly from Ps 9:1 and not any part of Ps 118. I'm not sure if it makes sense to correct the missal in the Latin text though
=> Latin Missa Passionis: correct psalm reference

web/www/horas/Latin/Psalterium/Prayers.txt, web/www/missa/Latin/Ordo/Prayers.txt
In "Aperi Dómine" the emphasis is on the first syllable, not the second. Usually, the accent is not put over the "A" either, because it is capitalized.
=> fix typo in aperi prayer

web/www/horas/Dansk/Psalterium/Prayers.txt, web/www/horas/Deutsch/Psalterium/Prayers.txt, web/www/horas/English/Psalterium/Prayers.txt, web/www/horas/Espanol/Psalterium/Prayers.txt, web/www/horas/Francais/Psalterium/Prayers.txt, web/www/horas/Italiano/Psalterium/Prayers.txt, web/www/horas/Latin/Psalterium/Prayers.txt, web/www/horas/Magyar/Psalterium/Prayers.txt, web/www/horas/Polski/Psalterium/Prayers.txt, web/www/horas/Portugues/Psalterium/Prayers.txt
Reverts DivinumOfficium/divinum-officium#3782 because it adds needless line breaks and introduces typos into the Compline texts (cf. Baptistam -> aptistam)
=> Revert "Consistency in Prayers.txt and solving #3781"

web/www/horas/Italiano/Psalterium/Major Special.txt, web/www/horas/Magyar/Psalterium/Major Special.txt
In [Italian](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=03-20-2024&command=prayVespera&version=Rubrics%201960%20-%201960&testmode=regular&lang2=Italiano&votive=), Preces feriales appear in English. This PR changes the section name in `Major Special.txt` from `Preces feriales_` to `Preces feriales Laudes_` in the files for Italiano and Magyar in order to match the section name in the Latin file. I think this is the correct fix, but I haven't tested it extensively. in particular, I haven't tried to use all the variations of preces feriales that appear in the Latin file.
=> Restore preces feriales translations for Italian and Hungarian by correcting section names

web/cgi-bin/horas/horascommon.pl, web/www/horas/Latin/Tempora/Quad1-1.txt, web/www/horas/Latin/Tempora/Quad1-2.txt, web/www/horas/Latin/Tempora/Quad1-3.txt, web/www/horas/Latin/Tempora/Quad1-4.txt, web/www/horas/Latin/Tempora/Quad1-5.txt, web/www/horas/Latin/Tempora/Quad1-6.txt, web/www/horas/Latin/Tempora/Quadp3-3.txt, web/www/horas/Latin/Tempora/Quadp3-4.txt, web/www/horas/Latin/Tempora/Quadp3-5.txt, web/www/horas/Latin/Tempora/Quadp3-6.txt, web/www/horas/Latin/TemporaM/Quad1-1.txt, web/www/horas/Latin/TemporaM/Quad1-2.txt, web/www/horas/Latin/TemporaM/Quad1-3.txt, web/www/horas/Latin/TemporaM/Quad1-4.txt, web/www/horas/Latin/TemporaM/Quad1-5.txt, web/www/horas/Latin/TemporaM/Quad1-6.txt, web/www/horas/Latin/TemporaM/Quadp3-1.txt, web/www/horas/Latin/TemporaM/Quadp3-2.txt, web/www/horas/Latin/TemporaM/Quadp3-3.txt, web/www/horas/Latin/TemporaM/Quadp3-4.txt, web/www/horas/Latin/TemporaM/Quadp3-5.txt, web/www/horas/Latin/TemporaM/Quadp3-6.txt
In 1930:
1. Temporis post Septuagesimam on equal rank as Temporis Adventus (!), namely Feria privilegiata III. ordinis (de facto same as Feria major in Tridentine and Divino Roman)
2. Temporis Quadragesimae post diem Cinerum et Passionis ante Dominicam Palmarum all on the same rank "Feria privilegiata II. ordinis" (de facto same as Dominica minor)
=> MONASTIC 1930: Hebd Quinquagesima et Quadragesima prima

web/cgi-bin/horas/horas.pl, web/cgi-bin/horas/specials.pl
old perl versions may not support postfix dereferencing
=> perl backward compatibility

web/cgi-bin/DivinumOfficium/RunTimeOptions.pm, web/cgi-bin/horas/dialogcommon.pl, web/cgi-bin/missa/missa.pl, web/cgi-bin/missa/propers.pl, web/www/Tabulae/data.txt, web/www/missa/missa.dialog
1. breaking nested loops after six iterations 
@APMarcello3  @mbab @fiapps  : This should resolve the CPU overload; however, maybe the limit of 6 nestings is too narrow? Please test if any working references are broken by this limit.
2. Renaming the Missa version names hopefully resolving some other issue within the Cache for the `setupstring` function.
=> Brute Force solution to #525 + Missa version names

web/cgi-bin/horas/specmatins.pl
Even infra 8vam Ascensionis, Paschal Ferial Versicles are substituted in after Nocturns. For Tridentine, it also looks wrong throughout Paschal Tide as even Semiduplex receive Psalms and Antiphones etc. from Commune. 
Since the Rubrics in the Psalterium and for the Octave of the Ascension seem to be somehow in contradiction (Breviarum Romanum 1942; I guess universally for DA), could someone (maybe @MRoth1910 ) check, for instance, Matins of 
- Robert Bellarmine:  May 13, 2024 (Feria II infra Octavam Ascensionis) 
if not the Versicles should be of the Ascension rather than Ferial Paschal tide. (DA version) Curiosly, for Rubrics 1960, which does not have the Octave anymore, the Versicle is of the Ascension.
=> Trid/DA: Matins Versicles infra 8vam Ascensionis

web/www/horas/Francais/Psalterium/Prayers.txt, web/www/horas/Italiano/Martyrologium/07-16.txt, web/www/horas/Italiano/Psalterium/Prayers.txt
I've made the _Jube, domne/Domine_ Italian translation consistent (cf. #4028 discussion).
Other:
- Fix a typo in Italian.
- Put French _misereatur_ translation in the same person as the Latin (a Frenchman complained to me about this).
=> Jube domne Italian revision (plus a couple of minor errors)

web/www/horas/Dansk/Psalterium/Major Special.txt, web/www/horas/Deutsch/Psalterium/Major Special.txt, web/www/horas/English/Psalterium/Major Special.txt, web/www/horas/Espanol/Psalterium/Major Special.txt, web/www/horas/Francais/Psalterium/Major Special.txt, web/www/horas/Italiano/Psalterium/Major Special.txt, web/www/horas/Latin/Psalterium/Major Special.txt, web/www/horas/Magyar/Psalterium/Major Special.txt, web/www/horas/Polski/Psalterium/Major Special.txt
The newlines in the database files are crucial to tell the code what exactly gets omitted in Tridentine version. To achieve joined layout, we have to work with the "tilde" `~` instead, keeping the empty lines.
__
Revert "Update Major Special.txt"
This reverts commit 1d510fc512005222f39756dc48baa1d3bfde88d7.
Revert "Update Major Special.txt"
This reverts commit 9e884402a106664d9b427271cfc8caabf5f1340a.
=> Tridentine: Fixing Preces feriales 

web/cgi-bin/horas/monastic.pl, web/cgi-bin/horas/specials.pl, web/www/horas/Dansk/Psalterium/Translate.txt, web/www/horas/Deutsch/Psalterium/Translate.txt, web/www/horas/English/Psalterium/Translate.txt, web/www/horas/Espanol/Psalterium/Translate.txt, web/www/horas/Francais/Psalterium/Translate.txt, web/www/horas/Italiano/Psalterium/Translate.txt, web/www/horas/Latin/Psalterium/Translate.txt, web/www/horas/Magyar/Psalterium/Translate.txt, web/www/horas/Ordinarium/Matutinum.txt, web/www/horas/Ordinarium/Prima.txt, web/www/horas/Polski/Psalterium/Translate.txt, web/www/horas/Portugues/Psalterium/Translate.txt
- to make the cell containing the Regula and/or Short reading comply with the "skeleton" expansion option
- plus a couple of additional Translations for labels
=> Monastic: Regula as Section item

web/cgi-bin/horas/specials.pl, web/cgi-bin/horas/specials/capitulis.pl, web/cgi-bin/horas/specials/hymni.pl, web/cgi-bin/horas/specials/orationes.pl, web/cgi-bin/horas/specials/preces.pl, web/cgi-bin/horas/specials/psalmi.pl, web/cgi-bin/horas/specials/specprima.pl
=> code: modularize function special, split specials.pl

web/cgi-bin/DivinumOfficium/SetupString.pl, web/cgi-bin/missa/ordo.pl, web/www/horas/English/Commune/C9.txt, web/www/horas/Espanol/Commune/C9.txt, web/www/horas/Francais/Commune/C9.txt, web/www/horas/Italiano/Commune/C9.txt, web/www/horas/Latin/Commune/C9.txt, web/www/horas/Magyar/Commune/C9.txt, web/www/horas/Polski/Commune/C9.txt
=> Issue #4111

web/cgi-bin/horas/specials/capitulis.pl, web/cgi-bin/horas/specials/hymni.pl, web/cgi-bin/horas/specials/orationes.pl, web/cgi-bin/horas/specials/preces.pl, web/cgi-bin/horas/specials/psalmi.pl, web/cgi-bin/horas/specials/specprima.pl
close #4137
@mbab. apparently each sub `.pl`-script needs its own `use utf8;` for special characters to match in regex's
=> "use utf8;" in script files

web/cgi-bin/horas/horascommon.pl, web/cgi-bin/horas/specmatins.pl
- prevent spliting biblical readings in two paragraphs when using 'nonumber'
- from options return to used date not today
+AMDG+
=> code: fixes

web/cgi-bin/horas/specials/orationes.pl
eg. Laudes 12/14/2024 1960
@FAJ-Munich `@commemoentries` contains empty strings, could fix this in proper place?
+AMDG+
=> quick hack to prevent perl warnings in FileIO.pm

web/www/horas/English/psalms/Psalm266.txt, web/www/horas/English/psalms/Psalm267.txt
Psalm266.txt and Psalm267.txt (both of the txt files which contain the canticle of Isaiah) have a space at the start of the first verse which leads to a minor visual issue where the first verse isn't highlighted in red, as seen in the screenshots below:
This pull requests removes those spaces. For reference, both screenshots are taken from the Sunday Matins of the 1963 Monastic office.
=> Fix formatting for the canticle of Isaiah (Remove unnecessary spaces from Psalm266.txt and Psalm267.txt)

web/cgi-bin/DivinumOfficium/dialogcommon.pl, web/cgi-bin/horas/horascommon.pl, web/cgi-bin/horas/specials/orationes.pl, web/cgi-bin/horas/specmatins.pl
this is proper solution for warnings from FileIO
resolved in (reverted here) d06bccd6d1 & 255bc14cb5
+AMDG+
=> code: replace `undef` with proper values,

web/cgi-bin/horas/webdia.pl
empty color generates bug in doepub reported in #4191
+AMDG+
=> code: fix generate FONT tag with empty COLOR

web/cgi-bin/horas/horasscripts.pl, web/cgi-bin/horas/officium.pl, web/cgi-bin/horas/webdia.pl
=> Hodie et Crastina option for bookmarking purpose

web/cgi-bin/horas/kalendar.pl, web/cgi-bin/horas/kalendar/kal.pl, web/cgi-bin/horas/kalendar/ordo.pl
1. showing additional commemorations (where applicable; in the order given in Tabulae; for June 28 (DA version) Vigilia comes before infra 8vam S.J.B. due to technical issue otherwise)
2. new column "Vespera" given the Vespers information
3. Kalendarium: no capitalisation for infra Octavam and Vigilia
=> Ordo: new features

web/cgi-bin/missa/ordo.pl
Preserving the original behaviour when &hancigitur expands to the expected rubric seems to be prefered. When the expansion to the rubric does not occur, merge the previous, the expansion and the next line together.
=> Addresses the issue #4245, removes a few <br />s

web/www/horas/Portugues/Psalterium/Special/Minor Special.txt
Translate to Portuguese the Hymnus Tertia from web/www/horas/Portugues/Psalterium/Special/Minor Special.txt
I use the portguese translation from the [Nunc-Sancte-Nobis.pdf](https://salvemaria.com.br/wp-content/uploads/2018/04/Nunc-Sancte-Nobis.pdf) from [salvemaria.com.br](https://salvemaria.com.br)
=> Add Portuguese to Hymus in Tertia from Minor Special.txt 

web/www/missa/Latin/Sancti/09-23.txt, web/www/missa/Latin/Sancti/11-23.txt
This reverts parts of commit 451f1c6921ae8cc2121ef4b8ac34440abbed3633.
For the time being, the Oratios in Latin are still necessary for pre-`Si diligis` rubrics
=> Revert parts of "Mass fixes"

web/cgi-bin/horas/specials/capitulis.pl, web/www/Tabulae/Kalendaria/CAV.txt, web/www/horas/Bohemice/Commune/C8.txt, web/www/horas/Bohemice/Commune/C9.txt, web/www/horas/Bohemice/CommuneM/C8.txt, web/www/horas/Latin/Commune/C9.txt, web/www/horas/Latin/CommuneM/C8.txt, web/www/horas/Latin/CommuneM/C9.txt, web/www/horas/Latin/Sancti/06-01Av.txt
**Cistercian version:** C8 and C9 Vespers added including Czech translation
**specials/capitulis.pl:** for Cistercian version, the _Responsorium prolixum_ added as `Responsory Vespers 1`, which is usually reserved only for Nativity. As a _Responsorium prolixum_ is part of first Vespers of every Festum Sermonis (like first Class in Roman Calendar), we need them quite a lot...
=> Cist: C8 + C9 Vespers incl. Czech

web/www/horas/Latin/Psalterium/Invitatorium.txt
A semicolon doesn't precede a capital letter. It should be colon.
=> 'mea; Si introíbunt' → 'mea: Si introíbunt'

web/www/horas/English/Tempora/Epi2-0.txt, web/www/horas/Italiano/Psalterium/Common/Prayers.txt, web/www/horas/Latin/Sancti/12-25.txt
- 4cbf012102a4e0b51acf76c01f25e0ad2e9195a4 added a second `Ant Vespera 3` section to `horas/Latin/Sancti/12-25.txt`. This shadows the section with the correct antiphons for the Roman Rite, so I'm reverting this change. I'm not sure what @Augustinus-Altovadensis was trying to accomplish. Perhaps it was meant to apply only to the Cistercian office. If it wasn't simply a mistake, he'll have to try again.
- dc500d9ec7d7ffffe3dabb65ceb1dde350413053 replaced three texts in `horas/English/Tempora/Epi2-0.txt` with Czech. I'm reverting this obvious mistake.
- There's also a fix for the Italian translation of Compline that I had forgotten to commit. This gives the oration Visita the same kind of initial capital in Italian that it has in Latin and other translations.
=> Revert recent accidental changes (plus an Italian fix)

web/cgi-bin/DivinumOfficium/SetupString.pl, web/www/horas/Latin/Commune/C5.txt
Fixes: Removes trailing newlines from the Officium hash and restores accented characters in the C5 oratio.
I'll prepare another PR in a day or two to restore more accents lost in the merge of horas and missa.
=> Resolve #4387 and restore a few accents

web/www/horas/Latin/Sancti/10-24.txt
Adding accents to the hymn at Laudes for St. Gabriel caused the substitution in the 10-24 file to fail. This PR adds accents to the substitution regexes so they will match.
=> Fix hymn at Laudes for St. Raphael

web/www/horas/Bohemice/Tempora/Pasc6-0.txt, web/www/horas/Bohemice/TemporaM/Pasc6-0.txt, web/www/horas/Espanol/TemporaM/Pasc6-0.txt, web/www/horas/Francais/TemporaM/Pasc6-0.txt, web/www/horas/Italiano/TemporaM/Pasc6-0.txt, web/www/horas/Magyar/TemporaM/Pasc6-0.txt, web/www/horas/Nederlands/TemporaM/Pasc6-0.txt, web/www/horas/Polski/TemporaM/Pasc6-0.txt
close #4443
@Augustinus-Altovadensis 
Apparently, since in Latin, `Officium` and `Rank` is only defined in Tempora/Pasc6-0 but not TemporaM/Pasc6-0 there must not be a `Officium` hash in the vernacular versions of TemporaM/Pasc6-0. In Tempora/Pasc6-0 it is fine.
=> For issue #4443

web/cgi-bin/horas/monastic.pl, web/cgi-bin/horas/specmatins.pl, web/www/horas/Bohemice/Commune/C11.txt, web/www/horas/Bohemice/CommuneM/C11.txt, web/www/horas/Bohemice/Psalterium/Psalmorum/Psalm214.txt, web/www/horas/Bohemice/Psalterium/Psalmorum/Psalm272.txt, web/www/horas/Bohemice/Psalterium/Psalmorum/Psalm273.txt, web/www/horas/Bohemice/Sancti/07-16.txt, web/www/horas/Bohemice/Sancti/09-08.txt, web/www/horas/Bohemice/SanctiM/07-16.txt, web/www/horas/Bohemice/Tempora/Pent01-4.txt, web/www/horas/Bohemice/Tempora/Quad6-4.txt, web/www/horas/Bohemice/TemporaM/Pent01-4.txt, web/www/horas/Latin/Commune/C10.txt, web/www/horas/Latin/Commune/C11.txt, web/www/horas/Latin/CommuneM/C11.txt, web/www/horas/Latin/SanctiM/07-16.txt, web/www/horas/Latin/Tempora/Pent01-4.txt, web/www/horas/Latin/TemporaM/Pent01-4.txt, web/www/missa/Bohemice/Tempora/Pent01-4.txt
Cistercian version Matins:
- added Commune de Beata 
- added Corpus Christi
- added Czech translation
- `specmatins.pl`: fixed the code adding _Pater noster_ to Matutinum parvum de Beata.
- `monastic.pl`: fixed the code replacing the standard ferial Antiphons with Allelúia in certain cases like Sabbato de Beata. This is wrong for the Cistercian rite.
=> Cist: added Commune de Beata for Matins + Czech + Corpus Christi

web/cgi-bin/horas/horasscripts.pl, web/cgi-bin/horas/monastic.pl, web/cgi-bin/horas/specials.pl, web/www/horas/Bohemice/Psalterium/Common/Prayers.txt, web/www/horas/Bohemice/Psalterium/Psalmi/Psalmi matutinum.txt, web/www/horas/Bohemice/Psalterium/Psalmorum/Psalm85.txt, web/www/horas/Bohemice/Psalterium/Psalmorum/Psalm94C.txt, web/www/horas/Deutsch/Psalterium/Psalmorum/Psalm94C.txt, web/www/horas/English/Psalterium/Psalmorum/Psalm94C.txt, web/www/horas/Espanol/Psalterium/Psalmorum/Psalm94C.txt, web/www/horas/Francais/Psalterium/Psalmorum/Psalm94C.txt, web/www/horas/Italiano/Psalterium/Psalmorum/Psalm94C.txt, web/www/horas/Latin/Psalterium/Psalmi/Psalmi matutinum.txt, web/www/horas/Latin/Psalterium/Psalmorum/Psalm94C.txt, web/www/horas/Latin/Tempora/Pent01-5.txt, web/www/horas/Latin/TemporaM/Pent01-5.txt, web/www/horas/Polski-Newer/Psalterium/Psalmorum/Psalm94C.txt, web/www/horas/Polski/Psalterium/Psalmorum/Psalm94C.txt
Changes in code for the Cistercian rite:
- `horasscripts.pl`: cosmetics (see further)
- `specials.pl`: Implemented change from discussion #4555 (in Cistercian rite, in Summer, the Invitatory is not said on Ferias or Vigils)
- `monastic.pl`: MM LB (Lectio Brevis in Matins) is needed not only on Ferias, but also on Ferias within Octaves and Vigils. Therefore this has been introduced, and will be adapted as needed.
Other changes:
- unified the Czech translation of collect endings
- added Friday in Octava Corporis Christi
=> Cist: Code changes for Matins in Oct./Vigils

web/cgi-bin/horas/specials/orationes.pl, web/www/horas/Bohemice/Commune/C12.txt, web/www/horas/Bohemice/Psalterium/Special/Matutinum Special.txt, web/www/horas/Latin/Psalterium/Special/Matutinum Special.txt
Error corrections:
- `orationes.pl`: In Czech, the word for Vigilia is usually "Vigilie", which was excluded by the original grep query `/Vigilia/i`, and the entire commemoration was lost. Corrected.
- Incorrect translation for verse for None in C12 corrected.
- `[MM Capitulum]` was corrected, so that it doesn't leak into other Monastic versions.
=> Cist: error corrections

web/www/horas/Bohemice/Sancti/01-25.txt, web/www/horas/Bohemice/Sancti/06-30.txt, web/www/horas/English/Sancti/06-30.txt, web/www/horas/Espanol/Tempora/Pent01-0.txt, web/www/horas/Espanol/Tempora/Pent01-2.txt, web/www/horas/Espanol/Tempora/Pent01-3.txt, web/www/horas/Espanol/Tempora/Pent03-1Feria.txt, web/www/horas/Espanol/Tempora/Pent03-2Feria.txt, web/www/horas/Francais/Tempora/Pent01-0.txt, web/www/horas/Francais/Tempora/Pent01-2.txt, web/www/horas/Francais/Tempora/Pent01-3.txt, web/www/horas/Francais/Tempora/Pent03-1Feria.txt, web/www/horas/Francais/Tempora/Pent03-2Feria.txt, web/www/horas/Italiano/Tempora/Pent01-0.txt, web/www/horas/Italiano/Tempora/Pent01-2.txt, web/www/horas/Italiano/Tempora/Pent01-3.txt, web/www/horas/Italiano/Tempora/Pent03-1Feria.txt, web/www/horas/Italiano/Tempora/Pent03-2Feria.txt, web/www/horas/Latin/Sancti/01-25.txt, web/www/horas/Latin/Sancti/06-30.txt, web/www/horas/Polski/Tempora/Pent01-0.txt, web/www/horas/Polski/Tempora/Pent01-2.txt
- Fixed the issue with 01-25/06-30 and their common [Ant 2]. Here, both versions of the Antiphon are needed - the Roman version is used in Cistercian Matins, that's why I divided the [Ant 2], but I messed up the cross-links before. Sorry for that!
- finished adding cross-links from yesterday's PR
=> Cist: bugfixes for Responsories after Pentecost etc.

web/www/missa/Espanol/Ordo/Ordo.txt
The Spanish translation of the Ordo rubrics contains some elements that could be improved:
- The expressions "facta illi debita reverentia", "profunde inclinatus", "inclinatus", and "inclinat caput" are translated as "postrándose" ("prostrating"), which is incorrect.
- The phrase "en medio del altar" would be clearer if rendered as "en el centro del altar" ("in the center of the altar").
- The rubric for the Preface is not fully translated.
=> correct translation errors in Spanish Ordo rubrics

web/www/horas/Bohemice/SanctiM/03-21C.txt, web/www/horas/Latin/Sancti/01-15.txt, web/www/horas/Latin/SanctiM/01-11.txt, web/www/horas/Latin/SanctiM/03-21C.txt, web/www/horas/Latin/SanctiM/07-13AV.txt
Correction of typos and missed things.
@FAJ-Munich 
Could you please check, whether on Saturday January 11 in any monastic rite, the day within Epiphany Octave should have second Vespers? I trust you still have the rubrics fresh in mind... I checked the last week's changes and found that in Vespers on 1-11-2025 for the Altovadense version, the Commemoration of the Octave appears twice, and once (from the `SanctiM/01-11.txt` file) without the translation. This PR correct this, but it might introduce another problem...
BTW, for this day in the 1951 version, it doesn't show the commemoration of the Octave, which is in the `TemporaM?` file, which it should... In Vespers nor in Lauds.
Thank you, God bless!
=> Cist: bugfixes

docker/generator/Dockerfile, standalone/tools/epubgen2/epubgen2.sh
Second language appears to the right. Without debian version called out it will assume buster (debian 10) which reached EOL 30 June 2024.
=> Epub language and debian

Dockerfile
Also, fix a few linter errors in the `Dockerfile` around token case (`as` vs `AS`, etc) and setting env vars (`key var` vs `key=var`).
The key change of this PR is line 16, the rest are trivial linter errors.
Not ready for merge, needs further testing.
=> Upgrade Docker Base Image to perl:5.42-slim

web/cgi-bin/horas/specials/orationes.pl, web/www/horas/Latin/TemporaM/Pasc1-1.txt, web/www/horas/Latin/TemporaM/Pent01-1.txt
@Augustinus-Altovadensis 
39f575bd2d59d7a5da6e60df2228228a95ace35f addresses your request.
However, I think a general question on the order of commemorations needs to be answered by the Brothers (or you):
- In the Tridentine rubrics and, hence, the Cistercian 1951, the order of commemorations purely follows the ranks of feasts and days. 
- Divino Afflatu changed this general rule in two ways:
1. Sunday commemorations are privilidged trumping all feasts (this is what interferred on Jan 12, 2025 in Altovado implementation)
2. The concurrent feast gets commemorated first always whatsoever. (This is not implemented for Altovado)
In the commit, I now relaxed rule 1 for the case of Sunday commemmorations comming out of `[Commemoratio]` hashes. The other option would have been to implement rule …
=> Cist: commemorations
