web/www/horas/Deutsch/Tempora/Adv1-2.txt

German translation

---

web/www/horas/Polski/Ordinarium/Laudes.txt
web/www/horas/Polski/Ordinarium/Laudes1960.txt
web/www/horas/Polski/Ordinarium/LaudesM.txt
web/www/horas/Polski/Ordinarium/LaudesTrid.txt
web/www/horas/Polski/Ordinarium/Matutinum.txt
web/www/horas/Polski/Ordinarium/Matutinum1960.txt
web/www/horas/Polski/Ordinarium/MatutinumM.txt
web/www/horas/Polski/Ordinarium/Matutinume.txt
web/www/horas/Polski/Ordinarium/Matutinume1960.txt
web/www/horas/Polski/Ordinarium/MatutinumeM.txt
web/www/horas/Polski/Ordinarium/Nona.txt
web/www/horas/Polski/Ordinarium/Nona1960.txt
web/www/horas/Polski/Ordinarium/NonaM.txt
web/www/horas/Polski/Ordinarium/Sexta.txt
web/www/horas/Polski/Ordinarium/Sexta1960.txt
web/www/horas/Polski/Ordinarium/SextaM.txt
web/www/horas/Polski/Ordinarium/Tertia.txt
web/www/horas/Polski/Ordinarium/Tertia1960.txt
web/www/horas/Polski/Ordinarium/TertiaM.txt
web/www/horas/Polski/Ordinarium/Tertiap.txt
web/www/horas/Polski/Ordinarium/Tertiap1960.txt
web/www/horas/Polski/Ordinarium/TertiapM.txt
web/www/horas/Polski/Ordinarium/Vespera.txt
web/www/horas/Polski/Ordinarium/Vespera1960.txt
web/www/horas/Polski/Ordinarium/VesperaM.txt
web/www/horas/Polski/Ordinarium/VesperaTrid.txt

As stated in the title, Polish Ordinaria are complete now.

Add Polish Ordinaria (all of them)

---

TranslationStatus/PlMissa.md

A simple page where we could track progress of Polish translation and present it in a concise way to Polish users in one central place.

Adding status page for Polish translation

---

web/www/horas/Help/Missing Offices.html

Minor typo. Correct repo this time, sorry.

Latin souce to Latin source

---

web/www/horas/Polski/Psalterium/Psalmi matutinum.txt
web/www/horas/Polski/Sancti/12-24.txt
web/www/horas/Polski/Sancti/12-25.txt

Everything should be in Polish in these days (Rubrics 1960).

Polish translations for the 24th and the 25th of December

---

web/www/missa/sourceC.html

A few of these Missal sources are no longer online. I have added links to the archived webpages on the Wayback Machine. The design of the links have been slightly changed to accommodate for this.

Add links to Wayback Machine (Missal sources)

---

web/www/horas/Latin/Sancti/01-14.txt
web/www/horas/Latin/Sancti/01-14o.txt

Should have thought of this already yesterday, sorry

Put all lesson texts into 01-14 again, instead of splitting them into 01-14 and 01-14o

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/missa/propers.pl
web/www/horas/Polski/Commune/C1.txt
web/www/horas/Polski/Commune/C2.txt
web/www/horas/Polski/Martyrologium/12-29.txt
web/www/horas/Polski/Psalterium/Psalmi minor.txt
web/www/horas/Polski/Sancti/01-15.txt
web/www/horas/Polski/Sancti/01-18.txt
web/www/horas/Polski/Sancti/02-22.txt
web/www/horas/Polski/Sancti/12-21.txt
web/www/horas/Polski/Sancti/12-28.txt
web/www/horas/Polski/Sancti/12-28o.txt
web/www/horas/Polski/Sancti/12-28r.txt
web/www/horas/Polski/Tempora/Adv4-0.txt
web/www/horas/Polski/Tempora/Epi2-0.txt
web/www/horas/Polski/Tempora/Quadp1-0.txt
web/www/horas/Polski/psalms1/Psalm118.txt

Fixes and Polish translations

---

web/www/horas/Latin/Tempora/Epi1-0.txt
web/www/missa/Latin/Ordo/Ordo.txt

Small Latin corrections

---

web/www/missa/Latin/Tempora/Quad6-3.txt
web/www/missa/Polski/Tempora/Quad6-3.txt

Problem in Holy Wednesday's Passion. It's similar to one described in issue #394. After 1955 changes, Passion starts with verse Luc 22:39, while Divinum Officum shows it from 22:1.
I made a fix to Latin and Polish propers.

Polish - Mass - adding Holy Wednesday

---

web/www/horas/Polski/Commune/C4.txt
web/www/horas/Polski/Psalterium/Major Special.txt
web/www/horas/Polski/Tempora/Quadp2-0.txt
web/www/missa/Polski/Ordo/Ordo.txt

Polish translations

---

web/www/horas/English/Psalterium/Major Special.txt
web/www/horas/Polski/Psalterium/Major Special.txt
web/www/horas/Polski/Psalterium/Translate.txt

The missing suffragia in Polish and one antiphon in English have been translated. I also add few lines to Polish and English translation of "Vexilla Regis" (vide #411).

Suffragia (Polish) and changes in Vexilla Regis

---

web/www/missa/English/Tempora/Quad6-5.txt
web/www/missa/English/Tempora/Quad6-5r.txt
web/www/missa/English/Tempora/Quad6-5t.txt
web/www/missa/Italiano/Tempora/Quad6-5.txt
web/www/missa/Italiano/Tempora/Quad6-5r.txt
web/www/missa/Italiano/Tempora/Quad6-5t.txt
web/www/missa/Latin/Tempora/Quad6-5.txt
web/www/missa/Latin/Tempora/Quad6-5r.txt
web/www/missa/Latin/Tempora/Quad6-5t.txt
web/www/missa/Magyar/Tempora/Quad6-5.txt
web/www/missa/Magyar/Tempora/Quad6-5r.txt
web/www/missa/Magyar/Tempora/Quad6-5t.txt
web/www/missa/Polski/Tempora/Quad6-5r.txt

Fixed issue #414. I added missing prayer for all versions to Latin and English files.
I also copied English version to Italian and Hungarian files to preserve the structure when Latin file is changed, so these two language versions need additional translation of this prayer to proper language.

Polish - Mass - Adding Good Friday; fixing #414

---

web/www/horas/Polski/Psalterium/Psalmi major.txt
web/www/horas/Polski/Psalterium/Psalmi matutinum.txt
web/www/horas/Polski/Sancti/01-18.txt
web/www/horas/Polski/Sancti/02-02.txt
web/www/horas/Polski/Tempora/Quadp3-0.txt

More Polish translation

---

web/www/horas/Latin/Sancti/02-01.txt
web/www/horas/Latin/Sancti/02-03.txt
web/www/horas/Latin/Tabulae/K1888.txt
web/www/horas/Latin/Tabulae/K1942.txt
web/www/horas/Latin/Tabulae/K1960.txt

Latin files changes

---

web/www/horas/Polski/Commune/C11.txt
web/www/horas/Polski/Psalterium/Major Special.txt
web/www/horas/Polski/Sancti/02-02.txt
web/www/horas/Polski/Tempora/Nat2-0.txt

The PR contains a complete set of the texts needed on the Feast of the Purification.
I would greatly appreciate it if you could update the live site before this feast, so it could be used then.

Polish texts for 2nd February

---

web/www/horas/Polski/Psalterium/Psalmi minor.txt
web/www/horas/Polski/Sancti/01-30.txt
web/www/horas/Polski/Sancti/01-31.txt
web/www/horas/Polski/Sancti/02-06.txt
web/www/horas/Polski/Sancti/02-06o.txt
web/www/horas/Polski/Sancti/02-07.txt
web/www/horas/Polski/Sancti/02-08.txt
web/www/horas/Polski/Sancti/02-09.txt
web/www/horas/Polski/Sancti/02-09o.txt
web/www/horas/Polski/Sancti/02-10.txt
web/www/horas/Polski/Sancti/02-11.txt
web/www/horas/Polski/Sancti/02-12.txt
web/www/horas/Polski/Sancti/02-14.txt
web/www/horas/Polski/Sancti/02-15.txt
web/www/horas/Polski/Sancti/02-18.txt
web/www/horas/Polski/Tempora/Quad1-0.txt
web/www/horas/Polski/Tempora/Quad1-1.txt
web/www/horas/Polski/Tempora/Quad1-2.txt
web/www/horas/Polski/Tempora/Quad1-3.txt
web/www/horas/Polski/Tempora/Quad1-4.txt
web/www/horas/Polski/Tempora/Quad1-5.txt
web/www/horas/Polski/Tempora/Quad1-6.txt
web/www/horas/Polski/Tempora/Quad2-0.txt
web/www/horas/Polski/Tempora/Quad2-1.txt
web/www/horas/Polski/Tempora/Quad2-2.txt
web/www/horas/Polski/Tempora/Quad2-3.txt
web/www/horas/Polski/Tempora/Quad2-4.txt
web/www/horas/Polski/Tempora/Quad2-5.txt
web/www/horas/Polski/Tempora/Quad2-6.txt

More Polish translations

---

web/www/horas/Latin/Sancti/02-05.txt

Fix #445 another

---

web/cgi-bin/horas/specials.pl
web/www/horas/Deutsch/Psalterium/Translate.txt
web/www/horas/English/Psalterium/Translate.txt
web/www/horas/Italiano/Psalterium/Translate.txt
web/www/horas/Latin/Psalterium/Translate.txt
web/www/horas/Polski/Psalterium/Translate.txt

Translation of 'Commemoratio'

---

web/www/horas/Magyar/Psalterium/Major Special.txt

I've added the correct verse for September 14.
Source of translation: http://breviar.sk/include_hu/sv_sep.htm
I haven't managed to find a verse for May 3, so I've made it to display as it used to be; however, I think that the version from September 14 would be more fitting (still incorrect, though).

Partial fix of  #411 (Hungarian)

---

web/www/horas/Latin/Commune/C7ap.txt

Correct me if I'm wrong, but I think this alleluia's should be there.

Add missing Alleluia's to C7ap

---

web/www/horas/Polski/Commune/C1ap.txt
web/www/horas/Polski/Commune/C2p.txt

Polish translations - corrections

---

web/www/horas/English/Tempora/Pent03-0r.txt
web/www/horas/English/Tempora/Pent04-0.txt
web/www/horas/English/Tempora/Pent04-0o.txt
web/www/horas/English/Tempora/Pent05-0.txt
web/www/horas/English/Tempora/Pent05-0o.txt
web/www/horas/English/Tempora/Pent06-0.txt
web/www/horas/English/Tempora/Pent07-0.txt
web/www/horas/English/Tempora/Pent08-0.txt
web/www/horas/English/Tempora/Pent09-0.txt
web/www/horas/English/Tempora/Pent10-0.txt
web/www/horas/Latin/Tempora/Pent01-1.txt
web/www/horas/Latin/Tempora/Pent01-2.txt
web/www/horas/Latin/Tempora/Pent03-0r.txt
web/www/horas/Latin/Tempora/Pent04-0.txt
web/www/horas/Latin/Tempora/Pent04-0o.txt
web/www/horas/Latin/Tempora/Pent05-0.txt
web/www/horas/Latin/Tempora/Pent05-0o.txt
web/www/horas/Latin/Tempora/Pent06-0.txt
web/www/horas/Latin/Tempora/Pent07-0.txt
web/www/horas/Latin/Tempora/Pent08-0.txt
web/www/horas/Latin/Tempora/Pent09-0.txt
web/www/horas/Latin/Tempora/Pent10-0.txt

Latin cross references

---

web/www/horas/Latin/Tempora/Pent03-1Feria.txt
web/www/horas/Latin/Tempora/Pent03-1Feriao.txt
web/www/horas/Latin/Tempora/Pent03-2Feria.txt
web/www/horas/Latin/Tempora/Pent03-2Feriao.txt
web/www/horas/Latin/Tempora/Pent03-3Feria.txt
web/www/horas/Latin/Tempora/Pent03-4Feria.txt
web/www/horas/Latin/Tempora/Pent03-5Feria.txt
web/www/horas/Latin/Tempora/Pent03-5Feriao.txt
web/www/horas/Latin/Tempora/Pent03-6o.txt
web/www/horas/Latin/Tempora/Pent04-1o.txt
web/www/horas/Latin/Tempora/Pent04-2o.txt
web/www/horas/Latin/Tempora/Pent04-3o.txt
web/www/horas/Latin/Tempora/Pent04-4o.txt
web/www/horas/Latin/Tempora/Pent04-5o.txt

Latin Tempore files: cross references

---

web/www/horas/Deutsch/Commune/C1.txt
web/www/horas/Italiano/Tempora/Pent02-5.txt
web/www/horas/Latin/Commune/C1.txt
web/www/horas/Latin/Tempora/Pent02-5.txt
web/www/horas/Polski/Commune/C1.txt
web/www/horas/Polski/Tempora/Pent02-5.txt

Just spotted missing Per Dominum in DA Vesperas today and find it written as `$Per Dóminum`.
Fix all occurrences.

$Per Dóminum fix

---

web/www/horas/Polski/Commune/C9.txt
web/www/horas/Polski/Sancti/11-02.txt

Few texts in Sancti/11-02.txt have been translated, since they were needed in Commune/C9.txt

Add Officium Defunctorum (Polish)

---

web/www/horas/Latin/Commune/C5.txt
web/www/horas/Latin/Sancti/07-04.txt
web/www/horas/Latin/Sancti/07-06.txt
web/www/horas/Latin/Sancti/07-11.txt
web/www/horas/Latin/Sancti/07-13.txt
web/www/horas/Latin/Sancti/07-14.txt
web/www/horas/Latin/Sancti/07-17.txt
web/www/horas/Latin/Sancti/07-22.txt

Latin files: Sancti/07-* - references + C5 additions

---

web/cgi-bin/horas/horas.pl

red dot after R.br

---

web/www/horas/Latin/Sancti/07-01.txt
web/www/horas/Latin/Sancti/07-26.txt
web/www/horas/Latin/Sancti/07-27.txt

Latin files: Sancti/07-* - references + additions

---

web/www/horas/Latin/Commune/C11.txt
web/www/horas/Latin/Sancti/07-02.txt
web/www/horas/Latin/Sancti/07-12.txt

Latin Sancti files: 07-* more

---

web/www/horas/Latin/Sancti/02-22.txt
web/www/horas/Latin/Sancti/06-29.txt
web/www/horas/Latin/Sancti/08-01.txt
web/www/horas/Latin/Sancti/08-03.txt
web/www/horas/Latin/Sancti/08-05.txt
web/www/horas/Latin/Sancti/08-06.txt
web/www/horas/Latin/Sancti/08-09o.txt
web/www/horas/Latin/Sancti/08-10.txt
web/www/horas/Latin/Sancti/08-15.txt
web/www/horas/Latin/Sancti/08-15r.txt
web/www/horas/Latin/Sancti/08-17.txt
web/www/horas/Latin/Sancti/08-29.txt
web/www/horas/Latin/Sancti/12-26.txt

Latin Sancti files: 08-* more

---

web/www/horas/Latin/Commune/C1.txt
web/www/horas/Latin/Commune/C4.txt

These correct errors introduced by pull requests merged recently. 55d7de1 relates to #575.

Correct errors introduced recently

---

web/www/horas/Latin/Sancti/04-25t.txt
web/www/horas/Latin/Sancti/06-13t.txt
web/www/horas/Latin/Sancti/07-14.txt
web/www/horas/Latin/Sancti/07-22.txt

Latin Sancti files: correct links to Commune (#575)

---

web/www/horas/Polski/Commune/C11.txt
web/www/horas/Polski/Sancti/08-15r.txt

The hymns have been translated by me, with some mbab's suggestions.
Few translation have been added to C11, as they are needed
on August 15th.

Polski/08-15r.txt - full translation

---

web/www/horas/Italiano/Tempora/Quad2-2.txt

Italian/Quad2-2 - repair #465 comment by @rl1234567890 (#1)

---

web/cgi-bin/horas/specials.pl
web/www/horas/English/Sancti/12-11.txt
web/www/horas/English/Sancti/12-13.txt

Commemoratio fixes

---

web/www/horas/Polski/Commune/C10.txt
web/www/horas/Polski/Commune/C11.txt
web/www/horas/Polski/Commune/C11p.txt
web/www/horas/Polski/Commune/C12.txt
web/www/horas/Polski/Commune/C2.txt
web/www/horas/Polski/Commune/C3p.txt
web/www/horas/Polski/Commune/C4.txt
web/www/horas/Polski/Commune/C4a.txt
web/www/horas/Polski/Commune/C4p.txt
web/www/horas/Polski/Commune/C8.txt
web/www/horas/Polski/Tempora/C10.txt

- Officium Dedicationis has been added (without Matins)
- Officium Parvum B.M.V Per Annum has been added
- Latin texts have been removed from Polish Commune files
- some more translations

Polski/Commune - additions and cleaning

---

web/www/horas/Polski/Martyrologium/08-29.txt
web/www/horas/Polski/Sancti/09-21.txt

Polish translations: fixes

---

web/www/horas/English/Commune/C1.txt
web/www/horas/English/Commune/C1a.txt

English files: conform previous latin changes in C1a

---

web/www/horas/English/Tempora/Quad6-4.txt
web/www/horas/English/Tempora/Quad6-6r.txt
web/www/horas/Italiano/Tempora/Quad6-4.txt
web/www/horas/Italiano/Tempora/Quad6-6r.txt
web/www/horas/Latin/Tempora/Quad6-4.txt
web/www/horas/Latin/Tempora/Quad6-6r.txt
web/www/horas/Magyar/Tempora/Quad6-4.txt
web/www/horas/Magyar/Tempora/Quad6-6r.txt
web/www/horas/Polski/Tempora/Quad6-4.txt
web/www/horas/Polski/Tempora/Quad6-6r.txt

Fix #596 + typos

---

web/www/horas/Latin/Commune/C1v.txt
web/www/horas/Latin/Sancti/05-03.txt
web/www/horas/Latin/Sancti/05-08.txt
web/www/horas/Latin/Sancti/09-01.txt
web/www/horas/Latin/Sancti/09-05.txt
web/www/horas/Latin/Sancti/09-08.txt
web/www/horas/Latin/Sancti/09-14.txt
web/www/horas/Latin/Sancti/09-15.txt
web/www/horas/Latin/Sancti/09-16.txt
web/www/horas/Latin/Sancti/09-17.txt
web/www/horas/Latin/Sancti/09-19.txt
web/www/horas/Latin/Sancti/09-20.txt
web/www/horas/Latin/Sancti/09-20o.txt
web/www/horas/Latin/Sancti/09-22.txt
web/www/horas/Latin/Sancti/09-23.txt
web/www/horas/Latin/Sancti/09-29.txt
web/www/horas/Latin/Tempora/Quad5-5.txt

Latin Sancti files: 09 + other used by them

---

web/www/horas/Polski/Sancti/10-07.txt
web/www/horas/Polski/Sancti/10-07r.txt

Polish files: corrections

---

web/www/horas/Polski/Sancti/05-08.txt
web/www/horas/Polski/Sancti/10-11.txt

Polish files corrections

---

web/www/horas/English/Commune/C10t.txt
web/www/horas/English/Sancti/09-12.txt
web/www/horas/English/Sancti/11-30.txt
web/www/horas/English/Tempora/C10t.txt
web/www/horas/English/Tempora/Quad2-1.txt
web/www/horas/English/Tempora/Quad4-4.txt
web/www/horas/English/Tempora/Quad4-4t.txt
web/www/horas/Polski/Commune/C1ap.txt
web/www/horas/Polski/Commune/C1p.txt
web/www/horas/Polski/Commune/C2p.txt
web/www/horas/Polski/Commune/C3p.txt
web/www/horas/Polski/Commune/C4.txt
web/www/horas/Polski/Commune/C4ap.txt
web/www/horas/Polski/Commune/C4p.txt
web/www/horas/Polski/Commune/C6.txt
web/www/horas/Polski/Sancti/02-02.txt
web/www/horas/Polski/Sancti/09-08.txt
web/www/horas/Polski/Sancti/09-14.txt
web/www/horas/Polski/Sancti/09-15.txt
web/www/horas/Polski/Sancti/11-01.txt
web/www/horas/Polski/Sancti/11-21.txt
web/www/horas/Polski/Sancti/11-30.txt
web/www/horas/Polski/Sancti/12-08.txt
web/www/horas/Polski/Tempora/Adv1-0.txt
web/www/horas/Polski/Tempora/Pent16-0.txt
web/www/horas/Polski/Tempora/Pent20-0.txt
web/www/horas/Polski/Tempora/Pent22-0.txt
web/www/horas/Polski/Tempora/Pent24-0.txt
web/www/horas/Polski/Tempora/Quad5-1.txt
web/www/horas/Polski/Tempora/Quadp1-0.txt

Polish and English Files - add missing stars in Antiphonas

---

web/www/horas/Polski/Tempora/Adv1-0.txt
web/www/horas/Polski/Tempora/Adv1-1.txt
web/www/horas/Polski/Tempora/Adv1-2.txt
web/www/horas/Polski/Tempora/Adv1-3.txt
web/www/horas/Polski/Tempora/Adv1-4.txt
web/www/horas/Polski/Tempora/Adv1-5.txt
web/www/horas/Polski/Tempora/Adv1-6.txt
web/www/horas/Polski/Tempora/Adv2-0.txt
web/www/horas/Polski/Tempora/Adv2-1.txt
web/www/horas/Polski/Tempora/Adv2-2.txt
web/www/horas/Polski/Tempora/Adv2-3.txt
web/www/horas/Polski/Tempora/Adv2-4.txt
web/www/horas/Polski/Tempora/Adv2-5.txt
web/www/horas/Polski/Tempora/Adv2-6.txt
web/www/horas/Polski/Tempora/Adv3-0.txt
web/www/horas/Polski/Tempora/Adv3-1.txt
web/www/horas/Polski/Tempora/Adv3-2.txt
web/www/horas/Polski/Tempora/Adv3-3.txt
web/www/horas/Polski/Tempora/Adv3-4.txt
web/www/horas/Polski/Tempora/Adv3-5.txt
web/www/horas/Polski/Tempora/Adv3-6.txt
web/www/horas/Polski/Tempora/Adv4-0.txt
web/www/horas/Polski/Tempora/Adv4-1.txt
web/www/horas/Polski/Tempora/Adv4-2.txt
web/www/horas/Polski/Tempora/Adv4-3.txt
web/www/horas/Polski/Tempora/Adv4-4.txt
web/www/horas/Polski/Tempora/Adv4-5.txt

Advent Polish translation

---

web/www/horas/Latin/Commune/C12A.txt
web/www/horas/Latin/Commune/C12An.txt

Still few remain, especially commas and capital letters.

Correct typos in Latin/C12A and Latin/C12An

---

web/www/horas/Latin/Sancti/11-04r.txt
web/www/horas/Latin/Sancti/11-08.txt
web/www/horas/Latin/Sancti/11-18o.txt
web/www/horas/Latin/Sancti/11-18r.txt
web/www/horas/Latin/Sancti/11-19.txt
web/www/horas/Latin/Sancti/11-30.txt

Latin November Sancti files - more changes

---

web/www/horas/Polski/Martyrologium/11-24.txt
web/www/horas/Polski/Sancti/11-04r.txt
web/www/horas/Polski/Sancti/12-02.txt
web/www/horas/Polski/Sancti/12-03.txt
web/www/horas/Polski/Sancti/12-05.txt
web/www/horas/Polski/Sancti/12-06.txt
web/www/horas/Polski/Sancti/12-07.txt
web/www/horas/Polski/Sancti/12-08.txt
web/www/horas/Polski/Sancti/12-11.txt
web/www/horas/Polski/Sancti/12-13.txt
web/www/horas/Polski/Sancti/12-16.txt

Polish December Sancti files

---

web/cgi-bin/horas/dialogcommon.pl

* matching groups can be used
* allow to choose line(s) numbered from 1!
eg. `@:Ant Vespera:1`                                                                        
or  `@:Ant Matutinum:9-10`
+AMDG+

Code: improve inclusion substitutions function

---

web/www/horas/Latin/Sancti/01-01.txt
web/www/horas/Latin/Sancti/01-02.txt
web/www/horas/Latin/Sancti/01-02o.txt
web/www/horas/Latin/Sancti/01-03o.txt
web/www/horas/Latin/Sancti/01-04o.txt

Latin files: January - corrections and references

---

web/www/horas/English/Sancti/12-27.txt
web/www/horas/English/Sancti/12-28.txt

English/12-2[78] - restore brackets as in comments #655

---

web/www/horas/horas.dialog

add option Polski as Language1

---

web/www/horas/Polski/Martyrologium/03-04.txt
web/www/horas/Polski/Martyrologium/03-22.txt
web/www/horas/Polski/Martyrologium/12-30.txt
web/www/horas/Polski/Sancti/03-18.txt
web/www/horas/Polski/Sancti/04-04.txt
web/www/horas/Polski/Sancti/04-11.txt
web/www/horas/Polski/Sancti/04-27.txt
web/www/horas/Polski/Sancti/05-02.txt
web/www/horas/Polski/Sancti/06-13.txt
web/www/horas/Polski/Sancti/06-14.txt
web/www/horas/Polski/Sancti/06-18.txt
web/www/horas/Polski/Sancti/07-14.txt
web/www/horas/Polski/Sancti/12-02.txt
web/www/horas/Polski/Sancti/12-13.txt
web/www/horas/Polski/Sancti/12-31.txt

Polish files: typos

---

web/www/horas/Polski/Commune/C2.txt
web/www/horas/Polski/Commune/C6.txt
web/www/horas/Polski/Martyrologium/01-18.txt
web/www/horas/Polski/Psalterium/Prayers.txt
web/www/horas/Polski/Sancti/01-06.txt
web/www/horas/Polski/Sancti/02-22.txt
web/www/horas/Polski/Sancti/04-28.txt
web/www/horas/Polski/Sancti/09-15.txt
web/www/horas/Polski/Sancti/10-DU.txt
web/www/horas/Polski/Sancti/11-30.txt
web/www/horas/Polski/Sancti/12-08.txt
web/www/horas/Polski/Sancti/12-26.txt
web/www/horas/Polski/Sancti/12-28.txt
web/www/horas/Polski/Sancti/12-29.txt
web/www/horas/Polski/Sancti/12-29r.txt
web/www/horas/Polski/Tempora/Nat2-0.txt
web/www/horas/Polski/Tempora/Pent07-6.txt
web/www/horas/Polski/Tempora/Pent11-6.txt
web/www/horas/Polski/Tempora/Quad6-4.txt

Polish files: corrections and cleaning

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/specials.pl
web/cgi-bin/horas/specmatins.pl

Code: translate Alleluia

---

web/www/horas/Polski/Psalterium/Translate.txt
web/www/horas/Polski/Sancti/01-01.txt
web/www/horas/Polski/Sancti/01-06.txt
web/www/horas/Polski/Sancti/02-02.txt
web/www/horas/Polski/Sancti/03-25.txt
web/www/horas/Polski/Sancti/04-29.txt
web/www/horas/Polski/Sancti/12-21.txt
web/www/horas/Polski/Sancti/12-24.txt
web/www/horas/Polski/Tempora/Epi1-0.txt
web/www/horas/Polski/Tempora/Epi2-0.txt
web/www/horas/Polski/Tempora/Nat1-0.txt
web/www/horas/Polski/Tempora/Pasc5-2.txt
web/www/horas/Polski/Tempora/Pasc5-5.txt
web/www/horas/Polski/Tempora/Pasc5-6.txt
web/www/horas/Polski/Tempora/Pasc6-0.txt
web/www/horas/Polski/Tempora/Pent14-0.txt
web/www/horas/Polski/Tempora/Pent15-0.txt
web/www/horas/Polski/Tempora/Quad5-0.txt
web/www/horas/Polski/Tempora/Quad6-0r.txt
web/www/horas/Polski/Tempora/Quad6-3.txt
web/www/horas/Polski/Tempora/Quad6-4r.txt
web/www/horas/Polski/Tempora/Quad6-5r.txt
web/www/horas/Polski/Tempora/Quadp1-0.txt
web/www/horas/Polski/Tempora/Quadp2-0.txt
web/www/horas/Polski/Tempora/Quadp3-0.txt
web/www/horas/Polski/psalms1/Psalm231.txt
web/www/horas/Polski/psalms1/Psalm232.txt
web/www/horas/Polski/psalms1/Psalm233.txt

Polish: translations of Rank, and Canticum

---

web/www/horas/Polski/Commune/C10.txt
web/www/horas/Polski/Martyrologium/02-11.txt
web/www/horas/Polski/Sancti/01-02.txt
web/www/horas/Polski/Sancti/01-18.txt
web/www/horas/Polski/Sancti/02-22.txt
web/www/horas/Polski/Sancti/03-25.txt
web/www/horas/Polski/Sancti/04-11.txt
web/www/horas/Polski/Sancti/06-30.txt
web/www/horas/Polski/Sancti/08-06.txt
web/www/horas/Polski/Sancti/08-30.txt
web/www/horas/Polski/Sancti/11-21.txt
web/www/horas/Polski/Sancti/12-04.txt
web/www/horas/Polski/Sancti/12-26.txt
web/www/horas/Polski/Tempora/Pasc2-1.txt
web/www/horas/Polski/Tempora/Pasc5-0.txt
web/www/horas/Polski/Tempora/Pent01-0.txt
web/www/horas/Polski/psalms1/Psalm210.txt
web/www/horas/Polski/psalms1/Psalm50.txt

Polish files various fixes

---

web/www/horas/Polski/Sancti/01-15.txt
web/www/horas/Polski/Sancti/02-14.txt
web/www/horas/Polski/Sancti/03-24.txt
web/www/horas/Polski/Sancti/04-17.txt
web/www/horas/Polski/Sancti/05-27.txt
web/www/horas/Polski/Sancti/06-29.txt
web/www/horas/Polski/Sancti/08-01.txt
web/www/horas/Polski/Sancti/08-07.txt
web/www/horas/Polski/Sancti/08-20.txt
web/www/horas/Polski/Sancti/08-28.txt
web/www/horas/Polski/Sancti/09-08.txt
web/www/horas/Polski/Sancti/09-15a.txt
web/www/horas/Polski/Sancti/09-23.txt
web/www/horas/Polski/Sancti/11-01.txt
web/www/horas/Polski/Sancti/11-15.txt
web/www/horas/Polski/Tempora/Adv2-0.txt
web/www/horas/Polski/Tempora/Quad5-5Feria.txt

Polish files small fixes

---

web/www/horas/Polski/Tempora/Quad2-4.txt
web/www/horas/Polski/Tempora/Quad3-0.txt
web/www/horas/Polski/Tempora/Quad3-4.txt
web/www/horas/Polski/Tempora/Quad3-5.txt
web/www/horas/Polski/Tempora/Quad5-0.txt
web/www/horas/Polski/Tempora/Quad5-3.txt
web/www/horas/Polski/Tempora/Quad6-0.txt
web/www/horas/Polski/Tempora/Quad6-2.txt
web/www/horas/Polski/Tempora/Quad6-3.txt
web/www/horas/Polski/Tempora/Quadp1-0.txt
web/www/horas/Polski/Tempora/Quadp1-1.txt
web/www/horas/Polski/Tempora/Quadp1-2.txt
web/www/horas/Polski/Tempora/Quadp1-3.txt
web/www/horas/Polski/Tempora/Quadp1-4.txt
web/www/horas/Polski/Tempora/Quadp2-0.txt
web/www/horas/Polski/Tempora/Quadp2-1.txt
web/www/horas/Polski/Tempora/Quadp2-2.txt
web/www/horas/Polski/Tempora/Quadp2-3.txt
web/www/horas/Polski/Tempora/Quadp3-0.txt
web/www/horas/Polski/Tempora/Quadp3-1.txt
web/www/horas/Polski/Tempora/Quadp3-2.txt

Reviewed and corrected by @mbab.

Polish translations (Quad*)

---

web/www/horas/English/Commune/C12.txt
web/www/horas/English/Commune/C12A.txt
web/www/horas/English/Commune/C12N.txt
web/www/horas/Italiano/Commune/C12A.txt
web/www/horas/Italiano/Commune/C12N.txt
web/www/horas/Latin/Commune/C12.txt
web/www/horas/Latin/Commune/C12A.txt
web/www/horas/Latin/Commune/C12N.txt
web/www/horas/Latin/Commune/C12P.txt
web/www/horas/Magyar/Commune/C12.txt
web/www/horas/Magyar/Commune/C12N.txt
web/www/horas/Polski/Commune/C12A.txt
web/www/horas/Polski/Commune/C12N.txt

Latin/C12 - more references, corrections + other languages to conform

---

web/cgi-bin/horas/dialogcommon.pl
web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specials.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/English/Psalterium/Translate.txt
web/www/horas/Latin/Psalterium/Translate.txt
web/www/horas/Magyar/Psalterium/Translate.txt
web/www/horas/Polski/Psalterium/Translate.txt

Code improvement: translation of comments (Antifonas etc.)

---

web/www/horas/Polski/Martyrologium/02-20.txt
web/www/horas/Polski/Martyrologium/05-09.txt
web/www/horas/Polski/Martyrologium/11-19.txt
web/www/horas/Polski/Martyrologium/11-26.txt
web/www/horas/Polski/Sancti/03-04.txt
web/www/horas/Polski/Sancti/04-26.txt
web/www/horas/Polski/Sancti/09-23.txt
web/www/horas/Polski/Sancti/10-07.txt
web/www/horas/Polski/Sancti/12-31o.txt

Polish files additions and corrections

---

web/www/horas/Deutsch/Psalterium/Minor Special.txt
web/www/horas/English/Psalterium/Minor Special.txt
web/www/horas/Italiano/Psalterium/Minor Special.txt
web/www/horas/Latin/Psalterium/Minor Special.txt
web/www/horas/Magyar/Psalterium/Minor Special.txt
web/www/horas/Polski/Psalterium/Minor Special.txt
web/www/horas/Polski/Sancti/03-06.txt
web/www/horas/Polski/Tempora/Quad1-0.txt

Polish files: corrections additions + dot in Quad resposories

---

web/www/horas/Deutsch/Commune/C2p.txt

Officium hangs on day 5-30-2017 german version pre1960.
This fix.
+AMDG+

!!! Hangs prevent

---

web/www/horas/Polski/Tempora/Quad1-0.txt

Polski/Quad1-0 - corrections

---

web/cgi-bin/horas/specmatins.pl
web/www/horas/Deutsch/Psalterium/Translate.txt
web/www/horas/English/Psalterium/Translate.txt
web/www/horas/English/Sancti/05-01r.txt
web/www/horas/Italiano/Psalterium/Translate.txt
web/www/horas/Latin/Psalterium/Translate.txt
web/www/horas/Latin/Sancti/06-28r.txt
web/www/horas/Polski/Psalterium/Translate.txt

Fix #413 and other

---

web/www/horas/Polski/Tempora/Pent02-5.txt
web/www/horas/Polski/Tempora/Quad1-1.txt
web/www/horas/Polski/Tempora/Quad1-2.txt
web/www/horas/Polski/Tempora/Quad1-5.txt
web/www/horas/Polski/Tempora/Quad1-6.txt
web/www/horas/Polski/Tempora/Quad2-0.txt
web/www/horas/Polski/Tempora/Quad2-1.txt
web/www/horas/Polski/Tempora/Quad2-2.txt
web/www/horas/Polski/Tempora/Quad2-3.txt
web/www/horas/Polski/Tempora/Quad2-4.txt
web/www/horas/Polski/Tempora/Quad2-5.txt
web/www/horas/Polski/Tempora/Quad2-6.txt
web/www/horas/Polski/Tempora/Quad3-0.txt
web/www/horas/Polski/Tempora/Quad3-1.txt
web/www/horas/Polski/Tempora/Quad3-2.txt
web/www/horas/Polski/Tempora/Quad3-3.txt
web/www/horas/Polski/Tempora/Quad3-4.txt
web/www/horas/Polski/Tempora/Quad3-5.txt
web/www/horas/Polski/Tempora/Quad3-6.txt
web/www/horas/Polski/Tempora/Quad4-0.txt
web/www/horas/Polski/Tempora/Quad4-1.txt
web/www/horas/Polski/Tempora/Quadp3-3.txt
web/www/horas/Polski/Tempora/Quadp3-4.txt

Polish files: correct Gospel source

---

web/www/horas/Polski/Martyrologium/03-01.txt
web/www/horas/Polski/Martyrologium/03-28.txt

Polski/Mart/03-{01,28} - typos

---

web/www/horas/Polski/Sancti/04-04.txt

Polski/04-04 - corrections

---

web/www/horas/Polski/Sancti/08-06.txt
web/www/horas/Polski/Sancti/09-29.txt
web/www/horas/Polski/Sancti/12-13.txt
web/www/horas/Polski/Tempora/Adv1-2.txt
web/www/horas/Polski/Tempora/Quad2-0.txt
web/www/horas/Polski/Tempora/Quad5-5.txt
web/www/horas/Polski/Tempora/Quad6-6.txt
web/www/horas/Polski/Tempora/Quad6-6r.txt

Polski - add missing stars in Antiphonas and moving some other

---

web/www/horas/English/Tempora/Quad5-4.txt

English/Quad5-4 - correction

---

web/www/horas/Latin/Sancti/03-24.txt
web/www/horas/Latin/Sancti/05-08.txt

Latin - add missing stars in Antiphonas

---

web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/webdia.pl

code - repair html output

---

web/www/horas/Polski/Commune/C1p.txt
web/www/horas/Polski/Psalterium/Major Special.txt

Polish files update

---

web/www/horas/Latin/Commune/C12P.txt

C12P - correct oratio in Matutinum and Laudes

---

web/cgi-bin/horas/horas.pl

Code - Benedicamus, translation of Alleluia.

---

web/www/horas/Polski/Commune/C3.txt

Polski/C3 - more translation

---

web/www/horas/Deutsch/Psalterium/Major Special.txt
web/www/horas/English/Psalterium/Major Special.txt
web/www/horas/Italiano/Psalterium/Major Special.txt
web/www/horas/Latin/Psalterium/Major Special.txt
web/www/horas/Magyar/Psalterium/Major Special.txt

*/Major Special - red N for Pope name in Lithany

---

web/www/horas/Latin/Tabulae/K1942.txt
web/www/horas/Latin/Tempora/Pasc6-5.txt

Correction of errors: Kalendar '42 + Pasc6-5

---

web/www/horas/Latin/Tempora/Pasc7-5.txt
web/www/horas/Latin/Tempora/Pasc7-6.txt
web/www/horas/Latin/Tempora/Pent01-4.txt

Latin files - restore stars in antifonas

---

web/www/horas/Latin/Sancti/05-19.txt

Latin/05-19 - corrections

---

web/cgi-bin/horas/horas.pl
web/www/horas/Deutsch/Psalterium/Prayers.txt
web/www/horas/English/Psalterium/Prayers.txt
web/www/horas/Italiano/Psalterium/Prayers.txt
web/www/horas/Latin/Ordinarium/Completorium.txt
web/www/horas/Latin/Ordinarium/Completoriump.txt
web/www/horas/Latin/Ordinarium/Tertia.txt
web/www/horas/Latin/Ordinarium/Tertiap.txt
web/www/horas/Latin/Psalterium/Prayers.txt
web/www/horas/Latin/Psalterium/Psalmi matutinum.txt
web/www/horas/Magyar/Psalterium/Prayers.txt
web/www/horas/Polski/Psalterium/Prayers.txt

code - repair 'Domine exaudi' in Prima and Completa

---

web/www/horas/Latin/Commune/C6.txt
web/www/horas/Latin/Sancti/01-23o.txt
web/www/horas/Latin/Sancti/02-06o.txt
web/www/horas/Latin/Sancti/07-20o.txt
web/www/horas/Latin/Sancti/07-24r.txt

Latin/C6 - add Oratio1 'Indulgentiam nobis'

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/specials.pl

Code - fix #752

---

web/cgi-bin/horas/horas.pl
web/www/horas/English/Psalterium/Translate.txt
web/www/horas/Latin/Psalterium/Translate.txt
web/www/horas/Polski/Psalterium/Translate.txt

added English and Polish translation
+AMDG+

Code - add subheader 'Antiphona finalis B.M.V.'

---

web/www/horas/English/Sancti/08-19.txt
web/www/horas/Italiano/Sancti/08-19.txt
web/www/horas/Latin/Sancti/08-19.txt
web/www/horas/Magyar/Sancti/08-19.txt
web/www/horas/Polski/Sancti/08-19.txt

08-19 - correction of commemoratio

---

web/www/horas/Latin/Sancti/10-07a.txt

the same content as 10-07t, except for the rank (simplex "1" here, 1.1 there)

Introduce cross-refs to 10-07a

---

web/www/horas/Latin/Sancti/08-15.txt
web/www/horas/Latin/Sancti/09-17.txt
web/www/horas/Latin/Tempora/Quad5-5Feria.txt
web/www/horas/Latin/Tempora/Quad6-0.txt

These commits fix recently a few introduced errors: missing words and typos. The first day affected by these fixes is September 17.

Latin typos, including September 17

---

web/www/horas/Latin/Psalterium/Major Special.txt

see issue #785 
I hope the combination with ~ achieves showing the "quotations" in black.

A cunctis rubric

---

web/www/horas/English/Sancti/05-03.txt
web/www/horas/English/Sancti/09-14.txt

English/05-03 09-14 - remove section which are links in Latin

---

web/www/horas/English/Sancti/06-29.txt
web/www/horas/Latin/Commune/C1.txt
web/www/horas/Latin/Sancti/06-29.txt

Latin,English/* - punctation, cleaning

---

web/cgi-bin/horas/specials.pl

code: red initial in Oratio

---

web/www/horas/Latin/Sancti/05-08.txt

Alleluja is added automaticaly in minor hours Responsories, as it is always
in Eastertime, as they are use in other days eg. October 2nd, removing it
is neccessary.
+AMDG+

Latin/05-08 - partially revert 7b6a1f4d

---

web/www/horas/Polski/Sancti/12-26.txt
web/www/horas/Polski/Sancti/12-27.txt
web/www/horas/Polski/Sancti/12-28.txt
web/www/horas/Polski/Sancti/12-29.txt
web/www/horas/Polski/Tempora/Nat1-0.txt

I'm unsure if they work. I couldn't find any office they would be included in. And I see that English files don't have such references, which can render the Polish ones not working. I need them to be correct, though, so I could use these files to generate an e-book (they caused the parser to throw an error while resolving the references).

Fix some references in Polish

---

web/www/horas/Polski/Martyrologium/09-25.txt
web/www/horas/Polski/Martyrologium/10-16.txt
web/www/horas/Polski/Psalterium/Psalmi major.txt
web/www/horas/Polski/Sancti/10-07.txt
web/www/horas/Polski/Sancti/10-24.txt
web/www/horas/Polski/Tempora/083-5.txt
web/www/horas/Polski/Tempora/093-4.txt
web/www/horas/Polski/psalms1/Psalm260.txt

Polish files updates

---

web/www/horas/English/Sancti/01-06.txt
web/www/horas/English/Sancti/01-25.txt
web/www/horas/English/Sancti/02-02.txt
web/www/horas/English/Sancti/03-24.txt
web/www/horas/English/Sancti/03-25.txt
web/www/horas/English/Sancti/05-01c.txt
web/www/horas/English/Sancti/05-01r.txt
web/www/horas/English/Sancti/05-08.txt
web/www/horas/English/Sancti/06-24.txt
web/www/horas/English/Sancti/06-30.txt
web/www/horas/English/Sancti/07-01.txt
web/www/horas/English/Sancti/08-06.txt
web/www/horas/English/Sancti/08-10.txt
web/www/horas/English/Sancti/09-15.txt
web/www/horas/English/Sancti/10-02.txt
web/www/horas/English/Sancti/10-07.txt
web/www/horas/English/Sancti/11-01.txt
web/www/horas/English/Sancti/11-30.txt
web/www/horas/English/Tempora/Epi1-0.txt
web/www/horas/English/Tempora/Nat2-0.txt
web/www/horas/English/Tempora/Pent01-0.txt
web/www/horas/English/Tempora/Pent02-0.txt

English/* - remove Capitulum Nona which are simple links in Latin + few corrections

---

web/www/horas/Latin/Sancti/06-30.txt
web/www/horas/Latin/Sancti/08-17t.txt
web/www/horas/Latin/Tempora/Pasc3-0t.txt
web/www/horas/Latin/Tempora/Pasc3-2Feria.txt
web/www/horas/Latin/Tempora/Quad2-0t.txt
web/www/horas/Latin/Tempora/Quad3-5t.txt
web/www/horas/Latin/Tempora/Quad4-0t.txt

Latin files corrections

---

web/cgi-bin/horas/specials.pl

code: fix #373

---

web/www/horas/Latin/Commune/C6.txt
web/www/horas/Latin/Tempora/Pasc3-0t.txt

Latin files update

---

web/www/horas/English/Martyrologium/04-14.txt
web/www/horas/English/Sancti/10-24.txt
web/www/horas/English/Tempora/Pasc2-0.txt
web/www/horas/English/Tempora/Pasc5-0.txt
web/www/horas/Latin/Commune/C9.txt
web/www/horas/Latin/Sancti/10-03.txt
web/www/horas/Latin/Sancti/12-27.txt
web/www/horas/Latin/Sancti/12-28.txt
web/www/horas/Latin/Sancti/12-29.txt
web/www/horas/Latin/Sancti/12-31.txt
web/www/horas/Latin/Tempora/093-5.txt
web/www/horas/Latin/Tempora/Epi1-2.txt
web/www/horas/Latin/Tempora/Epi1-3.txt
web/www/horas/Latin/Tempora/Epi1-6.txt
web/www/horas/Latin/Tempora/Nat2-0.txt
web/www/horas/Latin/Tempora/Pasc0-3.txt
web/www/horas/Latin/Tempora/Pasc1-4.txt
web/www/horas/Latin/Tempora/Pasc4-0.txt
web/www/horas/Latin/Tempora/Pasc5-0.txt
web/www/horas/Latin/Tempora/Pent11-3.txt
web/www/horas/Latin/Tempora/Pent13-0.txt
web/www/horas/Latin/Tempora/Quad5-4.txt
web/www/horas/Latin/Tempora/Quad6-3.txt
web/www/horas/Latin/Tempora/Quad6-4.txt
web/www/horas/Latin/Tempora/Quad6-5.txt
web/www/horas/Latin/Tempora/Quad6-6.txt
web/www/horas/Latin/Tempora/Quadp2-0.txt
web/www/horas/Latin/Tempora/Quadp3-0.txt

Most of there correct things like typos, orthography, punctuation.
For the 04-14 English martyrology, a correction had been made by someone else to make it clearer, but this correction made it no longer correspond to the Latin and the facts. I restored the original wording of the English translation (Marquis of Bute) but changed the punctuation to make it clear that it was Fronto who was famous for holiness, and not all his monks.

Corrections since September 2017

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/specials.pl

code: omit star in second Antiphona and in Commemoratio

---

web/www/horas/Polski/Commune/C1.txt
web/www/horas/Polski/Commune/C9.txt
web/www/horas/Polski/Psalterium/Major Special.txt
web/www/horas/Polski/Psalterium/Psalmi major.txt
web/www/horas/Polski/Sancti/01-06.txt
web/www/horas/Polski/Tempora/Nat2-0.txt
web/www/horas/Polski/Tempora/Pent01-4.txt
web/www/horas/Polski/Tempora/Quad6-6r.txt
web/www/horas/Polski/psalms1/Psalm17.txt
web/www/horas/Polski/psalms1/Psalm70.txt

Polski/* - remove superfluous stars in Antiphonas

---

web/www/horas/Latin/Sancti/02-05.txt
web/www/horas/Polski/Sancti/02-05.txt

Latin|Polski/02-05 - correction

---

web/www/horas/Polski/psalms1/Psalm112.txt
web/www/horas/Polski/psalms1/Psalm118.txt
web/www/horas/Polski/psalms1/Psalm28.txt

* concerns Psalms 28 and 112
* Psalm 118: missing space in verse 2

Consistency of numbering of verses

---

web/cgi-bin/horas/specials.pl

code: fix #161

---

web/www/missa/Polski/Commune/C4.txt
web/www/missa/Polski/Sancti/05-02.txt
web/www/missa/Polski/Sancti/07-16.txt
web/www/missa/Polski/Sancti/10-17.txt
web/www/missa/Polski/Sancti/10-28.txt
web/www/missa/Polski/Sancti/11-04r.txt
web/www/missa/Polski/Sancti/11-10.txt
web/www/missa/Polski/Sancti/11-11.txt
web/www/missa/Polski/Sancti/11-12.txt
web/www/missa/Polski/Sancti/11-13.txt
web/www/missa/Polski/Sancti/11-14.txt
web/www/missa/Polski/Sancti/11-16.txt
web/www/missa/Polski/Sancti/11-17.txt
web/www/missa/Polski/Sancti/11-18r.txt
web/www/missa/Polski/Sancti/11-20.txt
web/www/missa/Polski/Sancti/11-21.txt
web/www/missa/Polski/Sancti/11-30.txt
web/www/missa/Polski/Sancti/12-07.txt
web/www/missa/Polski/Tempora/C10.txt
web/www/missa/Polski/Tempora/C10c.txt

Removing '\xc2\xad' characters

Polish Mass - removing excessive dashes

---

web/www/horas/Francais/psalms1/Psalm1.txt

Est-ce bien ? Can any French native speaker review my changes?

Update Psalm1.txt (French)

---

web/www/horas/Polski/psalms1/Psalm94.txt

Based on `Polski/Psalterium/Invitatorium1.txt` with missing verses 6 and 7.

Added plain Polish translation of Psalm 94

---

web/www/horas/English/Commune/C9.txt
web/www/horas/English/Sancti/11-02.txt
web/www/horas/Italiano/Commune/C9.txt
web/www/horas/Italiano/Sancti/11-02.txt
web/www/horas/Latin/Commune/C9.txt
web/www/horas/Latin/Sancti/11-02.txt
web/www/horas/Magyar/Commune/C9.txt
web/www/horas/Magyar/Sancti/11-02.txt
web/www/horas/Polski/Sancti/11-02.txt

and remove [Oratio Matutinum] from vernaculars
(revert changes in C9)
+AMDG+

Fix #840: change Latin 11-02 rather then C9

---

web/www/horas/Deutsch/psalms1/Psalm3.txt
web/www/horas/Deutsch/psalms1/Psalm6.txt
web/www/horas/English/psalms1/Psalm3.txt
web/www/horas/English/psalms1/Psalm4.txt
web/www/horas/English/psalms1/Psalm5.txt
web/www/horas/English/psalms1/Psalm6.txt
web/www/horas/Francais/psalms1/Psalm3.txt
web/www/horas/Francais/psalms1/Psalm4.txt
web/www/horas/Francais/psalms1/Psalm5.txt
web/www/horas/Francais/psalms1/Psalm6.txt
web/www/horas/Italiano/psalms1/Psalm3.txt
web/www/horas/Italiano/psalms1/Psalm4.txt
web/www/horas/Italiano/psalms1/Psalm5.txt
web/www/horas/Italiano/psalms1/Psalm6.txt
web/www/horas/Latin/psalms1/Psalm3.txt
web/www/horas/Latin/psalms1/Psalm4.txt
web/www/horas/Latin/psalms1/Psalm5.txt
web/www/horas/Latin/psalms1/Psalm6.txt
web/www/horas/Magyar/psalms1/Psalm3.txt
web/www/horas/Magyar/psalms1/Psalm4.txt
web/www/horas/Magyar/psalms1/Psalm5.txt
web/www/horas/Magyar/psalms1/Psalm6.txt
web/www/horas/Polski/psalms1/Psalm3.txt
web/www/horas/Polski/psalms1/Psalm4.txt
web/www/horas/Polski/psalms1/Psalm5.txt
web/www/horas/Polski/psalms1/Psalm6.txt

Still simple updates with no references to parts of the psalms.

Numbering of verses in Psalms 3-6

---

web/www/horas/Deutsch/Psalterium/Psalmi matutinum.txt
web/www/horas/Deutsch/Psalterium/Psalmi minor.txt
web/www/horas/Deutsch/psalms1/Psalm9.txt
web/www/horas/English/Psalterium/Psalmi matutinum.txt
web/www/horas/English/Psalterium/Psalmi minor.txt
web/www/horas/English/psalms1/Psalm9.txt
web/www/horas/Francais/psalms1/Psalm9.txt
web/www/horas/Italiano/Psalterium/Psalmi matutinum.txt
web/www/horas/Italiano/Psalterium/Psalmi minor.txt
web/www/horas/Italiano/psalms1/Psalm9.txt
web/www/horas/Latin/Psalterium/Psalmi matutinum.txt
web/www/horas/Latin/Psalterium/Psalmi minor.txt
web/www/horas/Latin/psalms1/Psalm9.txt
web/www/horas/Magyar/Psalterium/Psalmi matutinum.txt
web/www/horas/Magyar/Psalterium/Psalmi minor.txt
web/www/horas/Magyar/psalms1/Psalm9.txt
web/www/horas/Polski/Psalterium/Psalmi matutinum.txt
web/www/horas/Polski/Psalterium/Psalmi minor.txt
web/www/horas/Polski/psalms1/Psalm9.txt

Changes in references:
9(1-11) → 9(2-11)
9(1-20) → 9(2-19)

Numbering of verses in Psalm 9 + references

---

web/www/horas/Deutsch/Psalterium/Psalmi minor.txt
web/www/horas/English/psalms1/Psalm8.txt
web/www/horas/Francais/psalms1/Psalm8.txt
web/www/horas/Italiano/psalms1/Psalm8.txt
web/www/horas/Latin/psalms1/Psalm8.txt
web/www/horas/Magyar/psalms1/Psalm8.txt
web/www/horas/Polski/psalms1/Psalm8.txt

German version remains unchanged.

Numbering of verses in Psalm 8

---

web/cgi-bin/horas/specials.pl

code: oratio -> oremus in linked commemoratio eg Laudes DA 12/11

---

web/www/horas/English/Sancti/12-10o.txt
web/www/horas/English/Sancti/12-11t.txt
web/www/horas/English/Sancti/12-13.txt
web/www/horas/Latin/Sancti/12-10o.txt
web/www/horas/Latin/Sancti/12-11t.txt
web/www/horas/Latin/Sancti/12-13.txt
web/www/horas/Polski/Sancti/12-10o.txt
web/www/horas/Polski/Sancti/12-13.txt

 Latin-English-Polski/12-{10o,11t,13} - corrections, update

---

web/www/horas/English/Sancti/01-10.txt
web/www/horas/English/Sancti/01-11.txt
web/www/horas/English/Sancti/02-18.txt
web/www/horas/English/Sancti/08-02o.txt
web/www/horas/English/Sancti/11-19o.txt
web/www/horas/English/Sancti/11-26.txt
web/www/horas/English/Sancti/11-26t.txt
web/www/horas/Latin/Sancti/01-10.txt
web/www/horas/Latin/Sancti/01-11.txt
web/www/horas/Latin/Sancti/01-20.txt
web/www/horas/Latin/Sancti/02-18.txt
web/www/horas/Latin/Sancti/05-26o.txt
web/www/horas/Latin/Sancti/08-02o.txt
web/www/horas/Latin/Sancti/11-19o.txt
web/www/horas/Latin/Sancti/11-26.txt
web/www/horas/Latin/Sancti/11-26t.txt
web/www/horas/Polski/Sancti/01-10.txt
web/www/horas/Polski/Sancti/01-11.txt
web/www/horas/Polski/Sancti/05-26.txt
web/www/horas/Polski/Sancti/05-26o.txt
web/www/horas/Polski/Sancti/08-02o.txt
web/www/horas/Polski/Sancti/11-19.txt
web/www/horas/Polski/Sancti/11-19o.txt
web/www/horas/Polski/Sancti/11-26.txt

Oratio "Infirmitátem nostram" from C2 in Latin/English/Polski

---

web/www/horas/Deutsch/psalms1/Psalm145.txt
web/www/horas/Deutsch/psalms1/Psalm146.txt
web/www/horas/English/psalms1/Psalm145.txt
web/www/horas/English/psalms1/Psalm146.txt
web/www/horas/Francais/psalms1/Psalm145.txt
web/www/horas/Francais/psalms1/Psalm146.txt
web/www/horas/Italiano/psalms1/Psalm145.txt
web/www/horas/Italiano/psalms1/Psalm146.txt
web/www/horas/Latin/psalms1/Psalm145.txt
web/www/horas/Latin/psalms1/Psalm146.txt
web/www/horas/Magyar/psalms1/Psalm145.txt
web/www/horas/Magyar/psalms1/Psalm146.txt
web/www/horas/Polski/psalms1/Psalm145.txt
web/www/horas/Polski/psalms1/Psalm146.txt

And that's all! Psalms 147-150 are ok.
:-)

Numbering of verses in Psalms 145 and 146

---

web/www/horas/Deutsch/psalms1/Psalm144.txt
web/www/horas/English/psalms1/Psalm144.txt
web/www/horas/Francais/psalms1/Psalm144.txt
web/www/horas/Italiano/psalms1/Psalm144.txt
web/www/horas/Latin/Psalterium/Prayers.txt
web/www/horas/Latin/Psalterium/Psalmi major.txt
web/www/horas/Latin/Psalterium/Psalmi minor.txt
web/www/horas/Latin/psalms1/Psalm68.txt
web/www/horas/Magyar/psalms1/Psalm144.txt
web/www/horas/Polski/psalms1/Psalm144.txt

I caught some errors in the new verse numbering that were causing verses to appear in the wrong psalm section. There are also a few typos, and I've eliminated a duplicate section from the Latin `Prayers.txt`. The duplicate section had no effect, but it's tidier to eliminate it.

Verse numbering errors and typos

---

web/www/horas/Latin/Sancti/12-24s.txt

Latin/12-24s - corrections, accents

---

web/www/horas/Polski/psalms1/Psalm211.txt
web/www/horas/Polski/psalms1/Psalm254.txt
web/www/horas/Polski/psalms1/Psalm68.txt
web/www/horas/Polski/psalms1/Psalm85.txt

- numbering in Ps 211
- line endings in Ps 68 and 85
- extra words in Ps 254

Fixes in Polish translations of psalms

---

web/cgi-bin/horas/Cofficium.pl
web/cgi-bin/horas/Pofficium.pl
web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/officium.pl
web/www/horas/horas.dialog
web/www/horas/horas.setup

code: iplement #817

---

web/www/horas/Latin/PiusXII/Invitatorium.txt
web/www/horas/Latin/PiusXII/Invitatorium2.txt
web/www/horas/Latin/PiusXII/Invitatorium3.txt
web/www/horas/Latin/PiusXII/Invitatorium4.txt
web/www/horas/Latin/Sancti/01-25.txt

Latin files: small corrections

---

web/www/horas/English/Sancti/01-25.txt

English/01-25 - align with Latin

---

web/www/horas/English/Sancti/01-25.txt
web/www/horas/Latin/Sancti/01-01.txt
web/www/horas/Latin/Sancti/01-10.txt
web/www/horas/Latin/Sancti/11-26.txt
web/www/horas/Latin/Sancti/12-28.txt
web/www/horas/Latin/Sancti/12-30.txt
web/www/horas/Latin/Tempora/Epi1-0.txt

* One commit removes a failed attempt to fix a problem I had reported (#902).
* Another fixes a recent change to the English version of 01-25 that broke a reference.
* The rest are orthographic corrections to match the *editio typica.*

Orthographic corrections

---

web/www/horas/Polski/Commune/C2.txt
web/www/horas/Polski/Martyrologium/01-27.txt
web/www/horas/Polski/Martyrologium/02-12.txt
web/www/horas/Polski/Martyrologium/02-13.txt
web/www/horas/Polski/Martyrologium/06-21.txt
web/www/horas/Polski/Sancti/02-02.txt
web/www/horas/Polski/psalms1/Psalm215.txt

Polish files small corrections

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/specmatins.pl

Implement #817 missing parts

---

web/www/horas/Polski/Sancti/05-01r.txt
web/www/horas/Polski/Tempora/091-4.txt
web/www/horas/Polski/Tempora/113-4.txt
web/www/horas/Polski/Tempora/113-6.txt
web/www/horas/Polski/Tempora/Adv1-2.txt
web/www/horas/Polski/Tempora/Adv2-6.txt
web/www/horas/Polski/Tempora/Epi4-5.txt
web/www/horas/Polski/Tempora/Pent04-3.txt
web/www/horas/Polski/Tempora/Pent05-3.txt
web/www/horas/Polski/Tempora/Pent08-2.txt
web/www/horas/Polski/Tempora/Quad2-0.txt

Polski/* - typos

---

web/www/horas/Polski/Tempora/Quad1-0.txt
web/www/horas/Polski/Tempora/Quad2-0.txt

Polski/Quad[12]-0 - more translation + cleaning

---

web/cgi-bin/horas/horascommon.pl
web/www/horas/English/Commune/C12A.txt
web/www/horas/Italiano/Commune/C12A.txt
web/www/horas/Latin/Commune/C12.txt
web/www/horas/Latin/Commune/C12A.txt
web/www/horas/Latin/Commune/C12N.txt
web/www/horas/Magyar/Commune/C12A.txt

C12 corrections

---

web/www/horas/Polski/Commune/C12A.txt
web/www/horas/Polski/Sancti/01-01.txt

Polish files small update

---

web/www/missa/English/Tempora/Pasc0-2.txt
web/www/missa/English/Tempora/Pasc0-2t.txt
web/www/missa/Magyar/Tempora/Pasc0-2.txt
web/www/missa/Magyar/Tempora/Pasc0-2t.txt

I don't know what word was intended, but other missal use pious here.

Fix typo on Easter Tuesday

---

web/www/missa/English/Tempora/Quad6-0.txt
web/www/missa/Latin/Tempora/Quad6-0.txt

Latin and English: edit trident Palm blessing ceremony

---

web/www/missa/Latin/Sancti/04-23pl.txt
web/www/missa/Latin/Sancti/05-03pl.txt
web/www/missa/Latin/Sancti/05-08pl.txt
web/www/missa/Latin/Sancti/05-24pl.txt
web/www/missa/Latin/Sancti/08-26pl.txt
web/www/missa/Latin/Sancti/11-13pl.txt
web/www/missa/Polski/Commune/C2p.txt
web/www/missa/Polski/Sancti/04-23pl.txt
web/www/missa/Polski/Sancti/05-03pl.txt
web/www/missa/Polski/Sancti/05-24pl.txt
web/www/missa/Polski/Sancti/08-26pl.txt
web/www/missa/Polski/Tempora/C10a.txt

Adding Latin version of specific Polish masses. This commit does not affect divinumofficium explicitly. It is to keep all available translations in one place and divinumofficium seems to be the most comprehensive one across the Internet. Personally they're used as a source to generate missal in epub format.

Adding Latin version of Polish particular propers

---

web/www/horas/Polski/psalms1/Psalm213.txt
web/www/horas/Polski/psalms1/Psalm94.txt

Polski/Psalms* - typos

---

web/www/horas/English/Sancti/06-26.txt
web/www/horas/English/Sancti/07-03.txt
web/www/horas/Latin/Sancti/06-25.txt
web/www/horas/Latin/Sancti/06-26.txt
web/www/horas/Latin/Sancti/06-26t.txt
web/www/horas/Latin/Sancti/06-28.txt
web/www/horas/Latin/Sancti/07-03.txt
web/www/horas/Latin/Sancti/07-05.txt

Latin - Repair missing or superfuous commemoratio Octave of St, John and St. Apostolis

---

web/www/horas/English/Sancti/05-31.txt
web/www/horas/English/Tempora/Pent02-5Feria.txt
web/www/horas/Italiano/Sancti/05-31.txt
web/www/horas/Italiano/Sancti/05-31r.txt
web/www/horas/Latin/Sancti/05-31.txt
web/www/horas/Latin/Tempora/Pent02-5.txt
web/www/horas/Latin/Tempora/Pent04-5o.txt

Latin,English,Italiano - fixes in verses numbering

---

web/www/horas/Latin/Psalterium/Major Special.txt
web/www/horas/Polski/Psalterium/Major Special.txt

Polski,Latin/Major special - corrections

---

web/www/horas/Latin/Sancti/07-07.txt
web/www/horas/Latin/Sancti/07-08.txt
web/www/horas/Latin/Sancti/11-22.txt

Latin/* - add missing stars in Antiphonas

---

web/www/horas/Deutsch/Commune/C2.txt
web/www/horas/Deutsch/Psalterium/Matutinum Special.txt
web/www/horas/Deutsch/Tempora/Nat2-0.txt
web/www/horas/English/CommuneM/C3.txt
web/www/horas/English/Psalterium/Matutinum Special.txt
web/www/horas/English/TemporaM/Pasc7-0.txt
web/www/horas/Italiano/Psalterium/Matutinum Special.txt
web/www/horas/Italiano/Sancti/08-22r.txt
web/www/horas/Italiano/Sancti/12-25.txt
web/www/horas/Italiano/Sancti/12-30.txt
web/www/horas/Italiano/Sancti/12-30o.txt
web/www/horas/Italiano/SanctiM/12-25.txt
web/www/horas/Italiano/Tempora/Nat1-0.txt
web/www/horas/Italiano/TemporaM/Adv1-0.txt
web/www/horas/Italiano/TemporaM/Adv2-0.txt
web/www/horas/Italiano/TemporaM/Adv3-0.txt
web/www/horas/Italiano/TemporaM/Adv4-0.txt
web/www/horas/Latin/Commune/C2.txt
web/www/horas/Latin/Psalterium/Matutinum Special.txt
web/www/horas/Latin/SanctiM/02-05.txt
web/www/horas/Magyar/Psalterium/Matutinum Special.txt
web/www/horas/Polski/Psalterium/Matutinum Special.txt
web/www/horas/Polski/Sancti/03-24.txt
web/www/horas/Polski/Sancti/12-26.txt
web/www/horas/Polski/Tempora/Adv2-0.txt
web/www/horas/Polski/Tempora/Adv3-0.txt
web/www/horas/Polski/Tempora/Epi1-0.txt
web/www/horas/Polski/Tempora/Epi2-0.txt
web/www/horas/Polski/Tempora/Pasc3-0.txt
web/www/horas/Polski/Tempora/Pent01-0.txt

Correction of red initials

---

web/www/horas/Deutsch/Sancti/12-13.txt
web/www/horas/English/Sancti/12-13.txt
web/www/horas/Help/Rubrics/R01.txt
web/www/horas/Help/Rubrics/rubrics.txt
web/www/horas/Italiano/Sancti/12-13.txt
web/www/horas/Latin/Sancti/12-13.txt
web/www/horas/Polski/Sancti/12-13.txt

*/12-13 - no octava comm. for 1570 and 1955 + typos in help/rubrics

---

web/www/missa/English/Ordo/Ordo.txt

In Missa Defunctorum, Gospel, English

Remove superfluous blessing

---

web/www/horas/Latin/Sancti/02-09o.txt
web/www/horas/Latin/Sancti/05-29o.txt
web/www/horas/Latin/Sancti/06-12o.txt
web/www/horas/Latin/Sancti/06-19o.txt
web/www/horas/Latin/Sancti/07-12o.txt

Latin/* - replace English words in the titles of the feasts with Latin

---

web/www/horas/Latin/Psalterium/Psalmi major.txt

Latin/Psalmi major - Trident antiphonas corrections

---

web/www/horas/Latin/Psalterium/Psalmi major.txt

Latin/Psalmi major - missing character

---

web/www/horas/Espanol/Psalterium/Prayers
web/www/horas/Espanol/psalms1/Psalm1.txt
web/www/horas/Espanol/psalms1/Psalm119.txt
web/www/horas/Espanol/psalms1/Psalm120.txt
web/www/horas/Espanol/psalms1/Psalm121.txt
web/www/horas/Espanol/psalms1/Psalm122.txt
web/www/horas/Espanol/psalms1/Psalm123.txt
web/www/horas/Espanol/psalms1/Psalm124.txt
web/www/horas/Espanol/psalms1/Psalm2.txt
web/www/horas/Espanol/psalms1/Psalm3.txt
web/www/horas/Espanol/psalms1/Psalm4.txt
web/www/horas/Espanol/psalms1/Psalm5.txt
web/www/horas/Espanol/psalms1/Psalm6.txt
web/www/horas/Espanol/psalms1/Psalm7.txt

- Minor changes to uploaded psalms,
- Adding psalms 6, 7, 119-124.

More psalms

---

web/www/horas/Latin/Martyrologium/03-21.txt
web/www/horas/Latin/Martyrologium1955R/03-21.txt

Latin/Mart*/03-21 - change encoding to uft-8

---

web/www/horas/Polski/Martyrologium/04-02.txt
web/www/horas/Polski/Psalterium/Major Special.txt

Update Polish files

---

web/cgi-bin/horas/specials.pl

Fix in code repairs also other missing initial issues.
+AMDG+

code: fix #1115

---

web/www/missa/Italiano/Ordo/Ordo.txt

Mass/Italian/Ordo - fix #1118 and #927

---

Dockerfile
docker/apache/httpd.conf

Working on a Dockerfile for the app to allow both easier development (for those who wish to use it) and future deployment.
Would love input if others have docker experience or thoughts.
Left todo before merge:

Dockerfile for running app in Docker [WIP]

---

Dockerfile

Fixing the maintainer from PR #1123 since I'll be the one maintaining our production environment and docker file

Fixing maintainer for dockerfile

---

README.md
docker-compose-prod.yml

Got docker hub autobuilds working, so moved from Quay to Docker Hub.

Change from Quay to Dockerhub

---

web/www/missa/English/Tempora/Quad6-6t.txt
web/www/missa/Magyar/Tempora/Quad6-6t.txt

"His is risen" → "He is risen"

---

web/cgi-bin/horas/specials.pl

code: repair Paschal doxology in Trident1570

---

web/www/horas/Latin/Commune/C1.txt
web/www/horas/Latin/Commune/C1p.txt
web/www/horas/Latin/Commune/C2.txt
web/www/horas/Latin/Commune/C2p.txt
web/www/horas/Latin/Commune/C3.txt
web/www/horas/Latin/Commune/C3p.txt
web/www/horas/Latin/Commune/C4p.txt
web/www/horas/Latin/Commune/C6p.txt
web/www/horas/Latin/Psalterium/Mariaant.txt
web/www/horas/Latin/Psalterium/Prayers.txt
web/www/horas/Latin/Psalterium/Psalmi matutinum.txt
web/www/horas/Latin/Psalterium/Psalmi minor.txt
web/www/horas/Latin/Sancti/05-01c.txt
web/www/horas/Latin/Sancti/05-25t.txt
web/www/horas/Latin/Sancti/05-31.txt
web/www/horas/Latin/Sancti/05-31t.txt
web/www/horas/Latin/Sancti/09-14.txt
web/www/horas/Latin/Sancti/09-29.txt
web/www/horas/Latin/Sancti/11-21.txt
web/www/horas/Latin/Sancti/12-08o.txt
web/www/horas/Latin/Tempora/Pasc2-1.txt
web/www/horas/Latin/Tempora/Pasc3-5.txt
web/www/horas/Latin/Tempora/Pasc4-0.txt
web/www/horas/Latin/Tempora/Pasc6-0.txt

 Latin/* - unification of "Allelúja"

---

web/cgi-bin/horas/specials.pl

code: fix red initial in commemoratio

---

web/www/horas/Latin/Sancti/06-24.txt
web/www/horas/Latin/Sancti/06-26.txt
web/www/horas/Latin/Sancti/06-27.txt
web/www/horas/Latin/Sancti/06-28t.txt

Latin -  St John Octava corrections

---

web/www/horas/Latin/Sancti/01-12.txt
web/www/horas/Latin/Sancti/06-29.txt
web/www/horas/Latin/Sancti/07-04.txt
web/www/horas/Latin/Sancti/07-06.txt
web/www/horas/Latin/Sancti/09-13.txt
web/www/horas/Latin/Sancti/11-03.txt
web/www/horas/Latin/Sancti/11-05.txt
web/www/horas/Latin/Sancti/11-06.txt
web/www/horas/Latin/Sancti/11-07.txt
web/www/horas/Latin/Sancti/11-08.txt
web/www/horas/Latin/Sancti/12-09.txt
web/www/horas/Latin/Sancti/12-10.txt
web/www/horas/Latin/Sancti/12-12.txt
web/www/horas/Latin/Sancti/12-14.txt
web/www/horas/Latin/Sancti/12-15.txt
web/www/horas/Latin/Tempora/Quad6-3.txt

Latin/* - correction of conditionals

---

web/www/horas/English/Sancti/07-11o.txt
web/www/horas/Polski/Sancti/07-11.txt

*/07-11{o} - corrections

---

web/www/horas/Polski/Sancti/07-23.txt

Source: sent by a user.
I'm unsure of the last sentence ('Ille enim confírmare jubétur fratres suos').
The translation provided is not 100% accurate.
Right now I'd prefer to leave it as-is (it's a very good translation anyway).
UPDATE: I've changed the translation of this sentence to a more literal one.

Add 07-23.txt readings in Polish

---

web/www/horas/Polski/Sancti/07-29.txt

Add some Pent07-0.txt readings in Polish

---

web/www/horas/Polski/Sancti/08-03.txt

Add some 08-03.txt readings in Polish

---

web/www/horas/English/Psalterium/Major Special.txt

More changes of periods to commas in the Short Chapter from 2 Cor for Vespers.

More period to comma changes.

---

web/www/horas/Deutsch/Sancti/08-01.txt
web/www/horas/English/Sancti/08-01.txt
web/www/horas/Latin/Sancti/08-01.txt
web/www/horas/Polski/Sancti/08-01.txt

*/08-01 - updates

---

web/www/horas/Polski/Tempora/081-0.txt
web/www/horas/Polski/Tempora/Pent08-0.txt

Add 081-0 and Pent08-0 readings in Polish

---

web/www/horas/Polski/Sancti/08-06.txt

Polski/08-06 - corrections

---

web/www/horas/English/Sancti/08-10.txt
web/www/horas/Latin/Sancti/08-10.txt

*/10-08 - corrections

---

web/www/horas/English/Sancti/08-10.txt
web/www/horas/English/Sancti/08-11t.txt
web/www/horas/Latin/Sancti/08-10.txt
web/www/horas/Latin/Sancti/08-11t.txt
web/www/horas/Polski/Sancti/08-10.txt
web/www/horas/Polski/Sancti/08-11t.txt

Corrections in Commemoratio Ss. Mártyrum Tiburtii et Susannæ

---

web/www/horas/English/Sancti/08-13t.txt
web/www/horas/Latin/Sancti/08-13t.txt
web/www/horas/Polski/Sancti/08-13t.txt

Corrections in Commemoratio Ss. Mártyrum Hippólyti et Cassiáni

---

web/www/horas/English/Sancti/08-13t.txt
web/www/horas/English/Sancti/08-14.txt
web/www/horas/English/Sancti/08-14t.txt
web/www/horas/Latin/Sancti/08-13t.txt
web/www/horas/Latin/Sancti/08-14.txt
web/www/horas/Latin/Sancti/08-14t.txt
web/www/horas/Polski/Sancti/08-13t.txt
web/www/horas/Polski/Sancti/08-14.txt
web/www/horas/Polski/Sancti/08-14t.txt

Corrections in Commemoratio S. Eusebii

---

web/www/horas/Help/Rubrics/Tables 1960.txt

Update Tables 1960.txt

---

web/www/horas/Espanol/Psalterium/Major Special.txt

Update Major Special.txt

---

web/www/horas/Espanol/Psalterium/Psalmi major.txt

Update Psalmi major.txt

---

web/www/horas/Espanol/Psalterium/Matutinum Special.txt

Update Matutinum Special.txt

---

web/cgi-bin/horas/specials.pl

code: digest space to assume red capital in Oratio

---

web/www/horas/Portugues/psalms1/Psalm143.txt
web/www/missa/Portugues/Ordo/Prayers.txt

Correction to psalm 143; add portuguese to missa folder and file Prayers.txt to ordo

Correction Psalm & Add portuguese folder to missa

---

web/www/horas/Latin/Sancti/09-10.txt

Latin/09-10 - add Comm. Oct. Nat. BMV (1910)

---

web/www/horas/Latin/Sancti/09-22.txt
web/www/horas/Latin/Sancti/09-22o.txt

Latin/09-22* - update

---

web/www/horas/English/Sancti/05-08t.txt

Typos in first vespers

---

web/www/horas/Magyar/Sancti/05-08t.txt

Typos in hymn first Vespers for Feast of St. Michael the Archangel

Typos in hymn

---

web/www/horas/English/Sancti/05-08.txt

Typo in hymn

---

web/www/horas/Latin/Commune/C4.txt

Latin/C4 - accents ant typos

---

web/www/horas/Latin/Tempora/Pent07-6.txt
web/www/horas/Polski/Commune/C3.txt

Small corrections

---

web/www/horas/English/Sancti/11-11.txt
web/www/horas/Italiano/Sancti/11-11.txt
web/www/horas/Latin/Sancti/11-11.txt
web/www/horas/Polski/Sancti/11-11.txt

Latin/11-11 - Added 1st Vespers, links in Ant

---

web/www/horas/Latin/Sancti/11-21.txt
web/www/horas/Polski/Sancti/11-21.txt

11-21 - corrections

---

web/www/horas/Latin/Sancti/11-23t.txt

Latin/11-23t - accents

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/popup.pl

which also sets quotidianum and Genitrix in old version
+AMDG+

code: replace jtoi with spell_var 

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/popup.pl

Reverts DivinumOfficium/divinum-officium#1290

Revert "code: replace jtoi with spell_var "

---

web/cgi-bin/horas/horascommon.pl

code: spell_var handling more cases like 'cotídie'

---

web/www/horas/English/Sancti/12-11t.txt
web/www/horas/Francais/Sancti/12-11t.txt
web/www/horas/Italiano/Sancti/12-11t.txt
web/www/horas/Latin/Sancti/12-11t.txt
web/www/horas/Polski/Sancti/12-11t.txt

*/12-11t - remove superflous Commemoratio of day in octava

---

web/www/missa/Latin/Ordo/Ordo67.txt

Changed "in visibilium" to "invisibilium" (Ordo67.txt)

Typo correction (Ordo67.txt)

---

web/www/horas/English/Tempora/Epi2-3.txt

Typo: "santification" spelling

Typo: "santification" spelling

---

web/www/horas/English/Commune/C4.txt

Lower case at beginning of verse in hymn.

Capitalization

---

web/www/missa/English/Sancti/02-02.txt

It did not render correctly on my screen

fix apostraphe character

---

web/www/horas/English/Ordinarium/Prima.txt
web/www/horas/English/Ordinarium/Prima1960.txt

"to do always that is righteous in thy sight." -> "to do always what is righteous in thy sight."

Prima correction: that -> what

---

standalone/tools/epubgen2/epubgen2.sh

-v Parvum B.M.V. generation option for epubgen2.sh
implementing  #1087

-v Parvum B.M.V. generation option

---

web/www/horas/Polski/Psalterium/Psalmi minor.txt
web/www/missa/English/Tempora/Quad5-5.txt
web/www/missa/Latin/Tempora/Quad5-5.txt

Quad5-5 corrections

---

web/www/missa/English/Tempora/Quad6-1.txt

Change "weekness" to "weakness"

Type in Collect (Monday of Holy Week)

---

web/www/missa/English/Tempora/Quad6-1.txt

Change "weekness" to "weakness"

Typo in Collect Holy Week Monday

---

web/www/missa/English/Tempora/Quad6-2.txt

Type in Passion Tuesday Holy Week

---

web/www/missa/English/Tempora/Quad6-2.txt

Typo in Collect Tuesday Holy Week

---

web/www/missa/English/Tempora/Quad6-1.txt

Typo in Prayer over the people in Monday Holy Week

---

web/www/missa/English/Tempora/Quad6-5t.txt

Typo Good Friday

---

web/www/missa/English/Tempora/Pasc0-0.txt

Missing Punctuation

---

web/www/horas/Latin/Tempora/Pasc0-0.txt

Reverts DivinumOfficium/divinum-officium#1569

Revert "Update Pasc0-0.txt"

---

web/www/missa/English/Tempora/Pasc0-3.txt

Trying to make sense of this.  The changes here reflect the 1916 Roman Missal:
"O Lord, we humbly beseech thee that we, receiving thy sacrament with reverent hearts may be cleansed from all our former defilement and become a new creature in thee."

Postcommunion missing text

---

web/www/missa/English/Tempora/Pasc0-5.txt

1962 missal says that double Alleluia Gradual starts Holy Saturday

Remove extra double Alleluia

---

web/www/horas/Latin/Tempora/Pasc1-0.txt

Accents corrected using https://brroman.github.io/accenteur/
and incorrumptibile -> incorruptibile spelling fix verified in
https://books.google.cz/books?id=_w5lAAAAcAAJ&lpg=PA176&ots=u1Aoc2afIs&dq=Sed%20quia%20an%20illud%20corpus%2C%20quod%20videri%20poterat&pg=PA176-IA1#v=onepage&q=Sed%20quia%20an%20illud%20corpus%2C%20quod%20videri%20poterat&f=false

Accent fixes and one spelling fix for Dominica in Albis matins.

---

web/www/horas/English/Sancti/04-30.txt
web/www/horas/English/Tempora/Epi5-3.txt
web/www/horas/English/Tempora/Pasc1-1.txt
web/www/horas/English/TemporaM/Epi5-3.txt
web/www/horas/English/TemporaM/Pasc1-1.txt
web/www/missa/English/Commune/C4bp.txt
web/www/missa/English/Commune/C6bp.txt
web/www/missa/English/Ordo/Ordo.txt
web/www/missa/English/Sancti/04-23.txt
web/www/missa/English/Sancti/04-24.txt
web/www/missa/English/Sancti/04-25.txt
web/www/missa/English/Sancti/04-25c.txt
web/www/missa/English/Sancti/04-25t.txt
web/www/missa/English/Sancti/04-27.txt
web/www/missa/English/Sancti/04-28.txt
web/www/missa/English/Sancti/04-29.txt
web/www/missa/English/Sancti/04-30.txt
web/www/missa/Magyar/Sancti/04-27.txt

Various typos, mostly in Missa.

Dokeefe typos

---

web/www/missa/English/Sancti/05-16.txt

To allow English Oratio to appear?

Remove extra bracket

---

web/cgi-bin/horas/Ckalendar.pl
web/cgi-bin/horas/Cofficium.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/webdia.pl
web/cgi-bin/missa/Ckalendar.pl
web/cgi-bin/missa/Cmissa.pl
web/cgi-bin/missa/kalendar.pl
web/cgi-bin/missa/missa.pl
web/cgi-bin/missa/webdia.pl

Missing form labels and alternative text #1658

Missing form labels and alternative text #1658

---

web/cgi-bin/horas/Ckalendar.pl
web/cgi-bin/horas/Cofficium.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/webdia.pl
web/cgi-bin/missa/Ckalendar.pl
web/cgi-bin/missa/Cmissa.pl
web/cgi-bin/missa/kalendar.pl
web/cgi-bin/missa/missa.pl
web/cgi-bin/missa/webdia.pl

Reverts DivinumOfficium/divinum-officium#1659

Revert "Missing form labels and alternative text #1658"

---

web/cgi-bin/horas/Ckalendar.pl
web/cgi-bin/horas/Cofficium.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/webdia.pl
web/cgi-bin/missa/Ckalendar.pl
web/cgi-bin/missa/Cmissa.pl
web/cgi-bin/missa/kalendar.pl
web/cgi-bin/missa/missa.pl
web/cgi-bin/missa/webdia.pl

Reverts DivinumOfficium/divinum-officium#1660

Revert "Revert "Missing form labels and alternative text #1658""

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specials.pl

Monastic: code changes to conform 1963

---

web/www/horas/Deutsch/Psalterium/Minor Special.txt
web/www/horas/Deutsch/Psalterium/Psalmi major.txt
web/www/horas/English/Psalterium/Minor Special.txt
web/www/horas/English/Psalterium/Psalmi major.txt
web/www/horas/Espanol/Psalterium/Minor Special.txt
web/www/horas/Espanol/Psalterium/Psalmi major.txt
web/www/horas/Francais/Psalterium/Minor Special.txt
web/www/horas/Francais/Psalterium/Psalmi major.txt
web/www/horas/Italiano/Psalterium/Minor Special.txt
web/www/horas/Italiano/Psalterium/Psalmi major.txt
web/www/horas/Latin/Psalterium/Major Special.txt
web/www/horas/Latin/Psalterium/Minor Special.txt
web/www/horas/Latin/Psalterium/Psalmi major.txt
web/www/horas/Magyar/Psalterium/Minor Special.txt
web/www/horas/Magyar/Psalterium/Psalmi major.txt
web/www/horas/Polski/Psalterium/Minor Special.txt
web/www/horas/Polski/Psalterium/Psalmi major.txt

Monastic - changes in Psalterium

---

web/cgi-bin/horas/specials.pl
web/www/horas/English/Psalterium/Doxologies.txt
web/www/horas/Latin/Psalterium/Doxologies.txt

More Trident1570 doxologies, monastic use Trident1570 doxologies

---

web/cgi-bin/horas/horas.pl

code: repair fallback to English/Latin in Ordinarium files

---

web/www/horas/English/Psalterium/Translate.txt
web/www/horas/Italiano/Psalterium/Translate.txt
web/www/horas/Polski/Psalterium/Translate.txt

{English,Italiano,Polski}/Translate - additions

---

web/www/horas/Latin/Tempora/Pasc5-4.txt

The latter checked in Breviarium sanctae Viennensis ecclesiae
and Officia propria dioecesis Molinensis.

Accent fixes (and superationalem -> super rationálem)

---

web/index.html

Reverts DivinumOfficium/divinum-officium#1734

Revert "fix deprecated html on homepage"

---

web/www/horas/Latin/Psalterium/Doxologies.txt

Latin/Doxologies - add old Pentecostes

---

standalone/tools/epubgen2/EofficiumXhtml.pl
standalone/tools/epubgen2/Ewebdia.pl
standalone/tools/epubgen2/epubgen2.sh
web/cgi-bin/missa/Emissa.pl

-m option for epubgen2.sh to include Mass propers

---

web/www/horas/Latin/TemporaM/Pent02-5.txt

MONASTIC Pent02-5 - add Doxology

---

web/cgi-bin/horas/specmatins.pl

code: relax checking Evang. source in Mat. suggested in #1800

---

web/cgi-bin/horas/horascommon.pl

code: Monastic Sunday preference & SS PP vigil on Sunday

---

web/cgi-bin/horas/specials.pl
web/www/horas/Deutsch/Psalterium/Psalmi major.txt
web/www/horas/English/Psalterium/Psalmi major.txt
web/www/horas/Espanol/Psalterium/Psalmi major.txt
web/www/horas/Francais/Psalterium/Psalmi major.txt
web/www/horas/Italiano/Psalterium/Psalmi major.txt
web/www/horas/Latin/Psalterium/Psalmi major.txt
web/www/horas/Magyar/Psalterium/Psalmi major.txt
web/www/horas/Polski/Psalterium/Psalmi major.txt

MONASTIC: antiphonas update

---

web/www/horas/Latin/SanctiM/09-29.txt

MONASTIC 09-29 correction

---

web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/Latin/SanctiM/07-14.txt
web/www/horas/Latin/SanctiM/07-22.txt
web/www/horas/Latin/SanctiM/07-26.txt
web/www/horas/Latin/SanctiM/07-31.txt
web/www/horas/Latin/TemporaM/Pent05-0.txt
web/www/horas/Latin/TemporaM/Pent08-0.txt

Monastic matutinum code and data

---

web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/English/TemporaM/081-0.txt
web/www/horas/English/TemporaM/Pent09-0.txt
web/www/horas/Latin/Commune/C10.txt
web/www/horas/Latin/CommuneM/C10.txt
web/www/horas/Latin/CommuneM/C2.txt
web/www/horas/Latin/CommuneM/C2p.txt
web/www/horas/Latin/CommuneM/C3.txt
web/www/horas/Latin/CommuneM/C4.txt
web/www/horas/Latin/CommuneM/C5.txt
web/www/horas/Latin/CommuneM/C6.txt
web/www/horas/Latin/CommuneM/C7.txt
web/www/horas/Latin/Psalterium/Matutinum Special.txt
web/www/horas/Latin/TemporaM/081-0.txt
web/www/horas/Latin/TemporaM/Pent09-0.txt
web/www/horas/Polski/Psalterium/Matutinum Special.txt
web/www/horas/Polski/Psalterium/Psalmi matutinum.txt
web/www/horas/Polski/TemporaM/081-0.txt
web/www/horas/Polski/psalms1/Psalm68.txt

Monastic matutinum update

---

web/cgi-bin/horas/monastic.pl
web/www/horas/English/SanctiM/08-06.txt
web/www/horas/English/SanctiM/08-10.txt
web/www/horas/English/TemporaM/082-0.txt
web/www/horas/English/TemporaM/Pent10-0.txt
web/www/horas/Latin/Commune/C11.txt
web/www/horas/Latin/Commune/C4.txt
web/www/horas/Latin/Commune/C5.txt
web/www/horas/Latin/CommuneM/C6.txt
web/www/horas/Latin/CommuneM/C9.txt
web/www/horas/Latin/Psalterium/Matutinum Special.txt
web/www/horas/Latin/Sancti/08-06.txt
web/www/horas/Latin/SanctiM/07-14.txt
web/www/horas/Latin/SanctiM/07-22.txt
web/www/horas/Latin/SanctiM/07-31.txt
web/www/horas/Latin/SanctiM/08-06.txt
web/www/horas/Latin/SanctiM/08-10.txt
web/www/horas/Latin/TemporaM/082-0.txt
web/www/horas/Latin/TemporaM/Pent10-0.txt
web/www/horas/Polski/SanctiM/08-06.txt
web/www/horas/Polski/SanctiM/08-10.txt

Monastic updates

---

web/www/horas/Latin/SanctiM/07-31.txt

MONASTIC 07-31 - rank correction

---

web/www/horas/Polski/Ordinarium/PrimaM.txt
web/www/horas/Polski/Psalterium/Translate.txt
web/www/horas/Polski/psalms1/Psalm121.txt

Polski/{PrimaM,Translation,Psalm121} - update

---

web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/Italiano/Psalterium/Matutinum Special.txt
web/www/horas/Latin/CommuneM/C11.txt
web/www/horas/Latin/Psalterium/Benedictions.txt
web/www/horas/Latin/SanctiM/08-20.txt
web/www/horas/Latin/SanctiM/08-28.txt
web/www/horas/Latin/Tempora/083-0.txt
web/www/horas/Latin/Tempora/084-0.txt
web/www/horas/Magyar/Psalterium/Matutinum Special.txt

Monastic matutinum updates

---

web/www/horas/Latin/Sancti/08-15.txt

Latin/08-15 - Lectio2 correction

---

web/www/horas/Polski/TemporaM/083-0.txt
web/www/horas/Polski/TemporaM/Pent11-0.txt
web/www/horas/Polski/psalms1/Psalm118.txt
web/www/horas/Polski/psalms1/Psalm44.txt

Polski/* - update

---

web/www/horas/English/CommuneM/C1.txt
web/www/horas/English/SanctiM/08-24.txt
web/www/horas/English/psalms1/Psalm253.txt
web/www/horas/English/psalms1/Psalm254.txt
web/www/horas/English/psalms1/Psalm255.txt
web/www/horas/Latin/CommuneM/C1.txt
web/www/horas/Latin/SanctiM/08-24.txt
web/www/horas/Latin/psalms1/Psalm253.txt
web/www/horas/Latin/psalms1/Psalm254.txt
web/www/horas/Latin/psalms1/Psalm255.txt
web/www/horas/Polski/CommuneM/C1.txt
web/www/horas/Polski/SanctiM/08-24.txt
web/www/horas/Polski/psalms1/Psalm253.txt
web/www/horas/Polski/psalms1/Psalm254.txt
web/www/horas/Polski/psalms1/Psalm255.txt

Monastic {Latin,English,Polski}/{C1,08-24, Psalms25[345]}

---

web/www/horas/Latin/Psalterium/Major Special.txt

Major Special update

---

web/cgi-bin/horas/horas.pl

MONASTIC code: allow set dagger if Ant. match 1st line in psalm

---

web/www/horas/Latin/CommuneM/C1.txt

MONASTIC C1 Vespera last psalm correction

---

web/www/horas/Latin/SanctiM/01-21.txt
web/www/horas/Latin/SanctiM/01-25.txt
web/www/horas/Latin/SanctiM/01-28.txt
web/www/horas/Latin/SanctiM/02-05.txt
web/www/horas/Latin/SanctiM/02-22.txt
web/www/horas/Latin/SanctiM/03-25.txt
web/www/horas/Latin/SanctiM/06-30.txt

MONASTIC Sancti refactoring

---

web/www/horas/Latin/Psalterium/Major Special.txt

MONASTIC - Thursday Laudes Hymnn correction

---

web/www/horas/English/TemporaM/091-0.txt
web/www/horas/English/TemporaM/092-0.txt
web/www/horas/English/TemporaM/093-0.txt
web/www/horas/English/TemporaM/094-0.txt
web/www/horas/English/TemporaM/095-0.txt
web/www/horas/English/TemporaM/Pent14-0.txt
web/www/horas/English/TemporaM/Pent15-0.txt
web/www/horas/English/TemporaM/Pent16-0.txt
web/www/horas/English/TemporaM/Pent17-0.txt
web/www/horas/Latin/Tempora/091-0.txt
web/www/horas/Latin/Tempora/094-0.txt
web/www/horas/Latin/Tempora/095-0.txt
web/www/horas/Latin/TemporaM/091-0.txt
web/www/horas/Latin/TemporaM/092-0.txt
web/www/horas/Latin/TemporaM/093-0.txt
web/www/horas/Latin/TemporaM/094-0.txt
web/www/horas/Latin/TemporaM/095-0.txt
web/www/horas/Latin/TemporaM/Pent14-0.txt
web/www/horas/Latin/TemporaM/Pent15-0.txt
web/www/horas/Latin/TemporaM/Pent16-0.txt
web/www/horas/Latin/TemporaM/Pent17-0.txt
web/www/horas/Polski/TemporaM/095-0.txt
web/www/horas/Polski/TemporaM/Pent14-0.txt
web/www/horas/Polski/TemporaM/Pent16-0.txt
web/www/horas/Polski/TemporaM/Pent17-0.txt

Monastic Tempora - Sundays September and Pent14-17 - 12 lectiones 

---

web/www/horas/English/Psalterium/Major Special.txt
web/www/horas/Latin/Psalterium/Major Special.txt
web/www/horas/Polski/Psalterium/Major Special.txt

add old Antiphonas for Benedictus and Magnificat + update Major Special (English, Polski)

---

web/cgi-bin/horas/specmatins.pl
web/www/horas/Latin/SanctiM/05-27.txt
web/www/horas/Latin/SanctiM/07-14.txt
web/www/horas/Latin/SanctiM/08-20.txt
web/www/horas/Latin/SanctiM/08-28.txt

MONASTIC 'O Doctor optime' + code Gloria in Responsory

---

web/cgi-bin/horas/horascommon.pl
web/www/horas/Latin/TemporaM/092-0.txt
web/www/horas/Polski/Ordinarium/CompletoriumM.txt
web/www/horas/Polski/Psalterium/Mariaant.txt

Monastic code + Polish files update

---

web/www/horas/English/Sancti/05-08.txt
web/www/horas/English/SanctiM/09-08.txt
web/www/horas/English/SanctiM/09-14.txt
web/www/horas/English/SanctiM/09-21.txt
web/www/horas/English/SanctiM/09-29.txt
web/www/horas/Latin/CommuneM/C1a.txt
web/www/horas/Latin/Sancti/05-08.txt
web/www/horas/Latin/SanctiM/09-08.txt
web/www/horas/Latin/SanctiM/09-14.txt
web/www/horas/Latin/SanctiM/09-15.txt
web/www/horas/Latin/SanctiM/09-21.txt
web/www/horas/Latin/SanctiM/09-29.txt
web/www/horas/Latin/SanctiM/09-30.txt
web/www/horas/Polski/SanctiM/09-08.txt
web/www/horas/Polski/SanctiM/09-14.txt
web/www/horas/Polski/SanctiM/09-29.txt

Monastic Sancti Matutinum update

---

web/www/horas/Latin/Psalterium/Major Special.txt

MONASTIC Fix Doxology in Laudes F5 F6 + Amen

---

web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/English/CommuneM/C10.txt
web/www/horas/Latin/CommuneM/C10.txt

￼ MONASTIC C10 update

---

web/www/horas/Latin/Psalterium/Psalmi major.txt
web/www/horas/Latin/Psalterium/Psalmi matutinum.txt

MONASTIC antiphonas - corrections

---

web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specmatins.pl

Code for monastic C10 (327e024ea) with correction

---

web/cgi-bin/horas/horascommon.pl
web/www/horas/Latin/SanctiM/09-08.txt

Monastic update

---

web/cgi-bin/horas/monastic.pl
web/www/horas/English/SanctiM/09-15.txt
web/www/horas/Latin/SanctiM/09-15.txt

Monastic 09-15 corrections

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/monastic.pl
web/www/horas/English/SanctiM/10-DU.txt
web/www/horas/Latin/SanctiM/10-DU.txt

MONASTIC 10-DU correction of Canticles + code changes

---

web/www/missa/English/Tempora/Quad5-5.txt
web/www/missa/Portugues/Tempora/Quad5-5.txt

Remove "s" in two more places where it refers to John the Apostle.

Remove "s" from Disciple

---

web/www/missa/English/Commune/C3.txt
web/www/missa/English/Commune/C3b.txt
web/www/missa/English/Tempora/Quad6-4.txt
web/www/missa/English/Tempora/Quad6-4r.txt
web/www/missa/English/Tempora/Quad6-4t.txt
web/www/missa/Magyar/Commune/C3b.txt

Note:  Big confusion for "Ubi Caritas" on Holy Thursday:
No attribution or citation in St Joseph Missal
Baronius attributes lyrics to John 2:3, 4
Before this change some files in DO attributed 1 John: 3,4.
None of the referenced scripture has any resemblance to Ubi Caritas.  Some versions have words from 1 Corinthians 13.
I corrected to match St Joseph Missal with no scriptural attribution.

Formatting and Corrections

---

web/www/horas/Latin/TemporaM/093-3.txt
web/www/horas/Latin/TemporaM/093-5.txt
web/www/horas/Latin/TemporaM/093-6.txt

MONASTIC Quattuor Temporum Septembris - rank correction

---

web/www/horas/Latin/TemporaM/093-6.txt
web/www/horas/Polski/TemporaM/093-6.txt

MONASTIC Sabbato QT - Ant Laudes correction

---

web/www/horas/Deutsch/Sancti/05-08.txt
web/www/horas/English/Sancti/05-08.txt
web/www/horas/Italiano/Sancti/05-08.txt
web/www/horas/Latin/SanctiM/09-29.txt
web/www/horas/Magyar/Sancti/05-08.txt
web/www/horas/Polski/Sancti/05-08.txt

MONASTIC 09-29 Repairs Vespera psalms 

---

web/www/horas/English/CommuneM/C1a.txt
web/www/horas/English/SanctiM/10-18.txt
web/www/horas/English/SanctiM/10-28.txt
web/www/horas/Latin/CommuneM/C1a.txt
web/www/horas/Latin/SanctiM/10-02.txt
web/www/horas/Latin/SanctiM/10-05.txt
web/www/horas/Latin/SanctiM/10-07.txt
web/www/horas/Latin/SanctiM/10-15.txt
web/www/horas/Latin/SanctiM/10-18.txt
web/www/horas/Latin/SanctiM/10-28.txt
web/www/horas/Polski/CommuneM/C1a.txt
web/www/horas/Polski/SanctiM/10-18.txt
web/www/horas/Polski/SanctiM/10-28.txt

MONASTIC Octobers Sancti Matutinum

---

web/www/horas/Latin/SanctiM/10-05.txt

MONASTIC 10-05 corrections

---

web/cgi-bin/horas/horascommon.pl

fix #1912 in code - use Latin in getrank

---

web/www/horas/Latin/CommuneM/C5.txt

MONASTIC C5 - Hymnus Verspera correction

---

web/cgi-bin/horas/horascommon.pl
web/www/horas/English/TemporaM/111-0.txt
web/www/horas/English/TemporaM/113-0.txt
web/www/horas/English/TemporaM/114-0.txt
web/www/horas/English/TemporaM/115-0.txt
web/www/horas/English/TemporaM/Pent21-0.txt
web/www/horas/English/TemporaM/Pent22-0.txt
web/www/horas/English/TemporaM/Pent23-0.txt
web/www/horas/English/TemporaM/Pent24-0.txt
web/www/horas/Latin/TemporaM/111-0.txt
web/www/horas/Latin/TemporaM/113-0.txt
web/www/horas/Latin/TemporaM/114-0.txt
web/www/horas/Latin/TemporaM/115-0.txt
web/www/horas/Latin/TemporaM/Pent21-0.txt
web/www/horas/Latin/TemporaM/Pent22-0.txt
web/www/horas/Latin/TemporaM/Pent23-0.txt
web/www/horas/Latin/TemporaM/Pent24-0.txt
web/www/horas/Polski/TemporaM/115-0.txt
web/www/horas/Polski/TemporaM/Pent21-0.txt
web/www/horas/Polski/TemporaM/Pent22-0.txt
web/www/horas/Polski/TemporaM/Pent23-0.txt
web/www/horas/Polski/TemporaM/Pent24-0.txt

MONASTIC 12 readings in Novembers Sundays

---

web/www/missa/English/Tempora/Quad3-4.txt
web/www/missa/English/Tempora/Quad3-4t.txt
web/www/missa/Magyar/Tempora/Quad3-4.txt
web/www/missa/Magyar/Tempora/Quad3-4t.txt

Remove blank like between Introit header and text.

Formatting

---

web/cgi-bin/horas/specmatins.pl

MONASTIC code: fix Sundays Matins readings broken by d54f47c

---

web/www/horas/Latin/Psalterium/Major Special.txt

Friday Laudes - old Hymn correction

---

web/cgi-bin/horas/specials.pl

code: fix adding alleluia in Antiphona

---

web/www/horas/English/SanctiM/10-DU.txt
web/www/horas/Latin/SanctiM/10-DU.txt

MONASTIC 10-DU - corrections

---

web/www/horas/English/Sancti/11-01.txt
web/www/horas/Latin/Sancti/11-01.txt

Sancti/11-01 - Lectio correction

---

web/cgi-bin/horas/specmatins.pl

MONASTIC code: correct 5th Saturday in getC10readingname

---

web/cgi-bin/horas/specials.pl
web/www/horas/Latin/SanctiM/11-02.txt

MONASTIC 11-02 update

---

web/www/horas/English/SanctiM/11-17.txt
web/www/horas/Latin/SanctiM/11-17.txt

MONASTIC 11-17 update

---

web/www/horas/Latin/Commune/C8.txt
web/www/horas/Latin/CommuneM/C8.txt

C9 Monastic & 1570 update

---

web/www/horas/Latin/SanctiM/11-11.txt

MONASTIC 11-11 correction Ant Vespera

---

web/www/horas/English/SanctiM/11-11.txt
web/www/horas/Italiano/SanctiM/11-11.txt
web/www/horas/Latin/SanctiM/11-11.txt
web/www/horas/Polski/SanctiM/11-11.txt

MONASTIC 11-11 responsory + lectioE

---

web/www/horas/Latin/SanctiM/11-13.txt

MONASTIC 11-13 - Vespera correction

---

web/www/horas/Italiano/CommuneM/C2.txt
web/www/horas/Italiano/Psalterium/Psalmi matutinum.txt
web/www/horas/Latin/Sancti/12-28.txt

Minor corrections

---

web/www/horas/Latin/SanctiM/11-17.txt

MONASTIC 11-17 clean

---

web/www/horas/Espanol/Sancti/12-25.txt

Espanol/Sancti/12-25 - remove link which causes loop in calendar

---

web/www/horas/Espanol/Sancti/02-22.txt
web/www/horas/Espanol/Sancti/05-08.txt
web/www/horas/Espanol/Sancti/06-24.txt
web/www/horas/Espanol/Sancti/06-29.txt
web/www/horas/Espanol/Sancti/06-30.txt
web/www/horas/Espanol/Sancti/07-22.txt
web/www/horas/Espanol/Sancti/08-01.txt
web/www/horas/Espanol/Sancti/08-06.txt
web/www/horas/Espanol/Sancti/10-02.txt
web/www/horas/Espanol/Sancti/11-01.txt
web/www/horas/Espanol/Sancti/12-25.txt
web/www/horas/Espanol/Sancti/12-28.txt
web/www/horas/Francais/Tempora/Pasc5-4.txt
web/www/horas/Francais/Tempora/Pasc7-0.txt

{Espanol,Francais}/* old hymns section name

---

web/cgi-bin/horas/specials.pl

Fix #1060 #1062

---

web/www/horas/Latin/Sancti/12-29.txt
web/www/horas/Latin/Sancti/12-30.txt
web/www/horas/Latin/Sancti/12-31.txt
web/www/horas/Latin/Sancti/12-31r.txt
web/www/horas/Latin/Tempora/Nat1-0.txt

Revert redundant commits introduced as fix to #1060 & #1062

---

web/cgi-bin/horas/specials.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/English/Psalterium/Psalmi matutinum.txt
web/www/horas/Latin/Psalterium/Psalmi matutinum.txt

dca6e6e0f11f5358f8d0f698cb947533fc6c5d1f fixes the antiphons but uses the Divino Afflatu psalms

Fixes issues #2129 and #2132

---

web/www/horas/Deutsch/Tempora/Adv3-0.txt
web/www/horas/Deutsch/Tempora/Adv4-0.txt
web/www/horas/English/Tempora/Adv1-0.txt
web/www/horas/English/Tempora/Adv2-0.txt
web/www/horas/English/Tempora/Adv3-0.txt
web/www/horas/English/Tempora/Adv4-0.txt
web/www/horas/Espanol/Tempora/Adv1-0.txt
web/www/horas/Espanol/Tempora/Adv2-0.txt
web/www/horas/Espanol/Tempora/Adv3-0.txt
web/www/horas/Espanol/Tempora/Adv4-0.txt
web/www/horas/Francais/Tempora/Adv1-0.txt
web/www/horas/Francais/Tempora/Adv2-0.txt
web/www/horas/Francais/Tempora/Adv3-0.txt
web/www/horas/Francais/Tempora/Adv4-0.txt
web/www/horas/Latin/Tempora/Adv1-0.txt
web/www/horas/Latin/Tempora/Adv2-0.txt
web/www/horas/Latin/Tempora/Adv3-0.txt
web/www/horas/Latin/Tempora/Adv4-0.txt
web/www/horas/Polski/Tempora/Adv1-0.txt
web/www/horas/Polski/Tempora/Adv2-0.txt
web/www/horas/Polski/Tempora/Adv3-0.txt
web/www/horas/Polski/Tempora/Adv4-0.txt

Refactor b7e26da also fix introduced bugs in Monastic & 1955

---

web/www/horas/English/SanctiM/11-30.txt

MONASTIC English/11-30 - correction of Matins antiphonas

---

web/www/horas/English/Commune/C4.txt

Fix issue #2145

---

web/www/horas/English/Psalterium/Major Special.txt
web/www/horas/Latin/Psalterium/Major Special.txt

Old hymns update

---

web/cgi-bin/horas/horas.pl
web/www/horas/Deutsch/Ordinarium/MatutinumM.txt
web/www/horas/English/Ordinarium/MatutinumM.txt
web/www/horas/English/Ordinarium/PrimaM.txt
web/www/horas/English/Psalterium/Benedictions.txt
web/www/horas/English/Psalterium/Translate.txt
web/www/horas/Espanol/Ordinarium/MatutinumM.txt
web/www/horas/Espanol/Ordinarium/PrimaM.txt
web/www/horas/Italiano/Ordinarium/MatutinumM.txt
web/www/horas/Italiano/Ordinarium/PrimaM.txt
web/www/horas/Latin/Ordinarium/MatutinumM.txt
web/www/horas/Latin/Ordinarium/PrimaM.txt
web/www/horas/Latin/Psalterium/Translate.txt
web/www/horas/Magyar/Ordinarium/MatutinumM.txt
web/www/horas/Magyar/Ordinarium/PrimaM.txt
web/www/horas/Polski/Ordinarium/MatutinumM.txt
web/www/horas/Polski/Ordinarium/PrimaM.txt
web/www/horas/Polski/Psalterium/Translate.txt

Monastic: Ordinarium update

---

web/cgi-bin/horas/specials.pl

MONASTIC code: proper Oratio in Vespera of Quattor

---

web/www/horas/Francais/Psalterium/Psalmi minor.txt

Traduction des antiennes de laudes du jeudi Adv III

Update Psalmi minor.txt

---

web/cgi-bin/horas/specials.pl

MONASTIC code: Dec 17-23 use Laudes Antiphonas at Vespera

---

web/www/horas/English/psalms1/Psalm240.txt
web/www/horas/English/psalms1/Psalm241.txt
web/www/horas/English/psalms1/Psalm242.txt
web/www/horas/Latin/psalms1/Psalm240.txt
web/www/horas/Latin/psalms1/Psalm241.txt
web/www/horas/Latin/psalms1/Psalm242.txt
web/www/horas/Polski/psalms1/Psalm240.txt
web/www/horas/Polski/psalms1/Psalm241.txt
web/www/horas/Polski/psalms1/Psalm242.txt

MONASTIC {Latin,English,Polski}/Psalm24[0-2] - accents, verse split & stars

---

web/www/horas/Latin/TemporaM/Adv4-0.txt

MONASTIC Adv4-0 Capitulum Vespera/Laudes correction

---

web/cgi-bin/horas/horas.pl

MONASTIC code: correction of condition for Requiem in place Gloria in Prima Psalm 129

---

web/www/horas/Latin/SanctiM/11-13.txt

MONASTIC 11-13 - Invit

---

web/www/horas/Latin/SanctiM/01-01.txt
web/www/horas/Latin/SanctiM/12-25.txt
web/www/horas/Latin/SanctiM/12-26.txt
web/www/horas/Latin/SanctiM/12-30.txt
web/www/horas/Latin/Tempora/Nat1-0.txt
web/www/horas/Latin/TemporaM/Nat1-0.txt
web/www/horas/Latin/TemporaM/Nat2-0.txt

MONASTIC Christmastide update

---

web/cgi-bin/horas/specials.pl

MONASTIC code: fix last Vespera antiphona Dec 17-23

---

web/www/horas/English/Sancti/12-25.txt
web/www/horas/Latin/Sancti/12-25.txt

12/25 old Hymns as links

---

web/cgi-bin/horas/dialogcommon.pl
web/www/horas/Latin/Commune/C6p.txt
web/www/horas/Latin/SanctiM/03-12.txt
web/www/horas/Latin/SanctiM/10-DU.txt
web/www/horas/Latin/TemporaM/Pasc0-0.txt
web/www/horas/Latin/TemporaM/Pasc1-0.txt
web/www/horas/Latin/TemporaM/Pasc2-0.txt
web/www/horas/Latin/TemporaM/Pasc3-0.txt
web/www/horas/Latin/TemporaM/Pasc4-0.txt
web/www/horas/Latin/TemporaM/Pasc5-0.txt
web/www/horas/Latin/TemporaM/Pasc6-0.txt
web/www/horas/Latin/TemporaM/Pent01-4.txt
web/www/horas/Latin/TemporaM/Quad1-0.txt
web/www/horas/Latin/TemporaM/Quad2-0.txt
web/www/horas/Latin/TemporaM/Quad3-0.txt
web/www/horas/Latin/TemporaM/Quad4-0.txt
web/www/horas/Latin/TemporaM/Quad5-0.txt
web/www/horas/Latin/TemporaM/Quad6-0.txt
web/www/horas/Latin/TemporaM/Quadp1-0.txt
web/www/horas/Latin/TemporaM/Quadp2-0.txt
web/www/horas/Latin/TemporaM/Quadp3-0.txt

code: do_inclusion_substitutions - correction + data update

---

web/www/horas/English/CommuneM/C3.txt
web/www/horas/English/SanctiM/12-28.txt
web/www/horas/Latin/CommuneM/C3.txt
web/www/horas/Latin/SanctiM/12-28.txt

MONASTIC {Latin,English} 12-28 + C3 update

---

web/www/horas/Latin/Psalterium/Matutinum Special.txt

Matutinum special - old Quad hymn correction

---

web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/Latin/SanctiM/01-03.txt
web/www/horas/Latin/SanctiM/01-05.txt
web/www/horas/Latin/TemporaM/Epi1-3.txt
web/www/horas/Latin/TemporaM/Nat2-0.txt

MONASTIC code update for January 2-13

---

web/www/horas/Latin/SanctiM/12-29.txt
web/www/horas/Latin/SanctiM/12-31.txt
web/www/horas/Latin/Tempora/Epi2-0.txt

Small updates

---

web/www/missa/English/Ordo/Ordo.txt
web/www/missa/English/Ordo/OrdoM.txt
web/www/missa/English/Ordo/OrdoS.txt
web/www/missa/English/Tempora/Quad6-6.txt
web/www/missa/English/Tempora/Quad6-6t.txt
web/www/missa/Portugues/Tempora/Quad6-6t.txt

Corrected this line to make it consistent internally within the Prayers at the Foot of the Altar and in accordance with the St. Joseph Missal.  Allowed alternative translations in other places to remain as they are.

Correct inconsistencies in English prayers at the foot of the altar

---

web/www/horas/Latin/SanctiM/01-02.txt
web/www/horas/Latin/SanctiM/01-03.txt
web/www/horas/Latin/SanctiM/01-04.txt
web/www/horas/Latin/SanctiM/01-05.txt

MONASTIC 01/0[2-5] update

---

web/www/horas/English/SanctiM/01-13.txt
web/www/horas/Latin/SanctiM/01-06.txt
web/www/horas/Latin/SanctiM/01-13.txt

MONASTIC 01-{06,13} - Matutinum Lectios corrections

---

web/www/missa/English/Commune/C10b.txt
web/www/missa/Magyar/Sancti/11-01.txt
web/www/missa/Magyar/Sancti/11-02m1.txt
web/www/missa/Magyar/Sancti/11-02m2.txt
web/www/missa/Magyar/Sancti/11-02m3.txt
web/www/missa/Magyar/Sancti/11-04.txt
web/www/missa/Magyar/Sancti/11-04r.txt
web/www/missa/Magyar/Sancti/11-08.txt
web/www/missa/Magyar/Sancti/11-08r.txt
web/www/missa/Magyar/Sancti/11-09.txt
web/www/missa/Magyar/Sancti/11-10.txt
web/www/missa/Magyar/Sancti/11-10o.txt
web/www/missa/Magyar/Sancti/11-11.txt
web/www/missa/Magyar/Sancti/11-12.txt
web/www/missa/Magyar/Sancti/11-12t.txt
web/www/missa/Magyar/Sancti/11-13.txt

Included two changes to English C10b.txt

Remove superfluous English Text from Missa/Magyar/Sancti November

---

web/cgi-bin/horas/specials.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/Latin/SanctiM/01-11.txt

MONASTIC fixes in Octava of Epiphany after Sunday

---

web/cgi-bin/horas/specials.pl
web/www/horas/Deutsch/Psalterium/Psalmi major.txt
web/www/horas/English/Psalterium/Psalmi major.txt
web/www/horas/Espanol/Psalterium/Psalmi major.txt
web/www/horas/Francais/Psalterium/Psalmi major.txt
web/www/horas/Italiano/Psalterium/Psalmi major.txt
web/www/horas/Latin/Psalterium/Psalmi major.txt
web/www/horas/Latin/TemporaM/Epi1-0.txt
web/www/horas/Latin/TemporaM/Nat2-0.txt
web/www/horas/Polski/Psalterium/Psalmi major.txt

MONASTIC Laudes Sunday/Feast antiphons correction 

---

web/www/horas/Latin/TemporaM/Nat1-0.txt

MONASTIC Nat1-0 correction

---

web/www/horas/English/Psalterium/Benedictions.txt
web/www/horas/Latin/Psalterium/Benedictions.txt

Benedictions remove stars

---

web/www/horas/English/TemporaM/Epi3-0.txt
web/www/horas/Latin/TemporaM/Epi1-0.txt
web/www/horas/Latin/TemporaM/Epi1-3.txt
web/www/horas/Latin/TemporaM/Epi2-0.txt
web/www/horas/Latin/TemporaM/Epi3-0.txt

MONASTIC Epi* update

---

web/www/horas/Latin/TemporaM/Quadp1-0.txt
web/www/horas/Latin/TemporaM/Quadp2-0.txt
web/www/horas/Latin/TemporaM/Quadp3-0.txt

MONASTIC Quadp Sundays Invit2

---

web/cgi-bin/horas/specmatins.pl

code: Trident Matins 1st nocturn readings correction

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/officium.pl
web/www/horas/Latin/Ordinarium/CompletoriumOP.txt
web/www/horas/Latin/Ordinarium/LaudesOP.txt
web/www/horas/Latin/Ordinarium/MatutinumOP.txt
web/www/horas/Latin/Ordinarium/NonaOP.txt
web/www/horas/Latin/Ordinarium/PrimaOP.txt
web/www/horas/Latin/Ordinarium/SextaOP.txt
web/www/horas/Latin/Ordinarium/TertiaOP.txt
web/www/horas/Latin/Ordinarium/VesperaOP.txt
web/www/horas/Latin/Psalterium/Prayers.txt
web/www/horas/Portugues/Ordinarium/CompletoriumOP.txt

👷🏻‍♂️ WIP: Add complines dominican rite

---

web/www/horas/Espanol/Tempora/Pasc6-0.txt
web/www/horas/Espanol/Tempora/Pasc6-6.txt
web/www/horas/Francais/Tempora/Pasc3-2.txt
web/www/horas/Francais/Tempora/Pasc5-4.txt
web/www/horas/Francais/Tempora/Pasc6-0.txt
web/www/horas/Latin/Tempora/Pasc3-2.txt
web/www/horas/Latin/Tempora/Pasc5-4.txt
web/www/horas/Latin/Tempora/Pasc6-0.txt
web/www/horas/Latin/TemporaM/Pasc6-0.txt

Responsories correction

---

web/cgi-bin/horas/horas.pl
web/cgi-bin/horas/specmatins.pl

code: refactor handling matins responsory alleluia

---

web/www/horas/English/Sancti/01-21.txt
web/www/horas/English/SanctiM/01-21.txt
web/www/horas/Latin/Sancti/05-08.txt

Few corrections

---

web/www/horas/Latin/SanctiM/01-17.txt
web/www/horas/Latin/SanctiM/01-20.txt
web/www/horas/Latin/SanctiM/01-21.txt
web/www/horas/Latin/SanctiM/01-22.txt
web/www/horas/Latin/SanctiM/01-25.txt
web/www/horas/Latin/SanctiM/01-27.txt

MONASTIC Sancti January update

---

web/cgi-bin/horas/horascommon.pl
web/www/horas/Latin/Tempora/Quad1-0.txt
web/www/horas/Latin/Tempora/Quad2-0.txt
web/www/horas/Latin/Tempora/Quad3-0.txt
web/www/horas/Latin/Tempora/Quad4-0.txt
web/www/horas/Latin/Tempora/Quad5-0.txt
web/www/horas/Latin/Tempora/Quad6-0.txt

fix false commemoratio of Transfered feasts on Lent Sunday

---

web/cgi-bin/horas/specials.pl

code: fix #2162 p. 3 & p. 4 + refactor

---

web/www/horas/Latin/Commune/C10.txt
web/www/horas/Latin/Commune/C12N.txt
web/www/horas/Latin/Commune/C12P.txt

proper fix #2308

---

web/www/missa/Latin/Ordo/Ordo.txt

Some function names were not working.  These three changes need to be double-checked to make sure they don't break something I'm not aware of.

Back Out Latin Changes That Breaks Some Functions

---

web/cgi-bin/horas/horas.pl

code: partially revert breaking 576a26f

---

web/www/horas/English/Sancti/06-30.txt
web/www/horas/Latin/Sancti/01-25.txt
web/www/horas/Latin/Sancti/06-30.txt
web/www/horas/Latin/SanctiM/01-25.txt

Sancti/06-30 01-25 use Ant 2 from Commune

---

web/www/horas/English/Psalterium/Major Special.txt
web/www/horas/Latin/Psalterium/Major Special.txt
web/www/horas/Polski/Psalterium/Major Special.txt

{Latin,English,Polski} old Ant. for Saturday Vespers

---

web/www/horas/Latin/Sancti/02-22.txt

02-22 old hymns

---

web/www/horas/Latin/SanctiM/01-25.txt
web/www/horas/Latin/SanctiM/01-27.txt

MONASTIC 01-2{57} Vespera corrections

---

web/www/horas/Latin/SanctiM/01-27.txt

MONASTIC 01-27 Vespera corrections

---

web/cgi-bin/horas/specials.pl

code: fix #1532

---

web/www/horas/English/SanctiM/02-02.txt
web/www/horas/English/Tempora/Quadp1-0.txt
web/www/horas/Espanol/Tempora/Quadp1-0.txt
web/www/horas/Francais/Tempora/Quadp1-0.txt
web/www/horas/Italiano/Tempora/Quadp1-0.txt
web/www/horas/Latin/SanctiM/02-02.txt
web/www/horas/Latin/SanctiM/11-01.txt
web/www/horas/Latin/SanctiM/11-13.txt
web/www/horas/Latin/Tempora/Quadp1-0.txt
web/www/horas/Latin/TemporaM/094-0.txt
web/www/horas/Latin/TemporaM/Adv4-0.txt
web/www/horas/Latin/TemporaM/Quadp1-0.txt
web/www/horas/Latin/psalms1/Psalm221.txt
web/www/horas/Latin/psalms1/Psalm250.txt
web/www/horas/Latin/psalms1/Psalm251.txt
web/www/horas/Latin/psalms1/Psalm268.txt
web/www/horas/Polski/Tempora/Quadp1-0.txt

Various minor updates

---

web/www/horas/Latin/SanctiM/02-02.txt

MONASTIC 02-02 Capitulum fix

---

web/www/horas/English/TemporaM/Quad1-0.txt
web/www/horas/English/TemporaM/Quad2-0.txt
web/www/horas/English/TemporaM/Quad3-0.txt
web/www/horas/English/TemporaM/Quad4-0.txt
web/www/horas/English/psalms1/Psalm269.txt
web/www/horas/English/psalms1/Psalm270.txt
web/www/horas/English/psalms1/Psalm271.txt
web/www/horas/Latin/TemporaM/Quad1-0.txt
web/www/horas/Latin/TemporaM/Quad2-0.txt
web/www/horas/Latin/TemporaM/Quad3-0.txt
web/www/horas/Latin/TemporaM/Quad4-0.txt
web/www/horas/Latin/psalms1/Psalm269.txt
web/www/horas/Latin/psalms1/Psalm270.txt
web/www/horas/Latin/psalms1/Psalm271.txt
web/www/horas/Polski/psalms1/Psalm269.txt
web/www/horas/Polski/psalms1/Psalm270.txt
web/www/horas/Polski/psalms1/Psalm271.txt

MONASTIC Canticles for Lent

---

web/www/horas/English/Psalterium/Matutinum Special.txt
web/www/horas/Latin/Psalterium/Major Special.txt
web/www/horas/Latin/Psalterium/Matutinum Special.txt

Old Hymns - corrections and links

---

web/www/horas/English/SanctiM/02-22.txt
web/www/horas/Latin/SanctiM/02-22.txt

MONASTIC 02-22 Rank and Readings

---

web/www/horas/English/CommuneM/C4.txt
web/www/horas/English/SanctiM/03-12.txt
web/www/horas/English/SanctiM/03-19.txt
web/www/horas/English/SanctiM/03-21.txt
web/www/horas/English/SanctiM/03-25.txt
web/www/horas/English/psalms1/Psalm256.txt
web/www/horas/English/psalms1/Psalm257.txt
web/www/horas/English/psalms1/Psalm258.txt
web/www/horas/Latin/CommuneM/C11.txt
web/www/horas/Latin/CommuneM/C4.txt
web/www/horas/Latin/SanctiM/03-06.txt
web/www/horas/Latin/SanctiM/03-12.txt
web/www/horas/Latin/SanctiM/03-19.txt
web/www/horas/Latin/SanctiM/03-21.txt
web/www/horas/Latin/SanctiM/03-25.txt
web/www/horas/Latin/psalms1/Psalm256.txt
web/www/horas/Latin/psalms1/Psalm257.txt
web/www/horas/Latin/psalms1/Psalm258.txt
web/www/horas/Polski/SanctiM/03-12.txt
web/www/horas/Polski/SanctiM/03-19.txt
web/www/horas/Polski/SanctiM/03-25.txt

MONASTIC Sancti March - Matutinumi etc.

---

web/www/horas/Latin/Sancti/01-03o.txt
web/www/horas/Latin/Tempora/Pasc3-2.txt

verse numbering

---

web/www/horas/Deutsch/Tempora/Nat1-0.txt
web/www/horas/English/Sancti/08-14t.txt
web/www/horas/English/Sancti/08-18t.txt
web/www/horas/Espanol/Sancti/08-18t.txt
web/www/horas/Espanol/Sancti/10-DU.txt
web/www/horas/Espanol/Tempora/Nat1-0.txt
web/www/horas/Francais/Sancti/08-18t.txt
web/www/horas/Francais/Sancti/10-24.txt
web/www/horas/Francais/Sancti/10-DU.txt
web/www/horas/Francais/Sancti/10-DUr.txt
web/www/horas/Francais/Tempora/Nat1-0.txt
web/www/horas/Italiano/Sancti/08-03.txt
web/www/horas/Italiano/Sancti/08-18t.txt
web/www/horas/Italiano/Sancti/10-DU.txt
web/www/horas/Italiano/Sancti/10-DUr.txt
web/www/horas/Italiano/Sancti/12-30.txt
web/www/horas/Italiano/Sancti/12-30o.txt
web/www/horas/Italiano/Tempora/Nat1-0.txt
web/www/horas/Latin/Sancti/08-18.txt
web/www/horas/Latin/Sancti/10-DU.txt
web/www/horas/Latin/Tempora/Nat1-0.txt
web/www/horas/Polski/Sancti/08-18t.txt
web/www/horas/Polski/Sancti/10-DU.txt

AFAICS the `.` after `&Gloria` does nothing. There are very few instances in the entire database; almost all responsories use `&Gloria`.  This PR standardises the few remaining examples.

Remove errant dots.

---

web/www/horas/Polski/Martyrologium/03-11.txt
web/www/horas/Polski/Psalterium/Psalmi major.txt
web/www/horas/Polski/Regula/03-08.txt
web/www/horas/Polski/Tempora/Quad2-0.txt
web/www/horas/Polski/psalms1/Psalm256.txt
web/www/horas/Polski/psalms1/Psalm257.txt
web/www/horas/Polski/psalms1/Psalm258.txt

Polski/* - corrections

---

web/www/horas/English/Tempora/Quad4-0.txt
web/www/horas/Latin/Tempora/Quad4-0.txt
web/www/horas/Polski/Tempora/Quad4-0.txt

MONASTIC Quad4-0 Ant Laudes update

---

web/www/horas/Latin/CommuneM/C4.txt

MONASTIC C4 Ants correction

---

web/www/horas/English/SanctiM/03-21.txt
web/www/horas/Latin/SanctiM/03-21.txt
web/www/horas/Latin/TemporaM/Quad5-0.txt

MONASTIC Small corrections

---

web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/Deutsch/Psalterium/Psalmi matutinum.txt
web/www/horas/English/Psalterium/Matutinum Special.txt
web/www/horas/English/Psalterium/Psalmi matutinum.txt
web/www/horas/English/TemporaM/Pasc2-0.txt
web/www/horas/English/TemporaM/Pasc3-0.txt
web/www/horas/English/TemporaM/Pasc4-0.txt
web/www/horas/English/TemporaM/Pasc5-0.txt
web/www/horas/Espanol/Psalterium/Psalmi matutinum.txt
web/www/horas/Francais/Psalterium/Psalmi matutinum.txt
web/www/horas/Italiano/Psalterium/Psalmi matutinum.txt
web/www/horas/Latin/Psalterium/Matutinum Special.txt
web/www/horas/Latin/Psalterium/Psalmi matutinum.txt
web/www/horas/Latin/TemporaM/Pasc2-0.txt
web/www/horas/Latin/TemporaM/Pasc3-0.txt
web/www/horas/Latin/TemporaM/Pasc4-0.txt
web/www/horas/Latin/TemporaM/Pasc5-0.txt
web/www/horas/Polski/Psalterium/Matutinum Special.txt
web/www/horas/Polski/TemporaM/Pasc2-0.txt
web/www/horas/Polski/TemporaM/Pasc3-0.txt

MONASTIC Matutinum Eastertide

---

web/cgi-bin/horas/monastic.pl

MONASTIC code: handling comments in LectioE correction

---

web/www/horas/Latin/Tempora/Quad5-5Feria.txt

MONASTIC Quad5-5 fix oratio

---

web/www/horas/English/Psalterium/Matutinum Special.txt
web/www/horas/English/SanctiM/03-25.txt
web/www/horas/English/TemporaM/Pasc3-0.txt
web/www/horas/Latin/Psalterium/Major Special.txt
web/www/horas/Latin/Psalterium/Matutinum Special.txt
web/www/horas/Latin/Psalterium/Psalmi matutinum.txt
web/www/horas/Latin/SanctiM/03-21.txt
web/www/horas/Latin/TemporaM/Pasc3-0.txt

MONASTIC Various fixes

---

web/www/horas/Deutsch/Commune/C3p.txt
web/www/horas/Italiano/Commune/C3p.txt
web/www/horas/Magyar/Commune/C3p.txt
web/www/horas/Polski/Commune/C3p.txt

*/C3p remove section which causes loop

---

web/cgi-bin/horas/specmatins.pl

code: Invit in Trident/Monastic during Lent

---

web/cgi-bin/horas/monastic.pl
web/www/horas/English/TemporaM/Pasc0-0.txt
web/www/horas/Latin/Tempora/Quad6-0.txt
web/www/horas/Latin/TemporaM/Pasc0-0.txt
web/www/horas/Latin/TemporaM/Pasc0-1.txt
web/www/horas/Latin/TemporaM/Pasc0-2.txt
web/www/horas/Latin/TemporaM/Pasc0-3.txt
web/www/horas/Latin/TemporaM/Pasc0-4.txt
web/www/horas/Latin/TemporaM/Pasc0-5.txt
web/www/horas/Latin/TemporaM/Pasc0-6.txt
web/www/horas/Latin/TemporaM/Quad6-4.txt

MONASTIC files update

---

web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/specials.pl
web/www/horas/Deutsch/Psalterium/Psalmi major.txt
web/www/horas/English/Psalterium/Psalmi major.txt
web/www/horas/Espanol/Psalterium/Psalmi major.txt
web/www/horas/Francais/Psalterium/Psalmi major.txt
web/www/horas/Italiano/Psalterium/Psalmi major.txt
web/www/horas/Latin/Commune/C10.txt
web/www/horas/Latin/CommuneM/C10p.txt
web/www/horas/Latin/Psalterium/Psalmi major.txt
web/www/horas/Polski/Psalterium/Psalmi major.txt

Monastic C10 in Eastertide update

---

web/www/horas/Latin/CommuneM/C1p.txt
web/www/horas/Latin/SanctiM/04-21.txt
web/www/horas/Latin/SanctiM/04-25.txt
web/www/horas/Latin/SanctiM/05-02.txt
web/www/horas/Latin/SanctiM/05-09.txt
web/www/horas/Latin/SanctiM/05-11.txt
web/www/horas/Latin/SanctiM/05-25.txt
web/www/horas/Latin/SanctiM/05-26.txt
web/www/horas/Latin/SanctiM/05-27.txt

MONASTIC Sancti Matutinum: April fixes + May

---

web/www/horas/Polski/Psalterium/Psalmi matutinum.txt
web/www/horas/Polski/Regula/04-11.txt
web/www/horas/Polski/Sancti/05-01.txt
web/www/horas/Polski/Tempora/Pasc3-0.txt

Polski updates

---

web/www/horas/Latin/SanctiM/04-29.txt

MONASTIC 04-29 update

---

web/cgi-bin/horas/monastic.pl
web/www/horas/English/SanctiM/05-01.txt
web/www/horas/Italiano/SanctiM/05-01.txt
web/www/horas/Latin/SanctiM/05-01.txt
web/www/horas/Polski/SanctiM/05-01.txt

MONASTIC {Latin,English,Polski,Italiano} 05-01 Matutinum

---

web/www/horas/English/TemporaM/Pent16-0.txt
web/www/horas/Latin/SanctiM/09-21.txt

MONASTIC forgotten changes

---

web/www/horas/English/TemporaM/Pent03-0.txt
web/www/horas/English/TemporaM/Pent04-0.txt
web/www/horas/English/TemporaM/Pent05-0.txt
web/www/horas/English/TemporaM/Pent06-0.txt
web/www/horas/English/TemporaM/Pent07-0.txt
web/www/horas/Latin/TemporaM/Pent02-0.txt
web/www/horas/Latin/TemporaM/Pent03-0.txt
web/www/horas/Latin/TemporaM/Pent04-0.txt
web/www/horas/Latin/TemporaM/Pent05-0.txt
web/www/horas/Latin/TemporaM/Pent06-0.txt
web/www/horas/Latin/TemporaM/Pent07-0.txt
web/www/horas/Polski/TemporaM/Pent03-0.txt
web/www/horas/Polski/TemporaM/Pent04-0.txt
web/www/horas/Polski/TemporaM/Pent05-0.txt
web/www/horas/Polski/TemporaM/Pent06-0.txt
web/www/horas/Polski/TemporaM/Pent07-0.txt

MONASTIC Sundays 2nd to 7th Matutinum update

---

web/cgi-bin/horas/specials.pl

fix Loops in Completorium mentioned in #2515

---

web/cgi-bin/horas/specials.pl
web/www/horas/Latin/Psalterium/Minor Special.txt

Veni Creator - old version

---

web/www/horas/Latin/Psalterium/Psalmi matutinum.txt
web/www/horas/Latin/Tempora/Pasc5-4.txt

Ascension old Matutinum Hymn as link + accents in Psalmi matutinum

---

web/cgi-bin/horas/specmatins.pl
web/www/horas/English/Sancti/07-22.txt
web/www/horas/English/SanctiM/07-02.txt
web/www/horas/English/SanctiM/07-11.txt
web/www/horas/English/SanctiM/07-25.txt
web/www/horas/English/SanctiM/07-26.txt
web/www/horas/Latin/Sancti/07-22.txt
web/www/horas/Latin/SanctiM/07-02.txt
web/www/horas/Latin/SanctiM/07-11.txt
web/www/horas/Latin/SanctiM/07-25.txt
web/www/horas/Latin/SanctiM/07-26.txt
web/www/horas/Polski/SanctiM/07-02.txt
web/www/horas/Polski/SanctiM/07-11.txt
web/www/horas/Polski/SanctiM/07-25.txt
web/www/horas/Polski/SanctiM/07-26.txt

MONASTIC Sancti July - Matutinum

---

web/www/horas/English/TemporaM/Pasc7-0.txt
web/www/horas/Latin/Tempora/Pasc7-0.txt
web/www/horas/Latin/TemporaM/Pasc7-0.txt
web/www/horas/Polski/TemporaM/Pasc7-0.txt

Pentecost update

---

web/www/horas/Latin/TemporaM/Pasc7-6.txt

MONASTIC Pasc7-6 psalm division

---

web/www/horas/Latin/Psalterium/Matutinum Special.txt
web/www/horas/Latin/Tempora/Pasc7-3.txt
web/www/horas/Latin/Tempora/Pent01-0.txt

Pasc7-3 Pent01-0 Matutinum Special - updates

---

web/www/horas/Latin/TemporaM/Pent01-5.txt
web/www/horas/Latin/TemporaM/Pent01-6.txt
web/www/horas/Latin/TemporaM/Pent02-1.txt
web/www/horas/Latin/TemporaM/Pent02-2.txt
web/www/horas/Latin/TemporaM/Pent02-3.txt
web/www/horas/Latin/TemporaM/Pent02-4.txt

MONASTIC Pent01-5 - Pent02-4 - no doxology as there is no Octavae

---

web/www/horas/Polski/Martyrologium/05-18.txt
web/www/horas/Polski/Regula/01-29.txt
web/www/horas/Polski/Sancti/12-08.txt
web/www/horas/Polski/Tempora/Pent01-4.txt
web/www/horas/Polski/TemporaM/Pasc4-0.txt
web/www/horas/Polski/TemporaM/Pasc5-4.txt
web/www/horas/Polski/TemporaM/Pent01-0.txt
web/www/horas/Polski/TemporaM/Pent01-4.txt

Polski/* - translations + typos

---

web/www/horas/Bea/Commune
web/www/horas/Bea/CommuneM
web/www/horas/Bea/Martyrologium
web/www/horas/Bea/Ordinarium
web/www/horas/Bea/Psalterium
web/www/horas/Bea/Regula
web/www/horas/Bea/Sancti
web/www/horas/Bea/SanctiM
web/www/horas/Bea/Tempora
web/www/horas/Bea/TemporaM
web/www/horas/Bea/psalms
web/www/horas/Bea/psalms1
web/www/horas/Linguae.txt

Rename Bea => Latin-Bea

---

standalone/tools/epubgen2/Ewebdia.pl
web/cgi-bin/horas/horas.pl

code: move ante_post function introduced to fix epubgen2 to proper place

---

web/www/horas/English/TemporaM/Pent02-5.txt
web/www/horas/Latin/SanctiM/06-14.txt
web/www/horas/Latin/TemporaM/Pent02-5.txt

MONASTIC small updates

---

web/cgi-bin/DivinumOfficium/Main.pm
web/cgi-bin/horas/Ckalendar.pl
web/cgi-bin/horas/Cofficium.pl
web/cgi-bin/horas/Pofficium.pl
web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/webdia.pl
web/cgi-bin/missa/Ckalendar.pl
web/cgi-bin/missa/Cmissa.pl
web/cgi-bin/missa/Emissa.pl
web/cgi-bin/missa/kalendar.pl
web/cgi-bin/missa/missa.pl
web/cgi-bin/missa/webdia.pl
web/www/horas/Versions.txt

code improving, cleaning and fixing

---

web/cgi-bin/DivinumOfficium/Main.pm
web/cgi-bin/horas/Ckalendar.pl
web/cgi-bin/horas/Cofficium.pl
web/cgi-bin/horas/Pofficium.pl
web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/webdia.pl
web/cgi-bin/missa/Ckalendar.pl
web/cgi-bin/missa/Cmissa.pl
web/cgi-bin/missa/Emissa.pl
web/cgi-bin/missa/kalendar.pl
web/cgi-bin/missa/missa.pl
web/cgi-bin/missa/webdia.pl
web/www/horas/Versions.txt

Reverts DivinumOfficium/divinum-officium#2542

Revert "code improving, cleaning and fixing"

---

web/cgi-bin/DivinumOfficium/Main.pm
web/cgi-bin/horas/Ckalendar.pl
web/cgi-bin/horas/Cofficium.pl
web/cgi-bin/horas/Pofficium.pl
web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/webdia.pl
web/cgi-bin/missa/Ckalendar.pl
web/cgi-bin/missa/Cmissa.pl
web/cgi-bin/missa/Emissa.pl
web/cgi-bin/missa/kalendar.pl
web/cgi-bin/missa/missa.pl
web/cgi-bin/missa/webdia.pl
web/www/horas/Versions.txt

Remake #2542

---

web/cgi-bin/DivinumOfficium/Main.pm
web/cgi-bin/horas/Ckalendar.pl
web/cgi-bin/horas/Cofficium.pl
web/cgi-bin/horas/Pofficium.pl
web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/webdia.pl
web/cgi-bin/missa/Ckalendar.pl
web/cgi-bin/missa/Cmissa.pl
web/cgi-bin/missa/Emissa.pl
web/cgi-bin/missa/kalendar.pl
web/cgi-bin/missa/missa.pl
web/cgi-bin/missa/webdia.pl
web/www/horas/Versions.txt

Reverts DivinumOfficium/divinum-officium#2548

Revert "Remake #2542"

---

web/www/horas/English/Commune/C1.txt
web/www/horas/Latin/Commune/C1.txt

C1 - old hymn as link

---

web/cgi-bin/DivinumOfficium/Main.pm
web/cgi-bin/horas/Ckalendar.pl
web/cgi-bin/horas/Cofficium.pl
web/cgi-bin/horas/Pofficium.pl
web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/webdia.pl
web/cgi-bin/missa/Ckalendar.pl
web/cgi-bin/missa/Cmissa.pl
web/cgi-bin/missa/Emissa.pl
web/cgi-bin/missa/kalendar.pl
web/cgi-bin/missa/missa.pl
web/cgi-bin/missa/webdia.pl
web/www/horas/Versions.txt

Remake of Remake #2542

---

web/cgi-bin/missa/Cmissa.pl
web/www/horas/Polski/Psalterium/Psalmi matutinum.txt

fix error in Cmissa.pl

---

web/cgi-bin/DivinumOfficium/Main.pm

code: fix #2555

---

web/www/horas/English/Commune/C12.txt
web/www/horas/English/CommuneM/C10.txt
web/www/horas/English/Sancti/07-02.txt
web/www/horas/English/Sancti/08-22.txt
web/www/horas/English/Sancti/09-08.txt
web/www/horas/English/Sancti/09-12.txt
web/www/horas/Latin/Commune/C12.txt
web/www/horas/Latin/CommuneM/C10.txt
web/www/horas/Latin/Sancti/07-02.txt
web/www/horas/Latin/Sancti/08-22.txt
web/www/horas/Latin/Sancti/09-08.txt
web/www/horas/Latin/Sancti/09-12.txt

Responsory 'Felix namque' as link

---

web/cgi-bin/missa/propers.pl
web/www/missa/Cesky/Ordo/Ordo.txt
web/www/missa/Deutsch/Ordo/Ordo.txt
web/www/missa/English/Ordo/Ordo.txt
web/www/missa/Espanol/Ordo/Ordo.txt
web/www/missa/French/Ordo/Ordo.txt
web/www/missa/Italiano/Ordo/Ordo.txt
web/www/missa/Latin/Ordo/Ordo.txt
web/www/missa/Magyar/Ordo/Ordo.txt
web/www/missa/Polski/Ordo/Ordo.txt
web/www/missa/Portugues/Ordo/Ordo.txt

No code changes required: instead the nD condition was applied to the Lavabo &Gloria.  NB that the "new" rubric is no longer needed. 
(Tested on 12 requests including all 9 languages.)

requiem/gloria #278

---

web/cgi-bin/horas/specmatins.pl
web/www/horas/Magyar/Psalterium/Translate.txt

code: implement #254

---

web/www/horas/Latin/TemporaM/Quad6-4.txt
web/www/horas/Latin/TemporaM/Quad6-5.txt
web/www/horas/Latin/TemporaM/Quad6-6.txt

MONASTIC Quad6-[456] update

---

web/cgi-bin/horas/monastic.pl

MONASTIC code: easy conditions

---

web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/monastic.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/horas/specials.pl
web/cgi-bin/horas/specmatins.pl
web/www/horas/English/Commune/C12.txt
web/www/horas/English/Commune/C9.txt
web/www/horas/English/CommuneM/C8.txt
web/www/horas/Espanol/Commune/C12.txt
web/www/horas/Italiano/Commune/C12.txt
web/www/horas/Latin/Commune/C12.txt
web/www/horas/Latin/Commune/C12A.txt
web/www/horas/Latin/Commune/C12Q.txt
web/www/horas/Latin/Commune/C9.txt
web/www/horas/Latin/CommuneM/C12.txt
web/www/horas/Latin/CommuneM/C12A.txt
web/www/horas/Latin/CommuneM/C12N.txt
web/www/horas/Latin/CommuneM/C12P.txt
web/www/horas/Latin/CommuneM/C8.txt
web/www/horas/Latin/CommuneM/C9.txt
web/www/horas/Magyar/Commune/C12.txt
web/www/horas/Polski/Commune/C12.txt
web/www/horas/Polski/Commune/C9.txt

MONASTIC optional (votive) offices C8 C9 C12

---

web/cgi-bin/DivinumOfficium/Main.pm
web/cgi-bin/horas/monastic.pl

small code updates

---

web/cgi-bin/DivinumOfficium/Main.pm

code: liturgical_color correction

---

web/www/horas/Latin/Sancti/08-13t.txt
web/www/horas/Latin/Sancti/09-09t.txt
web/www/horas/Latin/Sancti/09-11t.txt
web/www/horas/Latin/Sancti/09-12t.txt
web/www/horas/Latin/Sancti/09-15t.txt

Trident: Matutinum readings correction

---

web/www/horas/Deutsch/Sancti/09-15.txt
web/www/horas/Deutsch/Sancti/09-15t.txt
web/www/horas/English/Sancti/09-15t.txt
web/www/horas/Espanol/Sancti/09-15.txt
web/www/horas/Espanol/Sancti/09-15a.txt
web/www/horas/Espanol/Sancti/09-15t.txt
web/www/horas/Francais/Sancti/09-15.txt
web/www/horas/Francais/Sancti/09-15a.txt
web/www/horas/Italiano/Sancti/09-15.txt
web/www/horas/Italiano/Sancti/09-15t.txt
web/www/horas/Latin/Sancti/09-15.txt
web/www/horas/Latin/Sancti/09-15a.txt
web/www/horas/Magyar/Sancti/09-15.txt

09-15 Matutinum 9th reading correction

---

web/cgi-bin/horas/specials.pl
web/www/horas/English/Sancti/09-16.txt
web/www/horas/Espanol/Sancti/09-16.txt
web/www/horas/Francais/Sancti/09-16.txt
web/www/horas/Italiano/Sancti/09-16.txt
web/www/horas/Latin/Sancti/09-16.txt
web/www/horas/Polski/Sancti/09-16.txt

Trident 09-16 add missing 1st vespera commemoratio + minor code update

---

web/www/horas/Latin/Commune/C3.txt

C3 HymnusM Matutinum as link

---

web/www/horas/English/CommuneM/C1a.txt
web/www/horas/English/Sancti/09-21.txt
web/www/horas/English/SanctiM/09-08.txt
web/www/horas/English/SanctiM/09-21.txt
web/www/horas/Latin/CommuneM/C1a.txt
web/www/horas/Latin/Sancti/09-21.txt
web/www/horas/Latin/SanctiM/09-08.txt
web/www/horas/Latin/SanctiM/09-21.txt

09-08 & 09-21 update

---

web/cgi-bin/horas/Cofficium.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/missa/Cmissa.pl
web/cgi-bin/missa/missa.pl

One kalendar for officium/missa/compare

---

web/www/horas/Latin/Sancti/09-20.txt

S. Eustachii et Sociorum Martyrum is a group of martyrs, so plural in the Benediction.

Cuius->Quorum

---

web/cgi-bin/horas/horascommon.pl
web/cgi-bin/horas/specials.pl

Fixes #710.  Requires Tr file to work properly: at time of writing see 3-19-2023 instead of 3-19-2017 .

Notice concurrence for transfered office at Vespers.

---

web/www/horas/Polski/Commune/C3.txt
web/www/horas/Polski/Sancti/11-01.txt
web/www/horas/Polski/SanctiM/11-01.txt

Polski 11-01 translation

---

web/www/horas/Latin/CommuneM/C1.txt
web/www/horas/Latin/SanctiM/10-DU.txt
web/www/horas/Latin/SanctiM/11-01.txt

MONASTIC small fixes, accents

---

web/www/horas/English/psalms1/Psalm260.txt
web/www/horas/English/psalms1/Psalm261.txt
web/www/horas/English/psalms1/Psalm262.txt
web/www/horas/Latin/Commune/C8.txt
web/www/horas/Latin/CommuneM/C8.txt
web/www/horas/Latin/SanctiM/11-10.txt
web/www/horas/Latin/psalms1/Psalm260.txt
web/www/horas/Latin/psalms1/Psalm261.txt
web/www/horas/Latin/psalms1/Psalm262.txt

MONASTIC Canticles for Dedicatione + stars & align also English
C8 accents in old hymns
MONASTIC C8 accents & Antiphonas horas
MONASTIC 11-10 oratio as link
+AMDG+

Monastic related updates

---

web/www/horas/Polski/Commune/C4.txt
web/www/horas/Polski/Commune/C8.txt
web/www/horas/Polski/Commune/C9.txt
web/www/horas/Polski/Sancti/11-09.txt
web/www/horas/Polski/Sancti/11-11.txt
web/www/horas/Polski/SanctiM/11-09.txt
web/www/horas/Polski/SanctiM/11-11.txt
web/www/horas/Polski/SanctiM/11-14.txt
web/www/horas/Polski/Tempora/102-0.txt
web/www/horas/Polski/Tempora/105-6.txt
web/www/horas/Polski/Tempora/113-1.txt
web/www/horas/Polski/Tempora/113-2.txt
web/www/horas/Polski/Tempora/113-3.txt
web/www/horas/Polski/Tempora/113-4.txt
web/www/horas/Polski/Tempora/113-5.txt
web/www/horas/Polski/Tempora/113-6.txt
web/www/horas/Polski/Tempora/114-0.txt
web/www/horas/Polski/Tempora/114-2.txt
web/www/horas/Polski/Tempora/114-3.txt
web/www/horas/Polski/Tempora/115-0.txt
web/www/horas/Polski/Tempora/115-2.txt
web/www/horas/Polski/Tempora/115-6.txt
web/www/horas/Polski/Tempora/Pent08-0.txt
web/www/horas/Polski/TemporaM/102-0.txt
web/www/horas/Polski/TemporaM/114-0.txt
web/www/horas/Polski/TemporaM/Epi6-0.txt
web/www/horas/Polski/TemporaM/Pent08-0.txt

Polski more translation + corrections

---

web/www/horas/English/SanctiM/11-17.txt
web/www/horas/Latin/CommuneM/C8.txt
web/www/horas/Latin/SanctiM/11-14.txt
web/www/horas/Latin/SanctiM/11-17.txt
web/www/horas/Polski/SanctiM/11-14.txt
web/www/horas/Polski/SanctiM/11-17.txt

MONASTIC C8 11-14 11-17 update

---

web/cgi-bin/horas/Cofficium.pl
web/cgi-bin/horas/Pofficium.pl
web/cgi-bin/horas/kalendar.pl
web/cgi-bin/horas/officium.pl
web/cgi-bin/missa/missa.pl

code: update calling ordo and compare

---

web/www/horas/English/Martyrologium/12-09.txt

Fix "awn church" typo in Eng. Martyr. 12-09

---

web/cgi-bin/horas/monastic.pl

code: monastic clean

---

web/www/horas/Deutsch/Sancti/12-25.txt

Deutsch/12-25 remove links, which causes loop

---

web/cgi-bin/horas/horascommon.pl

code: add Commemoratio to title

---

web/www/horas/Polski/Commune/C1p.txt
web/www/horas/Polski/Commune/C3.txt
web/www/horas/Polski/Commune/C4.txt
web/www/horas/Polski/Commune/C4a.txt
web/www/horas/Polski/Commune/C4ap.txt
web/www/horas/Polski/Commune/C5a.txt
web/www/horas/Polski/Sancti/10-02.txt
web/www/horas/Polski/Sancti/12-25.txt
web/www/horas/Polski/Sancti/12-27.txt
web/www/horas/Polski/Sancti/12-28.txt
web/www/horas/Polski/SanctiM/12-21.txt
web/www/horas/Polski/Tempora/Adv2-1.txt
web/www/horas/Polski/Tempora/Adv2-2.txt
web/www/horas/Polski/Tempora/Pasc5-4.txt
web/www/horas/Polski/Tempora/Pasc7-0.txt
web/www/horas/Polski/TemporaM/Epi6-0.txt
web/www/horas/Polski/TemporaM/Pent09-0.txt

Polski - corrections
